Access slices by index

SOURCE:
fn borgo_main() -> string {
    let xs = ["a"];
    xs[0]
}

OUTPUT:
fn () -> string
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "borgo_main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "string",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "string",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "xs",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 8
                          },
                          "end": {
                            "line": 2,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "Slice",
                        "args": [
                          {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  },
                  "value": {
                    "Literal": {
                      "lit": {
                        "Slice": [
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "a",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 14
                                },
                                "end": {
                                  "line": 2,
                                  "col": 17
                                },
                                "file": 99
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "id": "Slice",
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 13
                        },
                        "end": {
                          "line": 2,
                          "col": 18
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "Slice",
                      "args": [
                        {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 4
                    },
                    "end": {
                      "line": 2,
                      "col": 19
                    },
                    "file": 99
                  }
                }
              },
              {
                "Index": {
                  "expr": {
                    "Var": {
                      "value": "xs",
                      "decl": {
                        "start": {
                          "line": 2,
                          "col": 8
                        },
                        "end": {
                          "line": 2,
                          "col": 10
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Slice",
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 4
                        },
                        "end": {
                          "line": 3,
                          "col": 6
                        },
                        "file": 99
                      }
                    }
                  },
                  "index": {
                    "Literal": {
                      "lit": {
                        "Int": 0
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 7
                        },
                        "end": {
                          "line": 3,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 4
                    },
                    "end": {
                      "line": 3,
                      "col": 9
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 26
              },
              "end": {
                "line": 4,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "string",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "string",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 0
        },
        "end": {
          "line": 4,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
