Check if type implements trait

SOURCE:
struct Baz { x: int }

impl (b: Baz) {
    fn bar(_: string) -> int {
      b.x
    }
}

fn main() -> int {
    interface Foo {
        fn bar(x: string) -> int
    }

    fn check(f: Foo) -> int {
        f.bar("yo")
    }

    check(Baz { x: 1 })
}

OUTPUT:
fn () -> int
---
No errors.
---
[
  {
    "StructDef": {
      "def": {
        "name": "Baz",
        "generics": [],
        "fields": [
          {
            "name": "x",
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ty": {
              "generics": [],
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        ]
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 21
        },
        "file": 99
      }
    }
  },
  {
    "ImplBlock": {
      "ann": {
        "Con": {
          "name": "Baz",
          "args": []
        }
      },
      "self_name": "b",
      "ty": {
        "Con": {
          "id": "Baz",
          "args": []
        }
      },
      "items": [
        {
          "Closure": {
            "fun": {
              "name": "bar",
              "generics": [],
              "args": [
                {
                  "pat": {
                    "Wild": {
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 12
                        },
                        "end": {
                          "line": 4,
                          "col": 13
                        },
                        "file": 99
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              ],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "FieldAccess": {
                        "expr": {
                          "Var": {
                            "value": "b",
                            "decl": {
                              "start": {
                                "line": 3,
                                "col": 1
                              },
                              "end": {
                                "line": 7,
                                "col": 1
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "id": "Baz",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 7
                              },
                              "end": {
                                "line": 5,
                                "col": 8
                              },
                              "file": 99
                            }
                          }
                        },
                        "field": "x",
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 9
                          },
                          "end": {
                            "line": 5,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 30
                    },
                    "end": {
                      "line": 6,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                ],
                "bounds": [],
                "ret": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              }
            },
            "span": {
              "start": {
                "line": 4,
                "col": 5
              },
              "end": {
                "line": 6,
                "col": 5
              },
              "file": 99
            }
          }
        }
      ],
      "generics": [],
      "span": {
        "start": {
          "line": 3,
          "col": 1
        },
        "end": {
          "line": 7,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Trait": {
                  "name": "Foo",
                  "generics": [],
                  "supertraits": [],
                  "items": [
                    {
                      "Closure": {
                        "fun": {
                          "name": "bar",
                          "generics": [],
                          "args": [
                            {
                              "pat": {
                                "Type": {
                                  "ident": "x",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 11,
                                      "col": 16
                                    },
                                    "end": {
                                      "line": 11,
                                      "col": 17
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "ann": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "ty": {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            }
                          ],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "ann": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "body": "Noop",
                          "bounded_ty": {
                            "generics": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              }
                            }
                          }
                        },
                        "kind": "TopLevel",
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            }
                          }
                        },
                        "span": {
                          "start": {
                            "line": 11,
                            "col": 12
                          },
                          "end": {
                            "line": 11,
                            "col": 33
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "span": {
                    "start": {
                      "line": 10,
                      "col": 5
                    },
                    "end": {
                      "line": 12,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              {
                "Closure": {
                  "fun": {
                    "name": "check",
                    "generics": [],
                    "args": [
                      {
                        "pat": {
                          "Type": {
                            "ident": "f",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 14,
                                "col": 14
                              },
                              "end": {
                                "line": 14,
                                "col": 15
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "Foo",
                            "args": []
                          }
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [
                          {
                            "Call": {
                              "func": {
                                "FieldAccess": {
                                  "expr": {
                                    "Var": {
                                      "value": "f",
                                      "decl": {
                                        "start": {
                                          "line": 14,
                                          "col": 14
                                        },
                                        "end": {
                                          "line": 14,
                                          "col": 15
                                        },
                                        "file": 99
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "id": "Foo",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 15,
                                          "col": 9
                                        },
                                        "end": {
                                          "line": 15,
                                          "col": 10
                                        },
                                        "file": 99
                                      }
                                    }
                                  },
                                  "field": "bar",
                                  "ty": {
                                    "Fun": {
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "string",
                                            "args": []
                                          }
                                        }
                                      ],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "id": "int",
                                          "args": []
                                        }
                                      }
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 15,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 15,
                                      "col": 14
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "args": [
                                {
                                  "Literal": {
                                    "lit": {
                                      "String": {
                                        "Single": "yo"
                                      }
                                    },
                                    "ty": {
                                      "Con": {
                                        "id": "string",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 15,
                                        "col": 15
                                      },
                                      "end": {
                                        "line": 15,
                                        "col": 19
                                      },
                                      "file": 99
                                    }
                                  }
                                }
                              ],
                              "ty": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 15,
                                  "col": 14
                                },
                                "end": {
                                  "line": 15,
                                  "col": 19
                                },
                                "file": 99
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 14,
                            "col": 29
                          },
                          "end": {
                            "line": 16,
                            "col": 5
                          },
                          "file": 99
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "Foo",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      }
                    }
                  },
                  "kind": "Inline",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "Foo",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 14,
                      "col": 5
                    },
                    "end": {
                      "line": 16,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "check",
                      "decl": {
                        "start": {
                          "line": 14,
                          "col": 5
                        },
                        "end": {
                          "line": 16,
                          "col": 5
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "Foo",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 18,
                          "col": 5
                        },
                        "end": {
                          "line": 18,
                          "col": 10
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "StructCall": {
                        "name": "Baz",
                        "fields": [
                          {
                            "name": "x",
                            "value": {
                              "Literal": {
                                "lit": {
                                  "Int": 1
                                },
                                "ty": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 18,
                                    "col": 20
                                  },
                                  "end": {
                                    "line": 18,
                                    "col": 21
                                  },
                                  "file": 99
                                }
                              }
                            }
                          }
                        ],
                        "rest": null,
                        "ty": {
                          "Con": {
                            "id": "Baz",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 18,
                            "col": 15
                          },
                          "end": {
                            "line": 18,
                            "col": 22
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 18,
                      "col": 10
                    },
                    "end": {
                      "line": 18,
                      "col": 23
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 9,
                "col": 18
              },
              "end": {
                "line": 19,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 9,
          "col": 1
        },
        "end": {
          "line": 19,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
