For loops.

SOURCE:
fn borgo_main() {
  for x in ["a"] {
    x as string;
  }

  for (index, value) in ["a"].enumerate() {
      index as int;
      value as string;
  }
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "borgo_main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Loop": {
                  "kind": {
                    "WithCondition": {
                      "binding": {
                        "pat": {
                          "Type": {
                            "ident": "x",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 6
                              },
                              "end": {
                                "line": 2,
                                "col": 7
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": "Unknown",
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      },
                      "expr": {
                        "Literal": {
                          "lit": {
                            "Slice": [
                              {
                                "Literal": {
                                  "lit": {
                                    "String": [
                                      "a",
                                      null
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 12
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 15
                                    },
                                    "file": 99
                                  }
                                }
                              }
                            ]
                          },
                          "ty": {
                            "Con": {
                              "id": "Slice",
                              "args": [
                                {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 11
                            },
                            "end": {
                              "line": 2,
                              "col": 16
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "x",
                                "decl": {
                                  "start": {
                                    "line": 2,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 7
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 3,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 3,
                                    "col": 5
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 4
                              },
                              "end": {
                                "line": 3,
                                "col": 15
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 17
                        },
                        "end": {
                          "line": 4,
                          "col": 3
                        },
                        "file": 99
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 2
                    },
                    "end": {
                      "line": 4,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              },
              {
                "Loop": {
                  "kind": {
                    "WithCondition": {
                      "binding": {
                        "pat": {
                          "Struct": {
                            "ident": "Tuple2",
                            "fields": [
                              {
                                "name": "first",
                                "value": {
                                  "Type": {
                                    "ident": "index",
                                    "is_mut": false,
                                    "ann": "Unknown",
                                    "span": {
                                      "start": {
                                        "line": 6,
                                        "col": 7
                                      },
                                      "end": {
                                        "line": 6,
                                        "col": 12
                                      },
                                      "file": 99
                                    }
                                  }
                                }
                              },
                              {
                                "name": "second",
                                "value": {
                                  "Type": {
                                    "ident": "value",
                                    "is_mut": false,
                                    "ann": "Unknown",
                                    "span": {
                                      "start": {
                                        "line": 6,
                                        "col": 14
                                      },
                                      "end": {
                                        "line": 6,
                                        "col": 19
                                      },
                                      "file": 99
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "id": "Tuple2",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "int",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 6
                              },
                              "end": {
                                "line": 6,
                                "col": 20
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": "Unknown",
                        "ty": {
                          "Con": {
                            "id": "Tuple2",
                            "args": [
                              {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ]
                          }
                        }
                      },
                      "expr": {
                        "Call": {
                          "func": {
                            "FieldAccess": {
                              "expr": {
                                "Literal": {
                                  "lit": {
                                    "Slice": [
                                      {
                                        "Literal": {
                                          "lit": {
                                            "String": [
                                              "a",
                                              null
                                            ]
                                          },
                                          "ty": {
                                            "Con": {
                                              "id": "string",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 6,
                                              "col": 25
                                            },
                                            "end": {
                                              "line": 6,
                                              "col": 28
                                            },
                                            "file": 99
                                          }
                                        }
                                      }
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "id": "Slice",
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 6,
                                      "col": 24
                                    },
                                    "end": {
                                      "line": 6,
                                      "col": 29
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "field": "enumerate",
                              "ty": {
                                "Fun": {
                                  "args": [],
                                  "bounds": [],
                                  "ret": {
                                    "Con": {
                                      "id": "EnumerateSlice",
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 30
                                },
                                "end": {
                                  "line": 6,
                                  "col": 39
                                },
                                "file": 99
                              }
                            }
                          },
                          "args": [],
                          "ty": {
                            "Con": {
                              "id": "EnumerateSlice",
                              "args": [
                                {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 30
                            },
                            "end": {
                              "line": 6,
                              "col": 39
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "index",
                                "decl": {
                                  "start": {
                                    "line": 6,
                                    "col": 7
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 12
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 7,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 7,
                                    "col": 11
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 7,
                                "col": 6
                              },
                              "end": {
                                "line": 7,
                                "col": 18
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "value",
                                "decl": {
                                  "start": {
                                    "line": 6,
                                    "col": 14
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 19
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 8,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 8,
                                    "col": 11
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 8,
                                "col": 6
                              },
                              "end": {
                                "line": 8,
                                "col": 21
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 42
                        },
                        "end": {
                          "line": 9,
                          "col": 3
                        },
                        "file": 99
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 2
                    },
                    "end": {
                      "line": 9,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Var": -333
            },
            "span": {
              "start": {
                "line": 1,
                "col": 16
              },
              "end": {
                "line": 10,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 0
        },
        "end": {
          "line": 10,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
