For loops.

SOURCE:
fn borgo_main() {
  for x in ["a"] {
    x as string;
  }

  for (index, value) in ["a"].enumerate() {
      index as int;
      value as string;
  }
}

OUTPUT:
fn () -> ()
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "borgo_main",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Loop": {
                        "kind": {
                          "WithCondition": {
                            "binding": {
                              "pat": {
                                "Type": {
                                  "ident": "x",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 7
                                    }
                                  }
                                }
                              },
                              "ann": "Unknown",
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              }
                            },
                            "expr": {
                              "Literal": {
                                "lit": {
                                  "Slice": [
                                    {
                                      "Literal": {
                                        "lit": {
                                          "String": [
                                            "a",
                                            null
                                          ]
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 2,
                                            "col": 12
                                          },
                                          "end": {
                                            "line": 2,
                                            "col": 15
                                          }
                                        }
                                      }
                                    }
                                  ]
                                },
                                "ty": {
                                  "Con": {
                                    "name": "Slice",
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      }
                                    ]
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 2,
                                    "col": 11
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 16
                                  }
                                }
                              }
                            }
                          }
                        },
                        "body": {
                          "Block": {
                            "stmts": [
                              {
                                "CheckType": {
                                  "expr": {
                                    "Var": {
                                      "value": "x",
                                      "decl": {
                                        "file_id": {
                                          "package": "user",
                                          "filename": "test.brg"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 2,
                                            "col": 6
                                          },
                                          "end": {
                                            "line": 2,
                                            "col": 7
                                          }
                                        }
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 3,
                                          "col": 4
                                        },
                                        "end": {
                                          "line": 3,
                                          "col": 5
                                        }
                                      }
                                    }
                                  },
                                  "ann": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 3,
                                      "col": 4
                                    },
                                    "end": {
                                      "line": 3,
                                      "col": 15
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 17
                              },
                              "end": {
                                "line": 4,
                                "col": 3
                              }
                            }
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 4,
                            "col": 3
                          }
                        }
                      }
                    },
                    {
                      "Loop": {
                        "kind": {
                          "WithCondition": {
                            "binding": {
                              "pat": {
                                "Struct": {
                                  "ident": "Tuple2",
                                  "fields": [
                                    {
                                      "name": "first",
                                      "value": {
                                        "Type": {
                                          "ident": "index",
                                          "is_mut": false,
                                          "ann": "Unknown",
                                          "span": {
                                            "start": {
                                              "line": 6,
                                              "col": 7
                                            },
                                            "end": {
                                              "line": 6,
                                              "col": 12
                                            }
                                          }
                                        }
                                      }
                                    },
                                    {
                                      "name": "second",
                                      "value": {
                                        "Type": {
                                          "ident": "value",
                                          "is_mut": false,
                                          "ann": "Unknown",
                                          "span": {
                                            "start": {
                                              "line": 6,
                                              "col": 14
                                            },
                                            "end": {
                                              "line": 6,
                                              "col": 19
                                            }
                                          }
                                        }
                                      }
                                    }
                                  ],
                                  "ty": {
                                    "Con": {
                                      "name": "Tuple2",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "int",
                                            "args": []
                                          }
                                        },
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 6,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 6,
                                      "col": 20
                                    }
                                  }
                                }
                              },
                              "ann": "Unknown",
                              "ty": {
                                "Con": {
                                  "name": "Tuple2",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "int",
                                        "args": []
                                      }
                                    },
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            "expr": {
                              "Call": {
                                "func": {
                                  "FieldAccess": {
                                    "expr": {
                                      "Literal": {
                                        "lit": {
                                          "Slice": [
                                            {
                                              "Literal": {
                                                "lit": {
                                                  "String": [
                                                    "a",
                                                    null
                                                  ]
                                                },
                                                "ty": {
                                                  "Con": {
                                                    "name": "string",
                                                    "args": []
                                                  }
                                                },
                                                "span": {
                                                  "start": {
                                                    "line": 6,
                                                    "col": 25
                                                  },
                                                  "end": {
                                                    "line": 6,
                                                    "col": 28
                                                  }
                                                }
                                              }
                                            }
                                          ]
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "Slice",
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "string",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 6,
                                            "col": 24
                                          },
                                          "end": {
                                            "line": 6,
                                            "col": 29
                                          }
                                        }
                                      }
                                    },
                                    "field": "enumerate",
                                    "ty": {
                                      "Fun": {
                                        "args": [],
                                        "bounds": [],
                                        "ret": {
                                          "Con": {
                                            "name": "EnumerateSlice",
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "string",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        },
                                        "id": -1
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 6,
                                        "col": 30
                                      },
                                      "end": {
                                        "line": 6,
                                        "col": 39
                                      }
                                    }
                                  }
                                },
                                "args": [],
                                "ty": {
                                  "Con": {
                                    "name": "EnumerateSlice",
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      }
                                    ]
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 30
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 39
                                  }
                                }
                              }
                            }
                          }
                        },
                        "body": {
                          "Block": {
                            "stmts": [
                              {
                                "CheckType": {
                                  "expr": {
                                    "Var": {
                                      "value": "index",
                                      "decl": {
                                        "file_id": {
                                          "package": "user",
                                          "filename": "test.brg"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 6,
                                            "col": 7
                                          },
                                          "end": {
                                            "line": 6,
                                            "col": 12
                                          }
                                        }
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 7,
                                          "col": 6
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 11
                                        }
                                      }
                                    }
                                  },
                                  "ann": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 7,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 18
                                    }
                                  }
                                }
                              },
                              {
                                "CheckType": {
                                  "expr": {
                                    "Var": {
                                      "value": "value",
                                      "decl": {
                                        "file_id": {
                                          "package": "user",
                                          "filename": "test.brg"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 6,
                                            "col": 14
                                          },
                                          "end": {
                                            "line": 6,
                                            "col": 19
                                          }
                                        }
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 8,
                                          "col": 6
                                        },
                                        "end": {
                                          "line": 8,
                                          "col": 11
                                        }
                                      }
                                    }
                                  },
                                  "ann": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 8,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 8,
                                      "col": 21
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 42
                              },
                              "end": {
                                "line": 9,
                                "col": 3
                              }
                            }
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 2
                          },
                          "end": {
                            "line": 9,
                            "col": 3
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 10,
                      "col": 1
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "Unit",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 10,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn borgo_main() {\n  for x in [\"a\"] {\n    x as string;\n  }\n\n  for (index, value) in [\"a\"].enumerate() {\n      index as int;\n      value as string;\n  }\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
