Generics in extern blocks

SOURCE:
use reflect

fn main() {
    let a = reflect.DeepEqual(1, false)
    let b = reflect.DeepEqual(1, 1)
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "UsePackage": {
      "import": {
        "name": "reflect",
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 12
          },
          "file": 99
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 12
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "a",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 9
                          },
                          "end": {
                            "line": 4,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "bool",
                        "args": []
                      }
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "reflect",
                              "decl": {
                                "start": {
                                  "line": 0,
                                  "col": 0
                                },
                                "end": {
                                  "line": 0,
                                  "col": 0
                                },
                                "file": -1
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "reflect",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 4,
                                  "col": 13
                                },
                                "end": {
                                  "line": 4,
                                  "col": 20
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "DeepEqual",
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "any",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "any",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "bool",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 21
                            },
                            "end": {
                              "line": 4,
                              "col": 30
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 31
                              },
                              "end": {
                                "line": 4,
                                "col": 32
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Bool": false
                            },
                            "ty": {
                              "Con": {
                                "id": "bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 34
                              },
                              "end": {
                                "line": 4,
                                "col": 39
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "bool",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 30
                        },
                        "end": {
                          "line": 4,
                          "col": 39
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 5
                    },
                    "end": {
                      "line": 4,
                      "col": 39
                    },
                    "file": 99
                  }
                }
              },
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "b",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 9
                          },
                          "end": {
                            "line": 5,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "bool",
                        "args": []
                      }
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "reflect",
                              "decl": {
                                "start": {
                                  "line": 0,
                                  "col": 0
                                },
                                "end": {
                                  "line": 0,
                                  "col": 0
                                },
                                "file": -1
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "reflect",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 13
                                },
                                "end": {
                                  "line": 5,
                                  "col": 20
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "DeepEqual",
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "any",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "any",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "bool",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 21
                            },
                            "end": {
                              "line": 5,
                              "col": 30
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 31
                              },
                              "end": {
                                "line": 5,
                                "col": 32
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 34
                              },
                              "end": {
                                "line": 5,
                                "col": 35
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "bool",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 30
                        },
                        "end": {
                          "line": 5,
                          "col": 35
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 5
                    },
                    "end": {
                      "line": 5,
                      "col": 35
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "bool",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 3,
                "col": 11
              },
              "end": {
                "line": 6,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 3,
          "col": 1
        },
        "end": {
          "line": 6,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
