Inference in loops

SOURCE:
fn borgo_main() {
    let rows = "yo"
      .split("\n")
      .map(|row| row.chars());

    for row in rows {
      row.enumerate();
    }
}

OUTPUT:
fn () -> ()
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "borgo_main",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Let": {
                        "binding": {
                          "pat": {
                            "Type": {
                              "ident": "rows",
                              "is_mut": false,
                              "ann": "Unknown",
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 8
                                },
                                "end": {
                                  "line": 2,
                                  "col": 12
                                }
                              }
                            }
                          },
                          "ann": "Unknown",
                          "ty": {
                            "Con": {
                              "name": "Seq",
                              "args": [
                                {
                                  "Con": {
                                    "name": "Seq",
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "Char",
                                          "args": []
                                        }
                                      }
                                    ]
                                  }
                                }
                              ]
                            }
                          }
                        },
                        "value": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Seq::map",
                                "decl": {
                                  "file_id": {
                                    "package": "dummy",
                                    "filename": "dummy"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 133,
                                      "col": 4
                                    },
                                    "end": {
                                      "line": 138,
                                      "col": 5
                                    }
                                  }
                                },
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "Seq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "String",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      },
                                      {
                                        "Fun": {
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "String",
                                                "args": []
                                              }
                                            }
                                          ],
                                          "bounds": [],
                                          "ret": {
                                            "Con": {
                                              "name": "Seq",
                                              "args": [
                                                {
                                                  "Con": {
                                                    "name": "Char",
                                                    "args": []
                                                  }
                                                }
                                              ]
                                            }
                                          },
                                          "fx": []
                                        }
                                      }
                                    ],
                                    "bounds": [],
                                    "ret": {
                                      "Con": {
                                        "name": "Seq",
                                        "args": [
                                          {
                                            "Con": {
                                              "name": "Seq",
                                              "args": [
                                                {
                                                  "Con": {
                                                    "name": "Char",
                                                    "args": []
                                                  }
                                                }
                                              ]
                                            }
                                          }
                                        ]
                                      }
                                    },
                                    "fx": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 4,
                                    "col": 7
                                  },
                                  "end": {
                                    "line": 4,
                                    "col": 10
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Call": {
                                  "func": {
                                    "Var": {
                                      "value": "String::split",
                                      "decl": {
                                        "file_id": {
                                          "package": "std",
                                          "filename": "core.brg"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 103,
                                            "col": 4
                                          },
                                          "end": {
                                            "line": 103,
                                            "col": 52
                                          }
                                        }
                                      },
                                      "ty": {
                                        "Fun": {
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "String",
                                                "args": []
                                              }
                                            },
                                            {
                                              "Con": {
                                                "name": "String",
                                                "args": []
                                              }
                                            }
                                          ],
                                          "bounds": [],
                                          "ret": {
                                            "Con": {
                                              "name": "Seq",
                                              "args": [
                                                {
                                                  "Con": {
                                                    "name": "String",
                                                    "args": []
                                                  }
                                                }
                                              ]
                                            }
                                          },
                                          "fx": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 3,
                                          "col": 7
                                        },
                                        "end": {
                                          "line": 3,
                                          "col": 12
                                        }
                                      }
                                    }
                                  },
                                  "args": [
                                    {
                                      "Literal": {
                                        "lit": {
                                          "String": "yo"
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "String",
                                            "args": []
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 3,
                                            "col": 7
                                          },
                                          "end": {
                                            "line": 3,
                                            "col": 12
                                          }
                                        }
                                      }
                                    },
                                    {
                                      "Literal": {
                                        "lit": {
                                          "String": "\n"
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "String",
                                            "args": []
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 3,
                                            "col": 13
                                          },
                                          "end": {
                                            "line": 3,
                                            "col": 17
                                          }
                                        }
                                      }
                                    }
                                  ],
                                  "ty": {
                                    "Con": {
                                      "name": "Seq",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "String",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 7
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 10
                                    }
                                  }
                                }
                              },
                              {
                                "Closure": {
                                  "fun": {
                                    "name": "__anonymous",
                                    "generics": [],
                                    "bounds": [],
                                    "args": [
                                      {
                                        "pat": {
                                          "Type": {
                                            "ident": "row",
                                            "is_mut": false,
                                            "ann": "Unknown",
                                            "span": {
                                              "start": {
                                                "line": 4,
                                                "col": 12
                                              },
                                              "end": {
                                                "line": 4,
                                                "col": 15
                                              }
                                            }
                                          }
                                        },
                                        "ann": "Unknown",
                                        "ty": {
                                          "Con": {
                                            "name": "String",
                                            "args": []
                                          }
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "Seq",
                                        "args": [
                                          {
                                            "Con": {
                                              "name": "Char",
                                              "args": []
                                            }
                                          }
                                        ]
                                      }
                                    },
                                    "ann": "Unknown",
                                    "body": {
                                      "Call": {
                                        "func": {
                                          "Var": {
                                            "value": "String::chars",
                                            "decl": {
                                              "file_id": {
                                                "package": "std",
                                                "filename": "core.brg"
                                              },
                                              "span": {
                                                "start": {
                                                  "line": 105,
                                                  "col": 4
                                                },
                                                "end": {
                                                  "line": 105,
                                                  "col": 37
                                                }
                                              }
                                            },
                                            "ty": {
                                              "Fun": {
                                                "args": [
                                                  {
                                                    "Con": {
                                                      "name": "String",
                                                      "args": []
                                                    }
                                                  }
                                                ],
                                                "bounds": [],
                                                "ret": {
                                                  "Con": {
                                                    "name": "Seq",
                                                    "args": [
                                                      {
                                                        "Con": {
                                                          "name": "Char",
                                                          "args": []
                                                        }
                                                      }
                                                    ]
                                                  }
                                                },
                                                "fx": []
                                              }
                                            },
                                            "span": {
                                              "start": {
                                                "line": 4,
                                                "col": 21
                                              },
                                              "end": {
                                                "line": 4,
                                                "col": 26
                                              }
                                            }
                                          }
                                        },
                                        "args": [
                                          {
                                            "Var": {
                                              "value": "row",
                                              "decl": {
                                                "file_id": {
                                                  "package": "user",
                                                  "filename": "test.brg"
                                                },
                                                "span": {
                                                  "start": {
                                                    "line": 4,
                                                    "col": 12
                                                  },
                                                  "end": {
                                                    "line": 4,
                                                    "col": 15
                                                  }
                                                }
                                              },
                                              "ty": {
                                                "Con": {
                                                  "name": "String",
                                                  "args": []
                                                }
                                              },
                                              "span": {
                                                "start": {
                                                  "line": 4,
                                                  "col": 21
                                                },
                                                "end": {
                                                  "line": 4,
                                                  "col": 26
                                                }
                                              }
                                            }
                                          }
                                        ],
                                        "ty": {
                                          "Con": {
                                            "name": "Seq",
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "Char",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 4,
                                            "col": 21
                                          },
                                          "end": {
                                            "line": 4,
                                            "col": 26
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "kind": "Lambda",
                                  "ty": {
                                    "Fun": {
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "String",
                                            "args": []
                                          }
                                        }
                                      ],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "name": "Seq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Char",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      },
                                      "fx": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 28
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Seq",
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Seq",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Char",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ]
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 7
                              },
                              "end": {
                                "line": 4,
                                "col": 10
                              }
                            }
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Seq",
                            "args": [
                              {
                                "Con": {
                                  "name": "Seq",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "Char",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 4
                          },
                          "end": {
                            "line": 4,
                            "col": 30
                          }
                        }
                      }
                    },
                    {
                      "Loop": {
                        "kind": {
                          "WithCondition": {
                            "binding": {
                              "pat": {
                                "Type": {
                                  "ident": "row",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 6,
                                      "col": 8
                                    },
                                    "end": {
                                      "line": 6,
                                      "col": 11
                                    }
                                  }
                                }
                              },
                              "ann": "Unknown",
                              "ty": {
                                "Con": {
                                  "name": "Seq",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "Char",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            "expr": {
                              "Var": {
                                "value": "rows",
                                "decl": {
                                  "file_id": {
                                    "package": "user",
                                    "filename": "test.brg"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 8
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 12
                                    }
                                  }
                                },
                                "ty": {
                                  "Con": {
                                    "name": "Seq",
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "Seq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Char",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ]
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 15
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 19
                                  }
                                }
                              }
                            }
                          }
                        },
                        "body": {
                          "Block": {
                            "stmts": [
                              {
                                "Call": {
                                  "func": {
                                    "Var": {
                                      "value": "Seq::enumerate",
                                      "decl": {
                                        "file_id": {
                                          "package": "dummy",
                                          "filename": "dummy"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 211,
                                            "col": 4
                                          },
                                          "end": {
                                            "line": 213,
                                            "col": 5
                                          }
                                        }
                                      },
                                      "ty": {
                                        "Fun": {
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Seq",
                                                "args": [
                                                  {
                                                    "Con": {
                                                      "name": "Char",
                                                      "args": []
                                                    }
                                                  }
                                                ]
                                              }
                                            }
                                          ],
                                          "bounds": [],
                                          "ret": {
                                            "Con": {
                                              "name": "Seq",
                                              "args": [
                                                {
                                                  "Con": {
                                                    "name": "Tuple2",
                                                    "args": [
                                                      {
                                                        "Con": {
                                                          "name": "Int",
                                                          "args": []
                                                        }
                                                      },
                                                      {
                                                        "Con": {
                                                          "name": "Char",
                                                          "args": []
                                                        }
                                                      }
                                                    ]
                                                  }
                                                }
                                              ]
                                            }
                                          },
                                          "fx": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 7,
                                          "col": 10
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 19
                                        }
                                      }
                                    }
                                  },
                                  "args": [
                                    {
                                      "Var": {
                                        "value": "row",
                                        "decl": {
                                          "file_id": {
                                            "package": "user",
                                            "filename": "test.brg"
                                          },
                                          "span": {
                                            "start": {
                                              "line": 6,
                                              "col": 8
                                            },
                                            "end": {
                                              "line": 6,
                                              "col": 11
                                            }
                                          }
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "Seq",
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "Char",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 7,
                                            "col": 10
                                          },
                                          "end": {
                                            "line": 7,
                                            "col": 19
                                          }
                                        }
                                      }
                                    }
                                  ],
                                  "ty": {
                                    "Con": {
                                      "name": "Seq",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Tuple2",
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "Int",
                                                  "args": []
                                                }
                                              },
                                              {
                                                "Con": {
                                                  "name": "Char",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 7,
                                      "col": 10
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 19
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Seq",
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Tuple2",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Int",
                                            "args": []
                                          }
                                        },
                                        {
                                          "Con": {
                                            "name": "Char",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ]
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 20
                              },
                              "end": {
                                "line": 8,
                                "col": 5
                              }
                            }
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 4
                          },
                          "end": {
                            "line": 8,
                            "col": 5
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 9,
                      "col": 1
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "Unit",
                    "args": []
                  }
                },
                "fx": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 9,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn borgo_main() {\n    let rows = \"yo\"\n      .split(\"\\n\")\n      .map(|row| row.chars());\n\n    for row in rows {\n      row.enumerate();\n    }\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
