Instances for built-in types are automatically derived

SOURCE:
fn foo() -> Bool {
  Eq::equals(1, 1) as Bool;
  Eq::equals(false, true) as Bool;
  Eq::equals("yo", "bo") as Bool;
  Eq::equals([1], [2,3]) as Bool;
}

OUTPUT:
fn () -> Bool
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "foo",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "CheckType": {
                        "expr": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Eq::equals",
                                "decl": {
                                  "file_id": {
                                    "package": "builtin",
                                    "filename": ""
                                  },
                                  "span": {
                                    "start": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 0,
                                      "col": 0
                                    }
                                  }
                                },
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "Int",
                                          "args": []
                                        }
                                      },
                                      {
                                        "Con": {
                                          "name": "Int",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [
                                      {
                                        "Con": {
                                          "name": "Eq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Int",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "Bool",
                                        "args": []
                                      }
                                    },
                                    "fx": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 2,
                                    "col": 2
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 12
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "Int": 1
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "Int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 14
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "Int": 1
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "Int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 16
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 17
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 2
                              },
                              "end": {
                                "line": 2,
                                "col": 18
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 2,
                            "col": 26
                          }
                        }
                      }
                    },
                    {
                      "CheckType": {
                        "expr": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Eq::equals",
                                "decl": {
                                  "file_id": {
                                    "package": "builtin",
                                    "filename": ""
                                  },
                                  "span": {
                                    "start": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 0,
                                      "col": 0
                                    }
                                  }
                                },
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "Bool",
                                          "args": []
                                        }
                                      },
                                      {
                                        "Con": {
                                          "name": "Bool",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [
                                      {
                                        "Con": {
                                          "name": "Eq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Bool",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "Bool",
                                        "args": []
                                      }
                                    },
                                    "fx": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 3,
                                    "col": 2
                                  },
                                  "end": {
                                    "line": 3,
                                    "col": 12
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "Bool": false
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "Bool",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 3,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 3,
                                      "col": 18
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "Bool": true
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "Bool",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 3,
                                      "col": 20
                                    },
                                    "end": {
                                      "line": 3,
                                      "col": 24
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 2
                              },
                              "end": {
                                "line": 3,
                                "col": 25
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 3,
                            "col": 2
                          },
                          "end": {
                            "line": 3,
                            "col": 33
                          }
                        }
                      }
                    },
                    {
                      "CheckType": {
                        "expr": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Eq::equals",
                                "decl": {
                                  "file_id": {
                                    "package": "builtin",
                                    "filename": ""
                                  },
                                  "span": {
                                    "start": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 0,
                                      "col": 0
                                    }
                                  }
                                },
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "String",
                                          "args": []
                                        }
                                      },
                                      {
                                        "Con": {
                                          "name": "String",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [
                                      {
                                        "Con": {
                                          "name": "Eq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "String",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "Bool",
                                        "args": []
                                      }
                                    },
                                    "fx": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 4,
                                    "col": 2
                                  },
                                  "end": {
                                    "line": 4,
                                    "col": 12
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "String": "yo"
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "String",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 17
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "String": "bo"
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "String",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 19
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 23
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 2
                              },
                              "end": {
                                "line": 4,
                                "col": 24
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 2
                          },
                          "end": {
                            "line": 4,
                            "col": 32
                          }
                        }
                      }
                    },
                    {
                      "CheckType": {
                        "expr": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Eq::equals",
                                "decl": {
                                  "file_id": {
                                    "package": "builtin",
                                    "filename": ""
                                  },
                                  "span": {
                                    "start": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 0,
                                      "col": 0
                                    }
                                  }
                                },
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "List",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Int",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      },
                                      {
                                        "Con": {
                                          "name": "List",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "Int",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ],
                                    "bounds": [
                                      {
                                        "Con": {
                                          "name": "Eq",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "List",
                                                "args": [
                                                  {
                                                    "Con": {
                                                      "name": "Int",
                                                      "args": []
                                                    }
                                                  }
                                                ]
                                              }
                                            }
                                          ]
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "Bool",
                                        "args": []
                                      }
                                    },
                                    "fx": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 5,
                                    "col": 2
                                  },
                                  "end": {
                                    "line": 5,
                                    "col": 12
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "List": [
                                      {
                                        "Literal": {
                                          "lit": {
                                            "Int": 1
                                          },
                                          "ty": {
                                            "Con": {
                                              "name": "Int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 5,
                                              "col": 14
                                            },
                                            "end": {
                                              "line": 5,
                                              "col": 15
                                            }
                                          }
                                        }
                                      }
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "List",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Int",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 5,
                                      "col": 16
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "List": [
                                      {
                                        "Literal": {
                                          "lit": {
                                            "Int": 2
                                          },
                                          "ty": {
                                            "Con": {
                                              "name": "Int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 5,
                                              "col": 19
                                            },
                                            "end": {
                                              "line": 5,
                                              "col": 20
                                            }
                                          }
                                        }
                                      },
                                      {
                                        "Literal": {
                                          "lit": {
                                            "Int": 3
                                          },
                                          "ty": {
                                            "Con": {
                                              "name": "Int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 5,
                                              "col": 21
                                            },
                                            "end": {
                                              "line": 5,
                                              "col": 22
                                            }
                                          }
                                        }
                                      }
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "List",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Int",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 18
                                    },
                                    "end": {
                                      "line": 5,
                                      "col": 23
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 2
                              },
                              "end": {
                                "line": 5,
                                "col": 24
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 2
                          },
                          "end": {
                            "line": 5,
                            "col": 32
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 17
                    },
                    "end": {
                      "line": 6,
                      "col": 1
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "Bool",
                    "args": []
                  }
                },
                "fx": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 6,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn foo() -> Bool {\n  Eq::equals(1, 1) as Bool;\n  Eq::equals(false, true) as Bool;\n  Eq::equals(\"yo\", \"bo\") as Bool;\n  Eq::equals([1], [2,3]) as Bool;\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
