Interfaces as arguments

SOURCE:
use bufio
use os

fn main() -> fn () -> int {
    let reader = bufio.NewReader(os.Stdin)
    reader.ReadString
}

OUTPUT:
fn () -> fn () -> int
---
No errors.
---
[
  {
    "UsePackage": {
      "import": {
        "name": "bufio",
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 10
          },
          "file": 99
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 10
        },
        "file": 99
      }
    }
  },
  {
    "UsePackage": {
      "import": {
        "name": "os",
        "span": {
          "start": {
            "line": 2,
            "col": 1
          },
          "end": {
            "line": 2,
            "col": 7
          },
          "file": 99
        }
      },
      "span": {
        "start": {
          "line": 2,
          "col": 1
        },
        "end": {
          "line": 2,
          "col": 7
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Fun": {
            "args": [],
            "bounds": [],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            }
          }
        },
        "ann": {
          "Fun": {
            "args": [],
            "ret": {
              "Con": {
                "name": "int",
                "args": []
              }
            }
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "reader",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 9
                          },
                          "end": {
                            "line": 5,
                            "col": 15
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "Ref",
                        "args": [
                          {
                            "Con": {
                              "id": "Reader",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "bufio",
                              "decl": {
                                "start": {
                                  "line": 0,
                                  "col": 0
                                },
                                "end": {
                                  "line": 0,
                                  "col": 0
                                },
                                "file": -1
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "bufio",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 18
                                },
                                "end": {
                                  "line": 5,
                                  "col": 23
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "NewReader",
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "Reader",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "Ref",
                                  "args": [
                                    {
                                      "Con": {
                                        "id": "Reader",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 24
                            },
                            "end": {
                              "line": 5,
                              "col": 33
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "FieldAccess": {
                            "expr": {
                              "Var": {
                                "value": "os",
                                "decl": {
                                  "start": {
                                    "line": 0,
                                    "col": 0
                                  },
                                  "end": {
                                    "line": 0,
                                    "col": 0
                                  },
                                  "file": -1
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "os",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 5,
                                    "col": 34
                                  },
                                  "end": {
                                    "line": 5,
                                    "col": 36
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "field": "Stdin",
                            "ty": {
                              "Con": {
                                "id": "Ref",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "File",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 37
                              },
                              "end": {
                                "line": 5,
                                "col": 42
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "Ref",
                          "args": [
                            {
                              "Con": {
                                "id": "Reader",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 33
                        },
                        "end": {
                          "line": 5,
                          "col": 42
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Ref",
                      "args": [
                        {
                          "Con": {
                            "id": "Reader",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 5
                    },
                    "end": {
                      "line": 5,
                      "col": 42
                    },
                    "file": 99
                  }
                }
              },
              {
                "FieldAccess": {
                  "expr": {
                    "Var": {
                      "value": "reader",
                      "decl": {
                        "start": {
                          "line": 5,
                          "col": 9
                        },
                        "end": {
                          "line": 5,
                          "col": 15
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Ref",
                          "args": [
                            {
                              "Con": {
                                "id": "Reader",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 5
                        },
                        "end": {
                          "line": 6,
                          "col": 11
                        },
                        "file": 99
                      }
                    }
                  },
                  "field": "ReadString",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "byte",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "Result",
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "error",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 12
                    },
                    "end": {
                      "line": 6,
                      "col": 22
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Fun": {
                "args": [
                  {
                    "Con": {
                      "id": "byte",
                      "args": []
                    }
                  }
                ],
                "bounds": [],
                "ret": {
                  "Con": {
                    "id": "Result",
                    "args": [
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "id": "error",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              }
            },
            "span": {
              "start": {
                "line": 4,
                "col": 27
              },
              "end": {
                "line": 7,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 4,
          "col": 1
        },
        "end": {
          "line": 7,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
