Loops with no condition

SOURCE:
fn main() {
  loop {
    break
  }
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Loop": {
                  "kind": "NoCondition",
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "Flow": {
                            "kind": "Break",
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 5
                              },
                              "end": {
                                "line": 3,
                                "col": 10
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Var": -333
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 8
                        },
                        "end": {
                          "line": 4,
                          "col": 3
                        },
                        "file": 99
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 3
                    },
                    "end": {
                      "line": 4,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Var": -333
            },
            "span": {
              "start": {
                "line": 1,
                "col": 11
              },
              "end": {
                "line": 5,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 5,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
