Methods are resolved in nested function.

SOURCE:
struct Foo { a: int }

impl Foo {
  fn method(self) -> int {
    self.a + 5
  }
}

fn foo() -> int {
  fn bar() -> int {
    let x = Foo { a: 1 };
    x.method()
  }

  bar()
}

OUTPUT:
fn () -> int
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "StructDef": {
            "def": {
              "name": "Foo",
              "generics": [],
              "fields": [
                {
                  "name": "a",
                  "ann": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "ty": {
                    "generics": [],
                    "ty": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  }
                }
              ]
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 1,
                "col": 21
              }
            }
          }
        },
        {
          "ImplBlock": {
            "ann": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            },
            "ty": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            },
            "items": [
              {
                "Closure": {
                  "fun": {
                    "name": "method",
                    "generics": [],
                    "bounds": [],
                    "args": [
                      {
                        "pat": {
                          "Type": {
                            "ident": "self",
                            "is_mut": false,
                            "ann": {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 0
                              },
                              "end": {
                                "line": 7,
                                "col": 1
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [
                          {
                            "Binary": {
                              "op": "Add",
                              "left": {
                                "FieldAccess": {
                                  "expr": {
                                    "Var": {
                                      "value": "self",
                                      "decl": {
                                        "file_id": {
                                          "package": "user",
                                          "filename": "test.brg"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 3,
                                            "col": 0
                                          },
                                          "end": {
                                            "line": 7,
                                            "col": 1
                                          }
                                        }
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "name": "Foo",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 4
                                        },
                                        "end": {
                                          "line": 5,
                                          "col": 8
                                        }
                                      }
                                    }
                                  },
                                  "field": "a",
                                  "ty": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 4
                                    },
                                    "end": {
                                      "line": 5,
                                      "col": 10
                                    }
                                  }
                                }
                              },
                              "right": {
                                "Literal": {
                                  "lit": {
                                    "Int": 5
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 5,
                                      "col": 14
                                    }
                                  }
                                }
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 4
                                },
                                "end": {
                                  "line": 5,
                                  "col": 14
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 25
                          },
                          "end": {
                            "line": 6,
                            "col": 3
                          }
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "id": -1
                        }
                      }
                    }
                  },
                  "kind": "TopLevel",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "id": -1
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 2
                    },
                    "end": {
                      "line": 6,
                      "col": 3
                    }
                  }
                }
              }
            ],
            "generics": [],
            "span": {
              "start": {
                "line": 3,
                "col": 5
              },
              "end": {
                "line": 3,
                "col": 8
              }
            }
          }
        },
        {
          "Closure": {
            "fun": {
              "name": "foo",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Closure": {
                        "fun": {
                          "name": "bar",
                          "generics": [],
                          "bounds": [],
                          "args": [],
                          "ret": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "ann": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "body": {
                            "Block": {
                              "stmts": [
                                {
                                  "Let": {
                                    "binding": {
                                      "pat": {
                                        "Type": {
                                          "ident": "x",
                                          "is_mut": false,
                                          "ann": "Unknown",
                                          "span": {
                                            "start": {
                                              "line": 11,
                                              "col": 8
                                            },
                                            "end": {
                                              "line": 11,
                                              "col": 9
                                            }
                                          }
                                        }
                                      },
                                      "ann": "Unknown",
                                      "ty": {
                                        "Con": {
                                          "name": "Foo",
                                          "args": []
                                        }
                                      }
                                    },
                                    "value": {
                                      "StructCall": {
                                        "name": "Foo",
                                        "fields": [
                                          {
                                            "name": "a",
                                            "value": {
                                              "Literal": {
                                                "lit": {
                                                  "Int": 1
                                                },
                                                "ty": {
                                                  "Con": {
                                                    "name": "int",
                                                    "args": []
                                                  }
                                                },
                                                "span": {
                                                  "start": {
                                                    "line": 11,
                                                    "col": 21
                                                  },
                                                  "end": {
                                                    "line": 11,
                                                    "col": 22
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        ],
                                        "rest": null,
                                        "ty": {
                                          "Con": {
                                            "name": "Foo",
                                            "args": []
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 11,
                                            "col": 12
                                          },
                                          "end": {
                                            "line": 11,
                                            "col": 24
                                          }
                                        }
                                      }
                                    },
                                    "ty": {
                                      "Con": {
                                        "name": "Foo",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 11,
                                        "col": 4
                                      },
                                      "end": {
                                        "line": 11,
                                        "col": 25
                                      }
                                    }
                                  }
                                },
                                {
                                  "Call": {
                                    "func": {
                                      "FieldAccess": {
                                        "expr": {
                                          "Var": {
                                            "value": "x",
                                            "decl": {
                                              "file_id": {
                                                "package": "user",
                                                "filename": "test.brg"
                                              },
                                              "span": {
                                                "start": {
                                                  "line": 11,
                                                  "col": 8
                                                },
                                                "end": {
                                                  "line": 11,
                                                  "col": 9
                                                }
                                              }
                                            },
                                            "generics_instantiated": [],
                                            "ty": {
                                              "Con": {
                                                "name": "Foo",
                                                "args": []
                                              }
                                            },
                                            "span": {
                                              "start": {
                                                "line": 12,
                                                "col": 4
                                              },
                                              "end": {
                                                "line": 12,
                                                "col": 5
                                              }
                                            }
                                          }
                                        },
                                        "field": "method",
                                        "ty": {
                                          "Fun": {
                                            "args": [],
                                            "bounds": [],
                                            "ret": {
                                              "Con": {
                                                "name": "int",
                                                "args": []
                                              }
                                            },
                                            "id": -1
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 12,
                                            "col": 6
                                          },
                                          "end": {
                                            "line": 12,
                                            "col": 12
                                          }
                                        }
                                      }
                                    },
                                    "args": [],
                                    "ty": {
                                      "Con": {
                                        "name": "int",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 12,
                                        "col": 6
                                      },
                                      "end": {
                                        "line": 12,
                                        "col": 12
                                      }
                                    }
                                  }
                                }
                              ],
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 10,
                                  "col": 18
                                },
                                "end": {
                                  "line": 13,
                                  "col": 3
                                }
                              }
                            }
                          },
                          "bounded_ty": {
                            "generics": [],
                            "ty": {
                              "Fun": {
                                "args": [],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            }
                          }
                        },
                        "kind": "Inline",
                        "ty": {
                          "Fun": {
                            "args": [],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "id": -1
                          }
                        },
                        "span": {
                          "start": {
                            "line": 10,
                            "col": 2
                          },
                          "end": {
                            "line": 13,
                            "col": 3
                          }
                        }
                      }
                    },
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "bar",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 10,
                                  "col": 2
                                },
                                "end": {
                                  "line": 13,
                                  "col": 3
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Fun": {
                                "args": [],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 2
                              },
                              "end": {
                                "line": 15,
                                "col": 5
                              }
                            }
                          }
                        },
                        "args": [],
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 15,
                            "col": 2
                          },
                          "end": {
                            "line": 15,
                            "col": 7
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 9,
                      "col": 16
                    },
                    "end": {
                      "line": 16,
                      "col": 1
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 9,
                "col": 0
              },
              "end": {
                "line": 16,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "struct Foo { a: int }\n\nimpl Foo {\n  fn method(self) -> int {\n    self.a + 5\n  }\n}\n\nfn foo() -> int {\n  fn bar() -> int {\n    let x = Foo { a: 1 };\n    x.method()\n  }\n\n  bar()\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
