Method calls work for enums.

SOURCE:
enum Foo {
  Bar(int)
}

impl (f: Foo) {
    fn method(s: string, b: int) -> int {
        match f {
          Bar(a) => a + b,
        }
    }
}

fn main() -> int {
    let f = Foo.Bar(1)
    @ensure f.method("a", 2), int

    let m = f.method
    m("a", 2)
}

OUTPUT:
fn () -> int
---
No errors.
---
[
  {
    "EnumDef": {
      "def": {
        "name": "Foo",
        "generics": [],
        "cons": [
          {
            "name": "Bar",
            "fields": [
              {
                "name": "field0",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              }
            ]
          }
        ]
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 3,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "ImplBlock": {
      "ann": {
        "Con": {
          "name": "Foo",
          "args": []
        }
      },
      "self_name": "f",
      "ty": {
        "Con": {
          "id": "Foo",
          "args": []
        }
      },
      "items": [
        {
          "Closure": {
            "fun": {
              "name": "method",
              "generics": [],
              "args": [
                {
                  "pat": {
                    "Type": {
                      "ident": "s",
                      "is_mut": false,
                      "ann": "Unknown",
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 15
                        },
                        "end": {
                          "line": 6,
                          "col": 16
                        },
                        "file": 99
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                },
                {
                  "pat": {
                    "Type": {
                      "ident": "b",
                      "is_mut": false,
                      "ann": "Unknown",
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 26
                        },
                        "end": {
                          "line": 6,
                          "col": 27
                        },
                        "file": 99
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              ],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Match": {
                        "subject": {
                          "Var": {
                            "value": "f",
                            "decl": {
                              "start": {
                                "line": 5,
                                "col": 1
                              },
                              "end": {
                                "line": 11,
                                "col": 1
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "id": "Foo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 7,
                                "col": 15
                              },
                              "end": {
                                "line": 7,
                                "col": 16
                              },
                              "file": 99
                            }
                          }
                        },
                        "arms": [
                          {
                            "pat": {
                              "Pat": {
                                "ident": "Foo.Bar",
                                "elems": [
                                  {
                                    "Type": {
                                      "ident": "a",
                                      "is_mut": false,
                                      "ann": "Unknown",
                                      "span": {
                                        "start": {
                                          "line": 8,
                                          "col": 15
                                        },
                                        "end": {
                                          "line": 8,
                                          "col": 16
                                        },
                                        "file": 99
                                      }
                                    }
                                  }
                                ],
                                "ty": {
                                  "Con": {
                                    "id": "Foo",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 8,
                                    "col": 11
                                  },
                                  "end": {
                                    "line": 8,
                                    "col": 14
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "expr": {
                              "Binary": {
                                "op": "Add",
                                "left": {
                                  "Var": {
                                    "value": "a",
                                    "decl": {
                                      "start": {
                                        "line": 8,
                                        "col": 15
                                      },
                                      "end": {
                                        "line": 8,
                                        "col": 16
                                      },
                                      "file": 99
                                    },
                                    "generics_instantiated": [],
                                    "ty": {
                                      "Con": {
                                        "id": "int",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 8,
                                        "col": 21
                                      },
                                      "end": {
                                        "line": 8,
                                        "col": 22
                                      },
                                      "file": 99
                                    }
                                  }
                                },
                                "right": {
                                  "Var": {
                                    "value": "b",
                                    "decl": {
                                      "start": {
                                        "line": 6,
                                        "col": 26
                                      },
                                      "end": {
                                        "line": 6,
                                        "col": 27
                                      },
                                      "file": 99
                                    },
                                    "generics_instantiated": [],
                                    "ty": {
                                      "Con": {
                                        "id": "int",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 8,
                                        "col": 25
                                      },
                                      "end": {
                                        "line": 8,
                                        "col": 26
                                      },
                                      "file": 99
                                    }
                                  }
                                },
                                "ty": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 8,
                                    "col": 21
                                  },
                                  "end": {
                                    "line": 8,
                                    "col": 26
                                  },
                                  "file": 99
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 7,
                            "col": 9
                          },
                          "end": {
                            "line": 9,
                            "col": 9
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 41
                    },
                    "end": {
                      "line": 10,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                ],
                "bounds": [],
                "ret": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              }
            },
            "span": {
              "start": {
                "line": 6,
                "col": 5
              },
              "end": {
                "line": 10,
                "col": 5
              },
              "file": 99
            }
          }
        }
      ],
      "generics": [],
      "span": {
        "start": {
          "line": 5,
          "col": 1
        },
        "end": {
          "line": 11,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "f",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 14,
                            "col": 9
                          },
                          "end": {
                            "line": 14,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "Foo",
                        "args": []
                      }
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "Foo.Bar",
                          "decl": {
                            "start": {
                              "line": 1,
                              "col": 1
                            },
                            "end": {
                              "line": 3,
                              "col": 1
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "Foo",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 14,
                              "col": 17
                            },
                            "end": {
                              "line": 14,
                              "col": 20
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 14,
                                "col": 21
                              },
                              "end": {
                                "line": 14,
                                "col": 22
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 14,
                          "col": 20
                        },
                        "end": {
                          "line": 14,
                          "col": 22
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 14,
                      "col": 5
                    },
                    "end": {
                      "line": 14,
                      "col": 22
                    },
                    "file": 99
                  }
                }
              },
              {
                "CheckType": {
                  "expr": {
                    "Call": {
                      "func": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "f",
                              "decl": {
                                "start": {
                                  "line": 14,
                                  "col": 9
                                },
                                "end": {
                                  "line": 14,
                                  "col": 10
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "Foo",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 15,
                                  "col": 13
                                },
                                "end": {
                                  "line": 15,
                                  "col": 14
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "method",
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 15,
                              "col": 15
                            },
                            "end": {
                              "line": 15,
                              "col": 21
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "String": {
                                "Single": "a"
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 22
                              },
                              "end": {
                                "line": 15,
                                "col": 25
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 2
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 27
                              },
                              "end": {
                                "line": 15,
                                "col": 28
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 15,
                          "col": 21
                        },
                        "end": {
                          "line": 15,
                          "col": 28
                        },
                        "file": 99
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 15,
                      "col": 5
                    },
                    "end": {
                      "line": 15,
                      "col": 34
                    },
                    "file": 99
                  }
                }
              },
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "m",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 17,
                            "col": 9
                          },
                          "end": {
                            "line": 17,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Var": 99
                    }
                  },
                  "value": {
                    "FieldAccess": {
                      "expr": {
                        "Var": {
                          "value": "f",
                          "decl": {
                            "start": {
                              "line": 14,
                              "col": 9
                            },
                            "end": {
                              "line": 14,
                              "col": 10
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Con": {
                              "id": "Foo",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 17,
                              "col": 13
                            },
                            "end": {
                              "line": 17,
                              "col": 14
                            },
                            "file": 99
                          }
                        }
                      },
                      "field": "method",
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 17,
                          "col": 15
                        },
                        "end": {
                          "line": 17,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 17,
                      "col": 5
                    },
                    "end": {
                      "line": 17,
                      "col": 21
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "m",
                      "decl": {
                        "start": {
                          "line": 17,
                          "col": 9
                        },
                        "end": {
                          "line": 17,
                          "col": 10
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Var": 99
                      },
                      "span": {
                        "start": {
                          "line": 18,
                          "col": 5
                        },
                        "end": {
                          "line": 18,
                          "col": 6
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "a"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 18,
                            "col": 7
                          },
                          "end": {
                            "line": 18,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "Int": 2
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 18,
                            "col": 12
                          },
                          "end": {
                            "line": 18,
                            "col": 13
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 18,
                      "col": 6
                    },
                    "end": {
                      "line": 18,
                      "col": 13
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 13,
                "col": 18
              },
              "end": {
                "line": 19,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 13,
          "col": 1
        },
        "end": {
          "line": 19,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
