Methods are resolved in nested function.

SOURCE:
struct Foo { a: int }

impl (f: Foo) {
    fn method() -> int {
        f.a + 5
    }
}

fn foo() -> int {
    fn bar() -> int {
        let x = Foo { a: 1 }
        x.method()
    }

    bar()
}

OUTPUT:
fn () -> int
---
No errors.
---
[
  {
    "StructDef": {
      "def": {
        "name": "Foo",
        "generics": [],
        "fields": [
          {
            "name": "a",
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ty": {
              "generics": [],
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        ]
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 21
        },
        "file": 99
      }
    }
  },
  {
    "ImplBlock": {
      "ann": {
        "Con": {
          "name": "Foo",
          "args": []
        }
      },
      "self_name": "f",
      "ty": {
        "Con": {
          "id": "Foo",
          "args": []
        }
      },
      "items": [
        {
          "Closure": {
            "fun": {
              "name": "method",
              "generics": [],
              "args": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Binary": {
                        "op": "Add",
                        "left": {
                          "FieldAccess": {
                            "expr": {
                              "Var": {
                                "value": "f",
                                "decl": {
                                  "start": {
                                    "line": 3,
                                    "col": 1
                                  },
                                  "end": {
                                    "line": 7,
                                    "col": 1
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "Foo",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 5,
                                    "col": 9
                                  },
                                  "end": {
                                    "line": 5,
                                    "col": 10
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "field": "a",
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 11
                              },
                              "end": {
                                "line": 5,
                                "col": 12
                              },
                              "file": 99
                            }
                          }
                        },
                        "right": {
                          "Literal": {
                            "lit": {
                              "Int": 5
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 15
                              },
                              "end": {
                                "line": 5,
                                "col": 16
                              },
                              "file": 99
                            }
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 9
                          },
                          "end": {
                            "line": 5,
                            "col": 16
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 24
                    },
                    "end": {
                      "line": 6,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              }
            },
            "span": {
              "start": {
                "line": 4,
                "col": 5
              },
              "end": {
                "line": 6,
                "col": 5
              },
              "file": 99
            }
          }
        }
      ],
      "generics": [],
      "span": {
        "start": {
          "line": 3,
          "col": 1
        },
        "end": {
          "line": 7,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "foo",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Closure": {
                  "fun": {
                    "name": "bar",
                    "generics": [],
                    "args": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [
                          {
                            "Let": {
                              "binding": {
                                "pat": {
                                  "Type": {
                                    "ident": "x",
                                    "is_mut": false,
                                    "ann": "Unknown",
                                    "span": {
                                      "start": {
                                        "line": 11,
                                        "col": 13
                                      },
                                      "end": {
                                        "line": 11,
                                        "col": 14
                                      },
                                      "file": 99
                                    }
                                  }
                                },
                                "ann": "Unknown",
                                "ty": {
                                  "Con": {
                                    "id": "Foo",
                                    "args": []
                                  }
                                }
                              },
                              "value": {
                                "StructCall": {
                                  "name": "Foo",
                                  "fields": [
                                    {
                                      "name": "a",
                                      "value": {
                                        "Literal": {
                                          "lit": {
                                            "Int": 1
                                          },
                                          "ty": {
                                            "Con": {
                                              "id": "int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 11,
                                              "col": 26
                                            },
                                            "end": {
                                              "line": 11,
                                              "col": 27
                                            },
                                            "file": 99
                                          }
                                        }
                                      }
                                    }
                                  ],
                                  "rest": null,
                                  "ty": {
                                    "Con": {
                                      "id": "Foo",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 11,
                                      "col": 21
                                    },
                                    "end": {
                                      "line": 11,
                                      "col": 28
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "mutable": false,
                              "ty": {
                                "Con": {
                                  "id": "Foo",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 11,
                                  "col": 9
                                },
                                "end": {
                                  "line": 11,
                                  "col": 28
                                },
                                "file": 99
                              }
                            }
                          },
                          {
                            "Call": {
                              "func": {
                                "FieldAccess": {
                                  "expr": {
                                    "Var": {
                                      "value": "x",
                                      "decl": {
                                        "start": {
                                          "line": 11,
                                          "col": 13
                                        },
                                        "end": {
                                          "line": 11,
                                          "col": 14
                                        },
                                        "file": 99
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "id": "Foo",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 12,
                                          "col": 9
                                        },
                                        "end": {
                                          "line": 12,
                                          "col": 10
                                        },
                                        "file": 99
                                      }
                                    }
                                  },
                                  "field": "method",
                                  "ty": {
                                    "Fun": {
                                      "args": [],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "id": "int",
                                          "args": []
                                        }
                                      }
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 12,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 12,
                                      "col": 17
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "args": [],
                              "ty": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 12,
                                  "col": 17
                                },
                                "end": {
                                  "line": 12,
                                  "col": 18
                                },
                                "file": 99
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 10,
                            "col": 21
                          },
                          "end": {
                            "line": 13,
                            "col": 5
                          },
                          "file": 99
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      }
                    }
                  },
                  "kind": "Inline",
                  "ty": {
                    "Fun": {
                      "args": [],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 10,
                      "col": 5
                    },
                    "end": {
                      "line": 13,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "bar",
                      "decl": {
                        "start": {
                          "line": 10,
                          "col": 5
                        },
                        "end": {
                          "line": 13,
                          "col": 5
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 15,
                          "col": 5
                        },
                        "end": {
                          "line": 15,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 15,
                      "col": 8
                    },
                    "end": {
                      "line": 15,
                      "col": 9
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 9,
                "col": 17
              },
              "end": {
                "line": 16,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 9,
          "col": 1
        },
        "end": {
          "line": 16,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
