Method calls work for enums.

SOURCE:
enum Foo {
  Bar(int)
}

impl Foo {
  fn method(self, s: string, b: int) -> int {
    match self {
      Bar(a) => a + b,
    }
  }
}

fn borgo_main() -> int {
  let f = Foo::Bar(1);
  f.method("a", 2) as int;

  let m = f.method;
  m("a", 2)
}

OUTPUT:
fn () -> int
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "EnumDef": {
            "def": {
              "name": "Foo",
              "generics": [],
              "cons": [
                {
                  "name": "Bar",
                  "fields": [
                    {
                      "name": "field0",
                      "ann": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    }
                  ]
                }
              ]
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 3,
                "col": 1
              }
            }
          }
        },
        {
          "ImplBlock": {
            "ann": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            },
            "ty": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            },
            "items": [
              {
                "Closure": {
                  "fun": {
                    "name": "method",
                    "generics": [],
                    "bounds": [],
                    "args": [
                      {
                        "pat": {
                          "Type": {
                            "ident": "self",
                            "is_mut": false,
                            "ann": {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 0
                              },
                              "end": {
                                "line": 11,
                                "col": 1
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        }
                      },
                      {
                        "pat": {
                          "Type": {
                            "ident": "s",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 18
                              },
                              "end": {
                                "line": 6,
                                "col": 19
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        }
                      },
                      {
                        "pat": {
                          "Type": {
                            "ident": "b",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 29
                              },
                              "end": {
                                "line": 6,
                                "col": 30
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [
                          {
                            "Match": {
                              "subject": {
                                "Var": {
                                  "value": "self",
                                  "decl": {
                                    "file_id": {
                                      "package": "user",
                                      "filename": "test.brg"
                                    },
                                    "span": {
                                      "start": {
                                        "line": 5,
                                        "col": 0
                                      },
                                      "end": {
                                        "line": 11,
                                        "col": 1
                                      }
                                    }
                                  },
                                  "generics_instantiated": [],
                                  "ty": {
                                    "Con": {
                                      "name": "Foo",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 7,
                                      "col": 10
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 14
                                    }
                                  }
                                }
                              },
                              "arms": [
                                {
                                  "pat": {
                                    "Pat": {
                                      "ident": "Foo::Bar",
                                      "elems": [
                                        {
                                          "Type": {
                                            "ident": "a",
                                            "is_mut": false,
                                            "ann": "Unknown",
                                            "span": {
                                              "start": {
                                                "line": 8,
                                                "col": 10
                                              },
                                              "end": {
                                                "line": 8,
                                                "col": 11
                                              }
                                            }
                                          }
                                        }
                                      ],
                                      "ty": {
                                        "Con": {
                                          "name": "Foo",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 8,
                                          "col": 6
                                        },
                                        "end": {
                                          "line": 8,
                                          "col": 12
                                        }
                                      }
                                    }
                                  },
                                  "expr": {
                                    "Binary": {
                                      "op": "Add",
                                      "left": {
                                        "Var": {
                                          "value": "a",
                                          "decl": {
                                            "file_id": {
                                              "package": "user",
                                              "filename": "test.brg"
                                            },
                                            "span": {
                                              "start": {
                                                "line": 8,
                                                "col": 10
                                              },
                                              "end": {
                                                "line": 8,
                                                "col": 11
                                              }
                                            }
                                          },
                                          "generics_instantiated": [],
                                          "ty": {
                                            "Con": {
                                              "name": "int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 8,
                                              "col": 16
                                            },
                                            "end": {
                                              "line": 8,
                                              "col": 17
                                            }
                                          }
                                        }
                                      },
                                      "right": {
                                        "Var": {
                                          "value": "b",
                                          "decl": {
                                            "file_id": {
                                              "package": "user",
                                              "filename": "test.brg"
                                            },
                                            "span": {
                                              "start": {
                                                "line": 6,
                                                "col": 29
                                              },
                                              "end": {
                                                "line": 6,
                                                "col": 30
                                              }
                                            }
                                          },
                                          "generics_instantiated": [],
                                          "ty": {
                                            "Con": {
                                              "name": "int",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 8,
                                              "col": 20
                                            },
                                            "end": {
                                              "line": 8,
                                              "col": 21
                                            }
                                          }
                                        }
                                      },
                                      "ty": {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 8,
                                          "col": 16
                                        },
                                        "end": {
                                          "line": 8,
                                          "col": 21
                                        }
                                      }
                                    }
                                  }
                                }
                              ],
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 7,
                                  "col": 4
                                },
                                "end": {
                                  "line": 9,
                                  "col": 5
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 44
                          },
                          "end": {
                            "line": 10,
                            "col": 3
                          }
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "id": -1
                        }
                      }
                    }
                  },
                  "kind": "TopLevel",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "id": -1
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 2
                    },
                    "end": {
                      "line": 10,
                      "col": 3
                    }
                  }
                }
              }
            ],
            "generics": [],
            "span": {
              "start": {
                "line": 5,
                "col": 5
              },
              "end": {
                "line": 5,
                "col": 8
              }
            }
          }
        },
        {
          "Closure": {
            "fun": {
              "name": "borgo_main",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Let": {
                        "binding": {
                          "pat": {
                            "Type": {
                              "ident": "f",
                              "is_mut": false,
                              "ann": "Unknown",
                              "span": {
                                "start": {
                                  "line": 14,
                                  "col": 6
                                },
                                "end": {
                                  "line": 14,
                                  "col": 7
                                }
                              }
                            }
                          },
                          "ann": "Unknown",
                          "ty": {
                            "Con": {
                              "name": "Foo",
                              "args": []
                            }
                          }
                        },
                        "value": {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Foo::Bar",
                                "decl": {
                                  "file_id": {
                                    "package": "user",
                                    "filename": "test.brg"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 1,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 3,
                                      "col": 1
                                    }
                                  }
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [],
                                    "ret": {
                                      "Con": {
                                        "name": "Foo",
                                        "args": []
                                      }
                                    },
                                    "id": -1
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 14,
                                    "col": 10
                                  },
                                  "end": {
                                    "line": 14,
                                    "col": 18
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "Int": 1
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 14,
                                      "col": 19
                                    },
                                    "end": {
                                      "line": 14,
                                      "col": 20
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 14,
                                "col": 10
                              },
                              "end": {
                                "line": 14,
                                "col": 21
                              }
                            }
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 14,
                            "col": 2
                          },
                          "end": {
                            "line": 14,
                            "col": 22
                          }
                        }
                      }
                    },
                    {
                      "CheckType": {
                        "expr": {
                          "Call": {
                            "func": {
                              "FieldAccess": {
                                "expr": {
                                  "Var": {
                                    "value": "f",
                                    "decl": {
                                      "file_id": {
                                        "package": "user",
                                        "filename": "test.brg"
                                      },
                                      "span": {
                                        "start": {
                                          "line": 14,
                                          "col": 6
                                        },
                                        "end": {
                                          "line": 14,
                                          "col": 7
                                        }
                                      }
                                    },
                                    "generics_instantiated": [],
                                    "ty": {
                                      "Con": {
                                        "name": "Foo",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 15,
                                        "col": 2
                                      },
                                      "end": {
                                        "line": 15,
                                        "col": 3
                                      }
                                    }
                                  }
                                },
                                "field": "method",
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      },
                                      {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [],
                                    "ret": {
                                      "Con": {
                                        "name": "int",
                                        "args": []
                                      }
                                    },
                                    "id": -1
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 15,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 15,
                                    "col": 10
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "String": [
                                      "a",
                                      null
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 15,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 15,
                                      "col": 14
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "Int": 2
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 15,
                                      "col": 16
                                    },
                                    "end": {
                                      "line": 15,
                                      "col": 17
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 4
                              },
                              "end": {
                                "line": 15,
                                "col": 10
                              }
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 15,
                            "col": 2
                          },
                          "end": {
                            "line": 15,
                            "col": 25
                          }
                        }
                      }
                    },
                    {
                      "Let": {
                        "binding": {
                          "pat": {
                            "Type": {
                              "ident": "m",
                              "is_mut": false,
                              "ann": "Unknown",
                              "span": {
                                "start": {
                                  "line": 17,
                                  "col": 6
                                },
                                "end": {
                                  "line": 17,
                                  "col": 7
                                }
                              }
                            }
                          },
                          "ann": "Unknown",
                          "ty": {
                            "Var": 99
                          }
                        },
                        "value": {
                          "FieldAccess": {
                            "expr": {
                              "Var": {
                                "value": "f",
                                "decl": {
                                  "file_id": {
                                    "package": "user",
                                    "filename": "test.brg"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 14,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 14,
                                      "col": 7
                                    }
                                  }
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "name": "Foo",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 17,
                                    "col": 10
                                  },
                                  "end": {
                                    "line": 17,
                                    "col": 11
                                  }
                                }
                              }
                            },
                            "field": "method",
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            },
                            "span": {
                              "start": {
                                "line": 17,
                                "col": 10
                              },
                              "end": {
                                "line": 17,
                                "col": 18
                              }
                            }
                          }
                        },
                        "ty": {
                          "Con": {
                            "name": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 17,
                            "col": 2
                          },
                          "end": {
                            "line": 17,
                            "col": 19
                          }
                        }
                      }
                    },
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "m",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 17,
                                  "col": 6
                                },
                                "end": {
                                  "line": 17,
                                  "col": 7
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Var": 99
                            },
                            "span": {
                              "start": {
                                "line": 18,
                                "col": 2
                              },
                              "end": {
                                "line": 18,
                                "col": 3
                              }
                            }
                          }
                        },
                        "args": [
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "a",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 18,
                                  "col": 4
                                },
                                "end": {
                                  "line": 18,
                                  "col": 7
                                }
                              }
                            }
                          },
                          {
                            "Literal": {
                              "lit": {
                                "Int": 2
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 18,
                                  "col": 9
                                },
                                "end": {
                                  "line": 18,
                                  "col": 10
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 18,
                            "col": 2
                          },
                          "end": {
                            "line": 18,
                            "col": 11
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 13,
                      "col": 23
                    },
                    "end": {
                      "line": 19,
                      "col": 1
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 13,
                "col": 0
              },
              "end": {
                "line": 19,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "enum Foo {\n  Bar(int)\n}\n\nimpl Foo {\n  fn method(self, s: string, b: int) -> int {\n    match self {\n      Bar(a) => a + b,\n    }\n  }\n}\n\nfn borgo_main() -> int {\n  let f = Foo::Bar(1);\n  f.method(\"a\", 2) as int;\n\n  let m = f.method;\n  m(\"a\", 2)\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
