Parse traits

SOURCE:
fn borgo_main() {
  trait Foo {
    fn bar(x: string) -> int;
  }

  fn check(f: Foo) -> int {
    f.bar("yo")
  }

  ()
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "borgo_main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Trait": {
                  "name": "Foo",
                  "supertraits": [],
                  "items": [
                    {
                      "Closure": {
                        "fun": {
                          "name": "bar",
                          "generics": [],
                          "args": [
                            {
                              "pat": {
                                "Type": {
                                  "ident": "x",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 3,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 3,
                                      "col": 12
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "ann": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "ty": {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            }
                          ],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "ann": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "body": "Noop",
                          "bounded_ty": {
                            "generics": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              }
                            }
                          }
                        },
                        "kind": "Inline",
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            }
                          }
                        },
                        "span": {
                          "start": {
                            "line": 3,
                            "col": 4
                          },
                          "end": {
                            "line": 3,
                            "col": 29
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "types": [],
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 2
                    },
                    "end": {
                      "line": 4,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              },
              {
                "Closure": {
                  "fun": {
                    "name": "check",
                    "generics": [],
                    "args": [
                      {
                        "pat": {
                          "Type": {
                            "ident": "f",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 11
                              },
                              "end": {
                                "line": 6,
                                "col": 12
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "Foo",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "Foo",
                            "args": []
                          }
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [
                          {
                            "Call": {
                              "func": {
                                "FieldAccess": {
                                  "expr": {
                                    "Var": {
                                      "value": "f",
                                      "decl": {
                                        "start": {
                                          "line": 6,
                                          "col": 11
                                        },
                                        "end": {
                                          "line": 6,
                                          "col": 12
                                        },
                                        "file": 99
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "id": "Foo",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 7,
                                          "col": 4
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 5
                                        },
                                        "file": 99
                                      }
                                    }
                                  },
                                  "field": "bar",
                                  "ty": {
                                    "Fun": {
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "string",
                                            "args": []
                                          }
                                        }
                                      ],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "id": "int",
                                          "args": []
                                        }
                                      }
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 7,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 9
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "args": [
                                {
                                  "Literal": {
                                    "lit": {
                                      "String": [
                                        "yo",
                                        null
                                      ]
                                    },
                                    "ty": {
                                      "Con": {
                                        "id": "string",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 7,
                                        "col": 10
                                      },
                                      "end": {
                                        "line": 7,
                                        "col": 14
                                      },
                                      "file": 99
                                    }
                                  }
                                }
                              ],
                              "ty": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 7,
                                  "col": 6
                                },
                                "end": {
                                  "line": 7,
                                  "col": 9
                                },
                                "file": 99
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 26
                          },
                          "end": {
                            "line": 8,
                            "col": 3
                          },
                          "file": 99
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "Foo",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        }
                      }
                    }
                  },
                  "kind": "Inline",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "Foo",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 2
                    },
                    "end": {
                      "line": 8,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              },
              {
                "Unit": {
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 10,
                      "col": 2
                    },
                    "end": {
                      "line": 10,
                      "col": 4
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Unit",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 16
              },
              "end": {
                "line": 11,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 0
        },
        "end": {
          "line": 11,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
