Parse traits

SOURCE:
fn borgo_main() {
  trait Foo {
    fn bar(x: string) -> int;
  }

  fn check(f: Foo) -> int {
    f.bar("yo")
  }

  ()
}

OUTPUT:
fn () -> ()
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "borgo_main",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Trait": {
                        "name": "Foo",
                        "supertraits": [],
                        "items": [
                          {
                            "Closure": {
                              "fun": {
                                "name": "bar",
                                "generics": [],
                                "bounds": [],
                                "args": [
                                  {
                                    "pat": {
                                      "Type": {
                                        "ident": "x",
                                        "is_mut": false,
                                        "ann": "Unknown",
                                        "span": {
                                          "start": {
                                            "line": 3,
                                            "col": 11
                                          },
                                          "end": {
                                            "line": 3,
                                            "col": 12
                                          }
                                        }
                                      }
                                    },
                                    "ann": {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    },
                                    "ty": {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  }
                                ],
                                "ret": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "ann": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "body": "Noop",
                                "bounded_ty": {
                                  "generics": [],
                                  "ty": {
                                    "Fun": {
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      },
                                      "id": -1
                                    }
                                  }
                                }
                              },
                              "kind": "Inline",
                              "ty": {
                                "Fun": {
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  ],
                                  "bounds": [],
                                  "ret": {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  "id": -1
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 4
                                },
                                "end": {
                                  "line": 3,
                                  "col": 29
                                }
                              }
                            }
                          }
                        ],
                        "types": [],
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 4,
                            "col": 3
                          }
                        }
                      }
                    },
                    {
                      "Closure": {
                        "fun": {
                          "name": "check",
                          "generics": [],
                          "bounds": [],
                          "args": [
                            {
                              "pat": {
                                "Type": {
                                  "ident": "f",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 6,
                                      "col": 11
                                    },
                                    "end": {
                                      "line": 6,
                                      "col": 12
                                    }
                                  }
                                }
                              },
                              "ann": {
                                "Con": {
                                  "name": "Foo",
                                  "args": []
                                }
                              },
                              "ty": {
                                "Con": {
                                  "name": "Foo",
                                  "args": []
                                }
                              }
                            }
                          ],
                          "ret": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "ann": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "body": {
                            "Block": {
                              "stmts": [
                                {
                                  "Call": {
                                    "func": {
                                      "FieldAccess": {
                                        "expr": {
                                          "Var": {
                                            "value": "f",
                                            "decl": {
                                              "file_id": {
                                                "package": "user",
                                                "filename": "test.brg"
                                              },
                                              "span": {
                                                "start": {
                                                  "line": 6,
                                                  "col": 11
                                                },
                                                "end": {
                                                  "line": 6,
                                                  "col": 12
                                                }
                                              }
                                            },
                                            "generics_instantiated": [],
                                            "ty": {
                                              "Con": {
                                                "name": "Foo",
                                                "args": []
                                              }
                                            },
                                            "span": {
                                              "start": {
                                                "line": 7,
                                                "col": 4
                                              },
                                              "end": {
                                                "line": 7,
                                                "col": 5
                                              }
                                            }
                                          }
                                        },
                                        "field": "bar",
                                        "ty": {
                                          "Fun": {
                                            "args": [
                                              {
                                                "Con": {
                                                  "name": "string",
                                                  "args": []
                                                }
                                              }
                                            ],
                                            "bounds": [],
                                            "ret": {
                                              "Con": {
                                                "name": "int",
                                                "args": []
                                              }
                                            },
                                            "id": -1
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 7,
                                            "col": 6
                                          },
                                          "end": {
                                            "line": 7,
                                            "col": 9
                                          }
                                        }
                                      }
                                    },
                                    "args": [
                                      {
                                        "Literal": {
                                          "lit": {
                                            "String": [
                                              "yo",
                                              null
                                            ]
                                          },
                                          "ty": {
                                            "Con": {
                                              "name": "string",
                                              "args": []
                                            }
                                          },
                                          "span": {
                                            "start": {
                                              "line": 7,
                                              "col": 10
                                            },
                                            "end": {
                                              "line": 7,
                                              "col": 14
                                            }
                                          }
                                        }
                                      }
                                    ],
                                    "ty": {
                                      "Con": {
                                        "name": "int",
                                        "args": []
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 7,
                                        "col": 6
                                      },
                                      "end": {
                                        "line": 7,
                                        "col": 9
                                      }
                                    }
                                  }
                                }
                              ],
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 26
                                },
                                "end": {
                                  "line": 8,
                                  "col": 3
                                }
                              }
                            }
                          },
                          "bounded_ty": {
                            "generics": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Foo",
                                      "args": []
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            }
                          }
                        },
                        "kind": "Inline",
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "name": "Foo",
                                  "args": []
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "id": -1
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 2
                          },
                          "end": {
                            "line": 8,
                            "col": 3
                          }
                        }
                      }
                    },
                    {
                      "Unit": {
                        "span": {
                          "start": {
                            "line": 10,
                            "col": 2
                          },
                          "end": {
                            "line": 10,
                            "col": 4
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 11,
                      "col": 1
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "Unit",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 11,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn borgo_main() {\n  trait Foo {\n    fn bar(x: string) -> int;\n  }\n\n  fn check(f: Foo) -> int {\n    f.bar(\"yo\")\n  }\n\n  ()\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
