References are maintained after try call

SOURCE:
use os

fn foo() -> Result<()> {
    let f = os.Open("file")?
    Ok(bar(f))
}

fn bar(f: *os.File) {}

fn main() {
    foo()
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "UsePackage": {
      "import": {
        "name": "os",
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 7
          },
          "file": 99
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 7
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "foo",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Result",
            "args": [
              {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              },
              {
                "Con": {
                  "id": "error",
                  "args": []
                }
              }
            ]
          }
        },
        "ann": {
          "Con": {
            "name": "Result",
            "args": [
              {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              }
            ]
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "f",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 9
                          },
                          "end": {
                            "line": 4,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "Ref",
                        "args": [
                          {
                            "Con": {
                              "id": "File",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  },
                  "value": {
                    "Try": {
                      "expr": {
                        "Call": {
                          "func": {
                            "FieldAccess": {
                              "expr": {
                                "Var": {
                                  "value": "os",
                                  "decl": {
                                    "start": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "end": {
                                      "line": 0,
                                      "col": 0
                                    },
                                    "file": -1
                                  },
                                  "generics_instantiated": [],
                                  "ty": {
                                    "Con": {
                                      "id": "os",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 13
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 15
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              "field": "Open",
                              "ty": {
                                "Fun": {
                                  "args": [
                                    {
                                      "Con": {
                                        "id": "string",
                                        "args": []
                                      }
                                    }
                                  ],
                                  "bounds": [],
                                  "ret": {
                                    "Con": {
                                      "id": "Result",
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "Ref",
                                            "args": [
                                              {
                                                "Con": {
                                                  "id": "File",
                                                  "args": []
                                                }
                                              }
                                            ]
                                          }
                                        },
                                        {
                                          "Con": {
                                            "id": "error",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 4,
                                  "col": 16
                                },
                                "end": {
                                  "line": 4,
                                  "col": 20
                                },
                                "file": 99
                              }
                            }
                          },
                          "args": [
                            {
                              "Literal": {
                                "lit": {
                                  "String": {
                                    "Single": "file"
                                  }
                                },
                                "ty": {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 4,
                                    "col": 21
                                  },
                                  "end": {
                                    "line": 4,
                                    "col": 27
                                  },
                                  "file": 99
                                }
                              }
                            }
                          ],
                          "ty": {
                            "Con": {
                              "id": "Result",
                              "args": [
                                {
                                  "Con": {
                                    "id": "Ref",
                                    "args": [
                                      {
                                        "Con": {
                                          "id": "File",
                                          "args": []
                                        }
                                      }
                                    ]
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "error",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 20
                            },
                            "end": {
                              "line": 4,
                              "col": 27
                            },
                            "file": 99
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "Ref",
                          "args": [
                            {
                              "Con": {
                                "id": "File",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 28
                        },
                        "end": {
                          "line": 4,
                          "col": 28
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Ref",
                      "args": [
                        {
                          "Con": {
                            "id": "File",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 5
                    },
                    "end": {
                      "line": 4,
                      "col": 28
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "Result.Ok",
                      "decl": {
                        "start": {
                          "line": 52,
                          "col": 1
                        },
                        "end": {
                          "line": 55,
                          "col": 1
                        },
                        "file": 99
                      },
                      "generics_instantiated": [
                        {
                          "Con": {
                            "id": "Unit",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "error",
                            "args": []
                          }
                        }
                      ],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "Unit",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Result",
                              "args": [
                                {
                                  "Con": {
                                    "id": "Unit",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "error",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 5
                        },
                        "end": {
                          "line": 5,
                          "col": 7
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "bar",
                            "decl": {
                              "start": {
                                "line": 8,
                                "col": 1
                              },
                              "end": {
                                "line": 8,
                                "col": 22
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "id": "Ref",
                                      "args": [
                                        {
                                          "Con": {
                                            "id": "File",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "id": "Unit",
                                    "args": []
                                  }
                                }
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 8
                              },
                              "end": {
                                "line": 5,
                                "col": 11
                              },
                              "file": 99
                            }
                          }
                        },
                        "args": [
                          {
                            "Var": {
                              "value": "f",
                              "decl": {
                                "start": {
                                  "line": 4,
                                  "col": 9
                                },
                                "end": {
                                  "line": 4,
                                  "col": 10
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "Ref",
                                  "args": [
                                    {
                                      "Con": {
                                        "id": "File",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 12
                                },
                                "end": {
                                  "line": 5,
                                  "col": 13
                                },
                                "file": 99
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "id": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 11
                          },
                          "end": {
                            "line": 5,
                            "col": 13
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Result",
                      "args": [
                        {
                          "Con": {
                            "id": "Unit",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "error",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 7
                    },
                    "end": {
                      "line": 5,
                      "col": 14
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Result",
                "args": [
                  {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "id": "error",
                      "args": []
                    }
                  }
                ]
              }
            },
            "span": {
              "start": {
                "line": 3,
                "col": 24
              },
              "end": {
                "line": 6,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Result",
                  "args": [
                    {
                      "Con": {
                        "id": "Unit",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "error",
                        "args": []
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Result",
              "args": [
                {
                  "Con": {
                    "id": "Unit",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "error",
                    "args": []
                  }
                }
              ]
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 3,
          "col": 1
        },
        "end": {
          "line": 6,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "bar",
        "generics": [],
        "args": [
          {
            "pat": {
              "Type": {
                "ident": "f",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 8,
                    "col": 8
                  },
                  "end": {
                    "line": 8,
                    "col": 9
                  },
                  "file": 99
                }
              }
            },
            "ann": {
              "Con": {
                "name": "Ref",
                "args": [
                  {
                    "Con": {
                      "name": "os.File",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ty": {
              "Con": {
                "id": "Ref",
                "args": [
                  {
                    "Con": {
                      "id": "File",
                      "args": []
                    }
                  }
                ]
              }
            }
          }
        ],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [],
            "ty": {
              "Con": {
                "id": "Unit",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 8,
                "col": 21
              },
              "end": {
                "line": 8,
                "col": 22
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "Ref",
                    "args": [
                      {
                        "Con": {
                          "id": "File",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [
            {
              "Con": {
                "id": "Ref",
                "args": [
                  {
                    "Con": {
                      "id": "File",
                      "args": []
                    }
                  }
                ]
              }
            }
          ],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 8,
          "col": 1
        },
        "end": {
          "line": 8,
          "col": 22
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "start": {
                          "line": 3,
                          "col": 1
                        },
                        "end": {
                          "line": 6,
                          "col": 1
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Result",
                              "args": [
                                {
                                  "Con": {
                                    "id": "Unit",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "error",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 11,
                          "col": 5
                        },
                        "end": {
                          "line": 11,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [],
                  "ty": {
                    "Con": {
                      "id": "Result",
                      "args": [
                        {
                          "Con": {
                            "id": "Unit",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "error",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 11,
                      "col": 8
                    },
                    "end": {
                      "line": 11,
                      "col": 9
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Result",
                "args": [
                  {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "id": "error",
                      "args": []
                    }
                  }
                ]
              }
            },
            "span": {
              "start": {
                "line": 10,
                "col": 11
              },
              "end": {
                "line": 12,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 10,
          "col": 1
        },
        "end": {
          "line": 12,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
