Simple check

SOURCE:
fn foo() -> int { 1 }

OUTPUT:
fn () -> int
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "foo",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Literal": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 19
                    },
                    "end": {
                      "line": 1,
                      "col": 20
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 17
              },
              "end": {
                "line": 1,
                "col": 21
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 21
        },
        "file": 99
      }
    }
  }
]
