Simple check

SOURCE:
fn foo() -> int { 1 }

OUTPUT:
fn () -> int
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "foo",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 1,
                            "col": 18
                          },
                          "end": {
                            "line": 1,
                            "col": 19
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 1,
                      "col": 21
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 1,
                "col": 21
              }
            }
          }
        }
      ],
      "source": "fn foo() -> int { 1 }"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
