Trait bounds

SOURCE:
fn foo<T: equals>(x: T) -> Bool {
  true
}

fn bar<Y: equals>(x: Y) -> Bool {
  foo(x)
}

OUTPUT:
fn <A: equals>(A) -> Bool
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "foo",
              "generics": [
                "T"
              ],
              "bounds": [
                {
                  "Con": {
                    "name": "equals",
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "args": [
                {
                  "pat": {
                    "Type": {
                      "ident": "x",
                      "ann": "Unknown",
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 18
                        },
                        "end": {
                          "line": 1,
                          "col": 19
                        }
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "T",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "T",
                      "args": []
                    }
                  }
                }
              ],
              "ret": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Literal": {
                        "lit": {
                          "Bool": true
                        },
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 2,
                            "col": 6
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 32
                    },
                    "end": {
                      "line": 3,
                      "col": 1
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [
                  {
                    "Var": 99
                  }
                ],
                "bounds": [
                  {
                    "Con": {
                      "name": "equals",
                      "args": [
                        {
                          "Var": 99
                        }
                      ]
                    }
                  }
                ],
                "ret": {
                  "Con": {
                    "name": "Bool",
                    "args": []
                  }
                },
                "fx": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 3,
                "col": 1
              }
            }
          }
        },
        {
          "Closure": {
            "fun": {
              "name": "bar",
              "generics": [
                "Y"
              ],
              "bounds": [
                {
                  "Con": {
                    "name": "equals",
                    "args": [
                      {
                        "Con": {
                          "name": "Y",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "args": [
                {
                  "pat": {
                    "Type": {
                      "ident": "x",
                      "ann": "Unknown",
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 18
                        },
                        "end": {
                          "line": 5,
                          "col": 19
                        }
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "Y",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Y",
                      "args": []
                    }
                  }
                }
              ],
              "ret": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Bool",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "foo",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 0
                                },
                                "end": {
                                  "line": 3,
                                  "col": 1
                                }
                              }
                            },
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Y",
                                      "args": []
                                    }
                                  }
                                ],
                                "bounds": [
                                  {
                                    "Con": {
                                      "name": "equals",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "Y",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "ret": {
                                  "Con": {
                                    "name": "Bool",
                                    "args": []
                                  }
                                },
                                "fx": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 2
                              },
                              "end": {
                                "line": 6,
                                "col": 5
                              }
                            }
                          }
                        },
                        "args": [
                          {
                            "Var": {
                              "value": "x",
                              "decl": {
                                "file_id": {
                                  "package": "user",
                                  "filename": "test.brg"
                                },
                                "span": {
                                  "start": {
                                    "line": 5,
                                    "col": 18
                                  },
                                  "end": {
                                    "line": 5,
                                    "col": 19
                                  }
                                }
                              },
                              "ty": {
                                "Con": {
                                  "name": "Y",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 6
                                },
                                "end": {
                                  "line": 6,
                                  "col": 7
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 2
                          },
                          "end": {
                            "line": 6,
                            "col": 8
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 32
                    },
                    "end": {
                      "line": 7,
                      "col": 1
                    }
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [
                  {
                    "Var": 99
                  }
                ],
                "bounds": [
                  {
                    "Con": {
                      "name": "equals",
                      "args": [
                        {
                          "Var": 99
                        }
                      ]
                    }
                  }
                ],
                "ret": {
                  "Con": {
                    "name": "Bool",
                    "args": []
                  }
                },
                "fx": []
              }
            },
            "span": {
              "start": {
                "line": 5,
                "col": 0
              },
              "end": {
                "line": 7,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn foo<T: equals>(x: T) -> Bool {\n  true\n}\n\nfn bar<Y: equals>(x: Y) -> Bool {\n  foo(x)\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
