Tuple structs

SOURCE:
struct Foo(int)

struct Bar<T>(int, T)

fn check(f: Foo) -> int {
    f.0
}

fn bar_check(b: Bar<string>) -> (int, string) {
    (b.0, b.1)
}

fn main() -> Foo {
    let b = Bar(1, false)
    let c = Bar(1, "yo")
    bar_check(c)

    @ensure check(Foo(1)), int
    Foo(2)
}

OUTPUT:
fn () -> Foo
---
No errors.
---
[
  {
    "NewtypeDef": {
      "def": {
        "name": "Foo",
        "generics": [],
        "fields": [
          {
            "name": "field0",
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ty": {
              "Var": -1
            }
          }
        ]
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 1,
          "col": 15
        },
        "file": 99
      }
    }
  },
  {
    "NewtypeDef": {
      "def": {
        "name": "Bar",
        "generics": [
          {
            "name": "T",
            "bounds": [],
            "span": {
              "start": {
                "line": 3,
                "col": 12
              },
              "end": {
                "line": 3,
                "col": 13
              },
              "file": 99
            }
          }
        ],
        "fields": [
          {
            "name": "field0",
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ty": {
              "Var": -1
            }
          },
          {
            "name": "field1",
            "ann": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "ty": {
              "Var": -1
            }
          }
        ]
      },
      "span": {
        "start": {
          "line": 3,
          "col": 1
        },
        "end": {
          "line": 3,
          "col": 21
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "check",
        "generics": [],
        "args": [
          {
            "pat": {
              "Type": {
                "ident": "f",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 5,
                    "col": 10
                  },
                  "end": {
                    "line": 5,
                    "col": 11
                  },
                  "file": 99
                }
              }
            },
            "ann": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            },
            "ty": {
              "Con": {
                "id": "Foo",
                "args": []
              }
            }
          }
        ],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "FieldAccess": {
                  "expr": {
                    "Var": {
                      "value": "f",
                      "decl": {
                        "start": {
                          "line": 5,
                          "col": 10
                        },
                        "end": {
                          "line": 5,
                          "col": 11
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 5
                        },
                        "end": {
                          "line": 6,
                          "col": 6
                        },
                        "file": 99
                      }
                    }
                  },
                  "field": "first",
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 7
                    },
                    "end": {
                      "line": 6,
                      "col": 8
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 5,
                "col": 25
              },
              "end": {
                "line": 7,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "Foo",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [
            {
              "Con": {
                "id": "Foo",
                "args": []
              }
            }
          ],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 5,
          "col": 1
        },
        "end": {
          "line": 7,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "bar_check",
        "generics": [],
        "args": [
          {
            "pat": {
              "Type": {
                "ident": "b",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 9,
                    "col": 14
                  },
                  "end": {
                    "line": 9,
                    "col": 15
                  },
                  "file": 99
                }
              }
            },
            "ann": {
              "Con": {
                "name": "Bar",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ty": {
              "Con": {
                "id": "Bar",
                "args": [
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                ]
              }
            }
          }
        ],
        "ret": {
          "Con": {
            "id": "Tuple2",
            "args": [
              {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              {
                "Con": {
                  "id": "string",
                  "args": []
                }
              }
            ]
          }
        },
        "ann": {
          "Con": {
            "name": "Tuple2",
            "args": [
              {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              {
                "Con": {
                  "name": "string",
                  "args": []
                }
              }
            ]
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "StructCall": {
                  "name": "Tuple2",
                  "fields": [
                    {
                      "name": "first",
                      "value": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "b",
                              "decl": {
                                "start": {
                                  "line": 9,
                                  "col": 14
                                },
                                "end": {
                                  "line": 9,
                                  "col": 15
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "Bar",
                                  "args": [
                                    {
                                      "Con": {
                                        "id": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 10,
                                  "col": 6
                                },
                                "end": {
                                  "line": 10,
                                  "col": 7
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "first",
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 10,
                              "col": 8
                            },
                            "end": {
                              "line": 10,
                              "col": 9
                            },
                            "file": 99
                          }
                        }
                      }
                    },
                    {
                      "name": "second",
                      "value": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "b",
                              "decl": {
                                "start": {
                                  "line": 9,
                                  "col": 14
                                },
                                "end": {
                                  "line": 9,
                                  "col": 15
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "Bar",
                                  "args": [
                                    {
                                      "Con": {
                                        "id": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 10,
                                  "col": 11
                                },
                                "end": {
                                  "line": 10,
                                  "col": 12
                                },
                                "file": 99
                              }
                            }
                          },
                          "field": "second",
                          "ty": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 10,
                              "col": 13
                            },
                            "end": {
                              "line": 10,
                              "col": 14
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "rest": null,
                  "ty": {
                    "Con": {
                      "id": "Tuple2",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 10,
                      "col": 5
                    },
                    "end": {
                      "line": 10,
                      "col": 14
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Tuple2",
                "args": [
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                ]
              }
            },
            "span": {
              "start": {
                "line": 9,
                "col": 47
              },
              "end": {
                "line": 11,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "Bar",
                    "args": [
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [
            {
              "Con": {
                "id": "Bar",
                "args": [
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                ]
              }
            }
          ],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Tuple2",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "string",
                    "args": []
                  }
                }
              ]
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 9,
          "col": 1
        },
        "end": {
          "line": 11,
          "col": 1
        },
        "file": 99
      }
    }
  },
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Foo",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Foo",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "b",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 14,
                            "col": 9
                          },
                          "end": {
                            "line": 14,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Var": 99
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "Bar",
                          "decl": {
                            "start": {
                              "line": 3,
                              "col": 1
                            },
                            "end": {
                              "line": 3,
                              "col": 21
                            },
                            "file": 99
                          },
                          "generics_instantiated": [
                            {
                              "Var": 99
                            }
                          ],
                          "ty": {
                            "Con": {
                              "id": "Bar",
                              "args": [
                                {
                                  "Var": 99
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 14,
                              "col": 13
                            },
                            "end": {
                              "line": 14,
                              "col": 16
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 14,
                                "col": 17
                              },
                              "end": {
                                "line": 14,
                                "col": 18
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Bool": false
                            },
                            "ty": {
                              "Con": {
                                "id": "bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 14,
                                "col": 20
                              },
                              "end": {
                                "line": 14,
                                "col": 25
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Var": 99
                      },
                      "span": {
                        "start": {
                          "line": 14,
                          "col": 16
                        },
                        "end": {
                          "line": 14,
                          "col": 25
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 14,
                      "col": 5
                    },
                    "end": {
                      "line": 14,
                      "col": 25
                    },
                    "file": 99
                  }
                }
              },
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "c",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 15,
                            "col": 9
                          },
                          "end": {
                            "line": 15,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "Bar",
                        "args": [
                          {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  },
                  "value": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "Bar",
                          "decl": {
                            "start": {
                              "line": 3,
                              "col": 1
                            },
                            "end": {
                              "line": 3,
                              "col": 21
                            },
                            "file": 99
                          },
                          "generics_instantiated": [
                            {
                              "Var": 99
                            }
                          ],
                          "ty": {
                            "Con": {
                              "id": "Bar",
                              "args": [
                                {
                                  "Var": 99
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 15,
                              "col": 13
                            },
                            "end": {
                              "line": 15,
                              "col": 16
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 17
                              },
                              "end": {
                                "line": 15,
                                "col": 18
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "String": {
                                "Single": "yo"
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 15,
                                "col": 20
                              },
                              "end": {
                                "line": 15,
                                "col": 24
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "Bar",
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 15,
                          "col": 16
                        },
                        "end": {
                          "line": 15,
                          "col": 24
                        },
                        "file": 99
                      }
                    }
                  },
                  "mutable": false,
                  "ty": {
                    "Con": {
                      "id": "Bar",
                      "args": [
                        {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 15,
                      "col": 5
                    },
                    "end": {
                      "line": 15,
                      "col": 24
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "bar_check",
                      "decl": {
                        "start": {
                          "line": 9,
                          "col": 1
                        },
                        "end": {
                          "line": 11,
                          "col": 1
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "Bar",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Tuple2",
                              "args": [
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "string",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 16,
                          "col": 5
                        },
                        "end": {
                          "line": 16,
                          "col": 14
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Var": {
                        "value": "c",
                        "decl": {
                          "start": {
                            "line": 15,
                            "col": 9
                          },
                          "end": {
                            "line": 15,
                            "col": 10
                          },
                          "file": 99
                        },
                        "generics_instantiated": [],
                        "ty": {
                          "Con": {
                            "id": "Bar",
                            "args": [
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ]
                          }
                        },
                        "span": {
                          "start": {
                            "line": 16,
                            "col": 15
                          },
                          "end": {
                            "line": 16,
                            "col": 16
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Tuple2",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 16,
                      "col": 14
                    },
                    "end": {
                      "line": 16,
                      "col": 16
                    },
                    "file": 99
                  }
                }
              },
              {
                "CheckType": {
                  "expr": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "check",
                          "decl": {
                            "start": {
                              "line": 5,
                              "col": 1
                            },
                            "end": {
                              "line": 7,
                              "col": 1
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "Foo",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 18,
                              "col": 13
                            },
                            "end": {
                              "line": 18,
                              "col": 18
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "Foo",
                                "decl": {
                                  "start": {
                                    "line": 1,
                                    "col": 1
                                  },
                                  "end": {
                                    "line": 1,
                                    "col": 15
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "Foo",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 18,
                                    "col": 19
                                  },
                                  "end": {
                                    "line": 18,
                                    "col": 22
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "args": [
                              {
                                "Literal": {
                                  "lit": {
                                    "Int": 1
                                  },
                                  "ty": {
                                    "Con": {
                                      "id": "int",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 18,
                                      "col": 23
                                    },
                                    "end": {
                                      "line": 18,
                                      "col": 24
                                    },
                                    "file": 99
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "id": "Foo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 18,
                                "col": 22
                              },
                              "end": {
                                "line": 18,
                                "col": 24
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 18,
                          "col": 18
                        },
                        "end": {
                          "line": 18,
                          "col": 25
                        },
                        "file": 99
                      }
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 18,
                      "col": 5
                    },
                    "end": {
                      "line": 18,
                      "col": 31
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "Foo",
                      "decl": {
                        "start": {
                          "line": 1,
                          "col": 1
                        },
                        "end": {
                          "line": 1,
                          "col": 15
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 19,
                          "col": 5
                        },
                        "end": {
                          "line": 19,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 2
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 19,
                            "col": 9
                          },
                          "end": {
                            "line": 19,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 19,
                      "col": 8
                    },
                    "end": {
                      "line": 19,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Foo",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 13,
                "col": 18
              },
              "end": {
                "line": 20,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Foo",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 13,
          "col": 1
        },
        "end": {
          "line": 20,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
