Variadic functions

SOURCE:
fn borgo_main() {
  fn foo(a: int, b: VarArgs<string>) {}

  foo(1);
  foo(1, "a");
  foo(1, "a", "b", "c");
}

OUTPUT:
fn () -> ()
---
No errors.
---
{
  "files": [
    {
      "name": "test.brg",
      "decls": [
        {
          "Closure": {
            "fun": {
              "name": "borgo_main",
              "generics": [],
              "bounds": [],
              "args": [],
              "ret": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "ann": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "body": {
                "Block": {
                  "stmts": [
                    {
                      "Closure": {
                        "fun": {
                          "name": "foo",
                          "generics": [],
                          "bounds": [],
                          "args": [
                            {
                              "pat": {
                                "Type": {
                                  "ident": "a",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 9
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 10
                                    }
                                  }
                                }
                              },
                              "ann": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              }
                            },
                            {
                              "pat": {
                                "Type": {
                                  "ident": "b",
                                  "is_mut": false,
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 2,
                                      "col": 17
                                    },
                                    "end": {
                                      "line": 2,
                                      "col": 18
                                    }
                                  }
                                }
                              },
                              "ann": {
                                "Con": {
                                  "name": "VarArgs",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "ty": {
                                "Con": {
                                  "name": "VarArgs",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ],
                          "ret": {
                            "Con": {
                              "name": "Unit",
                              "args": []
                            }
                          },
                          "ann": {
                            "Con": {
                              "name": "Unit",
                              "args": []
                            }
                          },
                          "body": {
                            "Block": {
                              "stmts": [],
                              "ty": {
                                "Con": {
                                  "name": "Unit",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 37
                                },
                                "end": {
                                  "line": 2,
                                  "col": 39
                                }
                              }
                            }
                          },
                          "bounded_ty": {
                            "generics": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "name": "VarArgs",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "Unit",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            }
                          }
                        },
                        "kind": "Inline",
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              {
                                "Con": {
                                  "name": "VarArgs",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "name": "Unit",
                                "args": []
                              }
                            },
                            "id": -1
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 2,
                            "col": 39
                          }
                        }
                      }
                    },
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "foo",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 2
                                },
                                "end": {
                                  "line": 2,
                                  "col": 39
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "name": "VarArgs",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "Unit",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 2
                              },
                              "end": {
                                "line": 4,
                                "col": 5
                              }
                            }
                          }
                        },
                        "args": [
                          {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 4,
                                  "col": 6
                                },
                                "end": {
                                  "line": 4,
                                  "col": 7
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 2
                          },
                          "end": {
                            "line": 4,
                            "col": 8
                          }
                        }
                      }
                    },
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "foo",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 2
                                },
                                "end": {
                                  "line": 2,
                                  "col": 39
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "name": "VarArgs",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "Unit",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 2
                              },
                              "end": {
                                "line": 5,
                                "col": 5
                              }
                            }
                          }
                        },
                        "args": [
                          {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 6
                                },
                                "end": {
                                  "line": 5,
                                  "col": 7
                                }
                              }
                            }
                          },
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "a",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 5,
                                  "col": 9
                                },
                                "end": {
                                  "line": 5,
                                  "col": 12
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 2
                          },
                          "end": {
                            "line": 5,
                            "col": 13
                          }
                        }
                      }
                    },
                    {
                      "Call": {
                        "func": {
                          "Var": {
                            "value": "foo",
                            "decl": {
                              "file_id": {
                                "package": "user",
                                "filename": "test.brg"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 2
                                },
                                "end": {
                                  "line": 2,
                                  "col": 39
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Fun": {
                                "args": [
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  },
                                  {
                                    "Con": {
                                      "name": "VarArgs",
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ],
                                "bounds": [],
                                "ret": {
                                  "Con": {
                                    "name": "Unit",
                                    "args": []
                                  }
                                },
                                "id": -1
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 2
                              },
                              "end": {
                                "line": 6,
                                "col": 5
                              }
                            }
                          }
                        },
                        "args": [
                          {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 6
                                },
                                "end": {
                                  "line": 6,
                                  "col": 7
                                }
                              }
                            }
                          },
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "a",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 9
                                },
                                "end": {
                                  "line": 6,
                                  "col": 12
                                }
                              }
                            }
                          },
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "b",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 14
                                },
                                "end": {
                                  "line": 6,
                                  "col": 17
                                }
                              }
                            }
                          },
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "c",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 19
                                },
                                "end": {
                                  "line": 6,
                                  "col": 22
                                }
                              }
                            }
                          }
                        ],
                        "ty": {
                          "Con": {
                            "name": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 2
                          },
                          "end": {
                            "line": 6,
                            "col": 23
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 7,
                      "col": 1
                    }
                  }
                }
              },
              "bounded_ty": {
                "generics": [],
                "ty": {
                  "Fun": {
                    "args": [],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              }
            },
            "kind": "TopLevel",
            "ty": {
              "Fun": {
                "args": [],
                "bounds": [],
                "ret": {
                  "Con": {
                    "name": "Unit",
                    "args": []
                  }
                },
                "id": -1
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 0
              },
              "end": {
                "line": 7,
                "col": 1
              }
            }
          }
        }
      ],
      "source": "fn borgo_main() {\n  fn foo(a: int, b: VarArgs<string>) {}\n\n  foo(1);\n  foo(1, \"a\");\n  foo(1, \"a\", \"b\", \"c\");\n}"
    }
  ],
  "errors": [
    [
      "test.brg",
      []
    ]
  ]
}
