Variadic functions

SOURCE:
fn main() {
    fn foo(a: int, b: VarArgs<string>) {}

    foo(1)
    foo(1, "a")
    foo(1, "a", "b", "c")
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Closure": {
                  "fun": {
                    "name": "foo",
                    "generics": [],
                    "args": [
                      {
                        "pat": {
                          "Type": {
                            "ident": "a",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 12
                              },
                              "end": {
                                "line": 2,
                                "col": 13
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      },
                      {
                        "pat": {
                          "Type": {
                            "ident": "b",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 20
                              },
                              "end": {
                                "line": 2,
                                "col": 21
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "VarArgs",
                            "args": [
                              {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              }
                            ]
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "VarArgs",
                            "args": [
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ]
                          }
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "id": "Unit",
                        "args": []
                      }
                    },
                    "ann": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "body": {
                      "Block": {
                        "stmts": [],
                        "ty": {
                          "Con": {
                            "id": "Unit",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 40
                          },
                          "end": {
                            "line": 2,
                            "col": 41
                          },
                          "file": 99
                        }
                      }
                    },
                    "bounded_ty": {
                      "generics": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "VarArgs",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Unit",
                              "args": []
                            }
                          }
                        }
                      }
                    }
                  },
                  "kind": "Inline",
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "id": "VarArgs",
                            "args": [
                              {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "Unit",
                          "args": []
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 5
                    },
                    "end": {
                      "line": 2,
                      "col": 41
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "start": {
                          "line": 2,
                          "col": 5
                        },
                        "end": {
                          "line": 2,
                          "col": 41
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "VarArgs",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Unit",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 5
                        },
                        "end": {
                          "line": 4,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 9
                          },
                          "end": {
                            "line": 4,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 8
                    },
                    "end": {
                      "line": 4,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "start": {
                          "line": 2,
                          "col": 5
                        },
                        "end": {
                          "line": 2,
                          "col": 41
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "VarArgs",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Unit",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 5
                        },
                        "end": {
                          "line": 5,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 9
                          },
                          "end": {
                            "line": 5,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "a"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 5,
                            "col": 12
                          },
                          "end": {
                            "line": 5,
                            "col": 15
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 8
                    },
                    "end": {
                      "line": 5,
                      "col": 15
                    },
                    "file": 99
                  }
                }
              },
              {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "start": {
                          "line": 2,
                          "col": 5
                        },
                        "end": {
                          "line": 2,
                          "col": 41
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "VarArgs",
                                "args": [
                                  {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Unit",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 5
                        },
                        "end": {
                          "line": 6,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 9
                          },
                          "end": {
                            "line": 6,
                            "col": 10
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "a"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 12
                          },
                          "end": {
                            "line": 6,
                            "col": 15
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "b"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 17
                          },
                          "end": {
                            "line": 6,
                            "col": 20
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "c"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 22
                          },
                          "end": {
                            "line": 6,
                            "col": 25
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 8
                    },
                    "end": {
                      "line": 6,
                      "col": 25
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "Unit",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 11
              },
              "end": {
                "line": 7,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 1
        },
        "end": {
          "line": 7,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
