While loops.

SOURCE:
fn borgo_main() {
  let x = 1;
  while x < 10 {
    x as int;
  }
}

OUTPUT:
fn () -> ()
---
No errors.
---
[
  {
    "Closure": {
      "fun": {
        "name": "borgo_main",
        "generics": [],
        "args": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "ann": {
          "Con": {
            "name": "Unit",
            "args": []
          }
        },
        "body": {
          "Block": {
            "stmts": [
              {
                "Let": {
                  "binding": {
                    "pat": {
                      "Type": {
                        "ident": "x",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 6
                          },
                          "end": {
                            "line": 2,
                            "col": 7
                          },
                          "file": 99
                        }
                      }
                    },
                    "ann": "Unknown",
                    "ty": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  },
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 10
                        },
                        "end": {
                          "line": 2,
                          "col": 11
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 2
                    },
                    "end": {
                      "line": 2,
                      "col": 12
                    },
                    "file": 99
                  }
                }
              },
              {
                "Loop": {
                  "kind": {
                    "While": {
                      "expr": {
                        "Binary": {
                          "op": "Lt",
                          "left": {
                            "Var": {
                              "value": "x",
                              "decl": {
                                "start": {
                                  "line": 2,
                                  "col": 6
                                },
                                "end": {
                                  "line": 2,
                                  "col": 7
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 8
                                },
                                "end": {
                                  "line": 3,
                                  "col": 9
                                },
                                "file": 99
                              }
                            }
                          },
                          "right": {
                            "Literal": {
                              "lit": {
                                "Int": 10
                              },
                              "ty": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 12
                                },
                                "end": {
                                  "line": 3,
                                  "col": 14
                                },
                                "file": 99
                              }
                            }
                          },
                          "ty": {
                            "Con": {
                              "id": "bool",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 8
                            },
                            "end": {
                              "line": 3,
                              "col": 14
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "x",
                                "decl": {
                                  "start": {
                                    "line": 2,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 7
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 4,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 4,
                                    "col": 5
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 4
                              },
                              "end": {
                                "line": 4,
                                "col": 12
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 15
                        },
                        "end": {
                          "line": 5,
                          "col": 3
                        },
                        "file": 99
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 2
                    },
                    "end": {
                      "line": 5,
                      "col": 3
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Var": -333
            },
            "span": {
              "start": {
                "line": 1,
                "col": 16
              },
              "end": {
                "line": 6,
                "col": 1
              },
              "file": 99
            }
          }
        },
        "bounded_ty": {
          "generics": [],
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          }
        }
      },
      "kind": "TopLevel",
      "ty": {
        "Fun": {
          "args": [],
          "bounds": [],
          "ret": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          }
        }
      },
      "span": {
        "start": {
          "line": 1,
          "col": 0
        },
        "end": {
          "line": 6,
          "col": 1
        },
        "file": 99
      }
    }
  }
]
