A function that is already wrapped, doesn't get wrapped again.

SOURCE:
{
  fn foo(x: int) -> Result<string, ErrFoo> { Err(ErrFoo::A) }

  fn bar(f: fn (x: int) -> Result<string, ErrFoo>) {
    ()
  }

  bar(foo);
  true
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "x",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 9
                      },
                      "end": {
                        "line": 2,
                        "col": 10
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Result",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "name": "ErrFoo",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Result",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "name": "ErrFoo",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "Err",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 0
                              },
                              "end": {
                                "line": 5,
                                "col": 1
                              }
                            }
                          },
                          "generics_instantiated": [
                            {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "name": "ErrFoo",
                                "args": []
                              }
                            }
                          ],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "ErrFoo",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "Result",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    },
                                    {
                                      "Con": {
                                        "name": "ErrFoo",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "id": -1
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 45
                            },
                            "end": {
                              "line": 2,
                              "col": 48
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "ErrFoo::A",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 18,
                                  "col": 0
                                },
                                "end": {
                                  "line": 21,
                                  "col": 1
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "name": "ErrFoo",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 49
                              },
                              "end": {
                                "line": 2,
                                "col": 58
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Result",
                          "args": [
                            {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "name": "ErrFoo",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 45
                        },
                        "end": {
                          "line": 2,
                          "col": 59
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Result",
                    "args": [
                      {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "name": "ErrFoo",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 43
                  },
                  "end": {
                    "line": 2,
                    "col": 61
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Result",
                      "args": [
                        {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "ErrFoo",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Result",
                  "args": [
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "ErrFoo",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 61
            }
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "bar",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "f",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 9
                      },
                      "end": {
                        "line": 4,
                        "col": 10
                      }
                    }
                  }
                },
                "ann": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "Result",
                        "args": [
                          {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "name": "ErrFoo",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Result",
                        "args": [
                          {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "name": "ErrFoo",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    "id": -1
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Unit",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "Unit",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Unit": {
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 4
                        },
                        "end": {
                          "line": 5,
                          "col": 6
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Unit",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 51
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "Result",
                            "args": [
                              {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              {
                                "Con": {
                                  "name": "ErrFoo",
                                  "args": []
                                }
                              }
                            ]
                          }
                        },
                        "id": -1
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Result",
                        "args": [
                          {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "name": "ErrFoo",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    "id": -1
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Unit",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 3
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "bar",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 2
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "Result",
                            "args": [
                              {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              {
                                "Con": {
                                  "name": "ErrFoo",
                                  "args": []
                                }
                              }
                            ]
                          }
                        },
                        "id": -1
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 2
                },
                "end": {
                  "line": 8,
                  "col": 5
                }
              }
            }
          },
          "args": [
            {
              "Var": {
                "value": "foo",
                "decl": {
                  "file_id": {
                    "package": "dummy",
                    "filename": "dummy"
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 2
                    },
                    "end": {
                      "line": 2,
                      "col": 61
                    }
                  }
                },
                "generics_instantiated": [],
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Result",
                        "args": [
                          {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "name": "ErrFoo",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 6
                  },
                  "end": {
                    "line": 8,
                    "col": 9
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Unit",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 10
            }
          }
        }
      },
      {
        "Literal": {
          "lit": {
            "Bool": true
          },
          "ty": {
            "Con": {
              "name": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 9,
              "col": 2
            },
            "end": {
              "line": 9,
              "col": 6
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 10,
        "col": 1
      }
    }
  }
}
