A function within a function gets its own return type.

SOURCE:
{
  fn foo() -> int {

    fn bar() -> string {
      if true {
        return "foo"
      }

      "bar"
    }


    bar() as string;

    return 2
  }
}

OUTPUT:
fn () -> int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Closure": {
                      "fun": {
                        "name": "bar",
                        "generics": [],
                        "bounds": [],
                        "args": [],
                        "ret": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "body": {
                          "Block": {
                            "stmts": [
                              {
                                "If": {
                                  "cond": {
                                    "Literal": {
                                      "lit": {
                                        "Bool": true
                                      },
                                      "ty": {
                                        "Con": {
                                          "name": "bool",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 9
                                        },
                                        "end": {
                                          "line": 5,
                                          "col": 13
                                        }
                                      }
                                    }
                                  },
                                  "then": {
                                    "Block": {
                                      "stmts": [
                                        {
                                          "Return": {
                                            "expr": {
                                              "Literal": {
                                                "lit": {
                                                  "String": [
                                                    "foo",
                                                    null
                                                  ]
                                                },
                                                "ty": {
                                                  "Con": {
                                                    "name": "string",
                                                    "args": []
                                                  }
                                                },
                                                "span": {
                                                  "start": {
                                                    "line": 6,
                                                    "col": 15
                                                  },
                                                  "end": {
                                                    "line": 6,
                                                    "col": 20
                                                  }
                                                }
                                              }
                                            },
                                            "ty": {
                                              "Con": {
                                                "name": "string",
                                                "args": []
                                              }
                                            },
                                            "span": {
                                              "start": {
                                                "line": 6,
                                                "col": 8
                                              },
                                              "end": {
                                                "line": 6,
                                                "col": 20
                                              }
                                            }
                                          }
                                        }
                                      ],
                                      "ty": {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 14
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 7
                                        }
                                      }
                                    }
                                  },
                                  "els": {
                                    "Block": {
                                      "stmts": [],
                                      "ty": {
                                        "Con": {
                                          "name": "Unit",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 6
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 7
                                        }
                                      }
                                    }
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "Unit",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 7
                                    }
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "String": [
                                      "bar",
                                      null
                                    ]
                                  },
                                  "ty": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 6
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 11
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 23
                              },
                              "end": {
                                "line": 10,
                                "col": 5
                              }
                            }
                          }
                        },
                        "bounded_ty": {
                          "generics": [],
                          "ty": {
                            "Fun": {
                              "args": [],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          }
                        }
                      },
                      "kind": "Inline",
                      "ty": {
                        "Fun": {
                          "args": [],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          "id": -1
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 4
                        },
                        "end": {
                          "line": 10,
                          "col": 5
                        }
                      }
                    }
                  },
                  {
                    "CheckType": {
                      "expr": {
                        "Call": {
                          "func": {
                            "Var": {
                              "value": "bar",
                              "decl": {
                                "file_id": {
                                  "package": "dummy",
                                  "filename": "dummy"
                                },
                                "span": {
                                  "start": {
                                    "line": 4,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 10,
                                    "col": 5
                                  }
                                }
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Fun": {
                                  "args": [],
                                  "bounds": [],
                                  "ret": {
                                    "Con": {
                                      "name": "string",
                                      "args": []
                                    }
                                  },
                                  "id": -1
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 13,
                                  "col": 4
                                },
                                "end": {
                                  "line": 13,
                                  "col": 7
                                }
                              }
                            }
                          },
                          "args": [],
                          "ty": {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 13,
                              "col": 4
                            },
                            "end": {
                              "line": 13,
                              "col": 9
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 13,
                          "col": 4
                        },
                        "end": {
                          "line": 13,
                          "col": 19
                        }
                      }
                    }
                  },
                  {
                    "Return": {
                      "expr": {
                        "Literal": {
                          "lit": {
                            "Int": 2
                          },
                          "ty": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 15,
                              "col": 11
                            },
                            "end": {
                              "line": 15,
                              "col": 12
                            }
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 15,
                          "col": 4
                        },
                        "end": {
                          "line": 15,
                          "col": 12
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 18
                  },
                  "end": {
                    "line": 16,
                    "col": 3
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 16,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 17,
        "col": 1
      }
    }
  }
}
