A function within a function gets its own return type.

SOURCE:
{
  fn foo() -> int {

    fn bar() -> string {
      if true {
        return "foo"
      }

      "bar"
    }


    @ensure bar(), string

    return 2
  }
}

OUTPUT:
fn () -> int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Closure": {
                      "fun": {
                        "name": "bar",
                        "generics": [],
                        "args": [],
                        "ret": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "ann": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "body": {
                          "Block": {
                            "stmts": [
                              {
                                "If": {
                                  "cond": {
                                    "Literal": {
                                      "lit": {
                                        "Bool": true
                                      },
                                      "ty": {
                                        "Con": {
                                          "id": "bool",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 10
                                        },
                                        "end": {
                                          "line": 5,
                                          "col": 14
                                        },
                                        "file": 99
                                      }
                                    }
                                  },
                                  "then": {
                                    "Block": {
                                      "stmts": [
                                        {
                                          "Return": {
                                            "expr": {
                                              "Literal": {
                                                "lit": {
                                                  "String": {
                                                    "Single": "foo"
                                                  }
                                                },
                                                "ty": {
                                                  "Con": {
                                                    "id": "string",
                                                    "args": []
                                                  }
                                                },
                                                "span": {
                                                  "start": {
                                                    "line": 6,
                                                    "col": 16
                                                  },
                                                  "end": {
                                                    "line": 6,
                                                    "col": 21
                                                  },
                                                  "file": 99
                                                }
                                              }
                                            },
                                            "ty": {
                                              "Con": {
                                                "id": "string",
                                                "args": []
                                              }
                                            },
                                            "span": {
                                              "start": {
                                                "line": 6,
                                                "col": 9
                                              },
                                              "end": {
                                                "line": 6,
                                                "col": 21
                                              },
                                              "file": 99
                                            }
                                          }
                                        }
                                      ],
                                      "ty": {
                                        "Con": {
                                          "id": "string",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 15
                                        },
                                        "end": {
                                          "line": 7,
                                          "col": 7
                                        },
                                        "file": 99
                                      }
                                    }
                                  },
                                  "els": "Noop",
                                  "ty": {
                                    "Con": {
                                      "id": "Unit",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 7
                                    },
                                    "end": {
                                      "line": 7,
                                      "col": 7
                                    },
                                    "file": 99
                                  }
                                }
                              },
                              {
                                "Literal": {
                                  "lit": {
                                    "String": {
                                      "Single": "bar"
                                    }
                                  },
                                  "ty": {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 7
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 12
                                    },
                                    "file": 99
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 24
                              },
                              "end": {
                                "line": 10,
                                "col": 5
                              },
                              "file": 99
                            }
                          }
                        },
                        "bounded_ty": {
                          "generics": [],
                          "ty": {
                            "Fun": {
                              "args": [],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "string",
                                  "args": []
                                }
                              }
                            }
                          }
                        }
                      },
                      "kind": "Inline",
                      "ty": {
                        "Fun": {
                          "args": [],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 5
                        },
                        "end": {
                          "line": 10,
                          "col": 5
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "CheckType": {
                      "expr": {
                        "Call": {
                          "func": {
                            "Var": {
                              "value": "bar",
                              "decl": {
                                "start": {
                                  "line": 4,
                                  "col": 5
                                },
                                "end": {
                                  "line": 10,
                                  "col": 5
                                },
                                "file": 99
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Fun": {
                                  "args": [],
                                  "bounds": [],
                                  "ret": {
                                    "Con": {
                                      "id": "string",
                                      "args": []
                                    }
                                  }
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 13,
                                  "col": 13
                                },
                                "end": {
                                  "line": 13,
                                  "col": 16
                                },
                                "file": 99
                              }
                            }
                          },
                          "args": [],
                          "ty": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 13,
                              "col": 16
                            },
                            "end": {
                              "line": 13,
                              "col": 17
                            },
                            "file": 99
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 13,
                          "col": 5
                        },
                        "end": {
                          "line": 13,
                          "col": 26
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Return": {
                      "expr": {
                        "Literal": {
                          "lit": {
                            "Int": 2
                          },
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 15,
                              "col": 12
                            },
                            "end": {
                              "line": 15,
                              "col": 13
                            },
                            "file": 99
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 15,
                          "col": 5
                        },
                        "end": {
                          "line": 15,
                          "col": 13
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 19
                  },
                  "end": {
                    "line": 16,
                    "col": 3
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 16,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 17,
        "col": 1
      },
      "file": 99
    }
  }
}
