Aliasing in a match arm.

SOURCE:
match 1 {
  1 => "foo",
  foo => int_to_string(foo),
}

OUTPUT:
string
---
No errors.
---
{
  "Match": {
    "subject": {
      "Literal": {
        "lit": {
          "Int": 1
        },
        "ty": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 6
          },
          "end": {
            "line": 1,
            "col": 7
          }
        }
      }
    },
    "arms": [
      {
        "pat": {
          "Lit": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 2
              },
              "end": {
                "line": 2,
                "col": 3
              }
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "String": [
                "foo",
                null
              ]
            },
            "ty": {
              "Con": {
                "name": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 7
              },
              "end": {
                "line": 2,
                "col": 12
              }
            }
          }
        }
      },
      {
        "pat": {
          "Type": {
            "ident": "foo",
            "is_mut": false,
            "ann": "Unknown",
            "span": {
              "start": {
                "line": 3,
                "col": 2
              },
              "end": {
                "line": 3,
                "col": 5
              }
            }
          }
        },
        "expr": {
          "Call": {
            "func": {
              "Var": {
                "value": "int_to_string",
                "decl": {
                  "file_id": {
                    "package": "std",
                    "filename": "builtin.brg"
                  },
                  "span": {
                    "start": {
                      "line": 0,
                      "col": 0
                    },
                    "end": {
                      "line": 0,
                      "col": 0
                    }
                  }
                },
                "generics_instantiated": [],
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 9
                  },
                  "end": {
                    "line": 3,
                    "col": 22
                  }
                }
              }
            },
            "args": [
              {
                "Var": {
                  "value": "foo",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 3,
                        "col": 2
                      },
                      "end": {
                        "line": 3,
                        "col": 5
                      }
                    }
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 23
                    },
                    "end": {
                      "line": 3,
                      "col": 26
                    }
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "name": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 3,
                "col": 9
              },
              "end": {
                "line": 3,
                "col": 27
              }
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      }
    }
  }
}
