Aliasing in a match arm.

SOURCE:
match 1 {
  1 => "foo",
  foo => int_to_string(foo),
}

OUTPUT:
string
---
No errors.
---
{
  "Match": {
    "subject": {
      "Literal": {
        "lit": {
          "Int": 1
        },
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 7
          },
          "end": {
            "line": 1,
            "col": 8
          },
          "file": 99
        }
      }
    },
    "arms": [
      {
        "pat": {
          "Lit": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 3
              },
              "end": {
                "line": 2,
                "col": 4
              },
              "file": 99
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "String": {
                "Single": "foo"
              }
            },
            "ty": {
              "Con": {
                "id": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 8
              },
              "end": {
                "line": 2,
                "col": 13
              },
              "file": 99
            }
          }
        }
      },
      {
        "pat": {
          "Type": {
            "ident": "foo",
            "is_mut": false,
            "ann": "Unknown",
            "span": {
              "start": {
                "line": 3,
                "col": 3
              },
              "end": {
                "line": 3,
                "col": 6
              },
              "file": 99
            }
          }
        },
        "expr": {
          "Call": {
            "func": {
              "Var": {
                "value": "int_to_string",
                "decl": {
                  "start": {
                    "line": 39,
                    "col": 1
                  },
                  "end": {
                    "line": 41,
                    "col": 1
                  },
                  "file": 99
                },
                "generics_instantiated": [],
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    }
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 10
                  },
                  "end": {
                    "line": 3,
                    "col": 23
                  },
                  "file": 99
                }
              }
            },
            "args": [
              {
                "Var": {
                  "value": "foo",
                  "decl": {
                    "start": {
                      "line": 3,
                      "col": 3
                    },
                    "end": {
                      "line": 3,
                      "col": 6
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 24
                    },
                    "end": {
                      "line": 3,
                      "col": 27
                    },
                    "file": 99
                  }
                }
              }
            ],
            "ty": {
              "Con": {
                "id": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 3,
                "col": 23
              },
              "end": {
                "line": 3,
                "col": 27
              },
              "file": 99
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 4,
        "col": 1
      },
      "file": 99
    }
  }
}
