Bidirectional inference for closure params

SOURCE:
{
  struct Foo { a: Int }

  fn bar<T, Y>(start: T, f: fn (x: T) -> Y) -> Y {
    f(start)
  }

  bar(Foo { a: 1 }, |x| x.a)
}

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "a",
                "ann": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 23
            }
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "bar",
            "generics": [
              "T",
              "Y"
            ],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "start",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 15
                      },
                      "end": {
                        "line": 4,
                        "col": 20
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "f",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 25
                      },
                      "end": {
                        "line": 4,
                        "col": 26
                      }
                    }
                  }
                },
                "ann": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "Y",
                        "args": []
                      }
                    }
                  }
                },
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Y",
                        "args": []
                      }
                    },
                    "fx": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Y",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "Y",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "f",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 4,
                                "col": 25
                              },
                              "end": {
                                "line": 4,
                                "col": 26
                              }
                            }
                          },
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "Y",
                                  "args": []
                                }
                              },
                              "fx": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 4
                            },
                            "end": {
                              "line": 5,
                              "col": 5
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "start",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 4,
                                  "col": 15
                                },
                                "end": {
                                  "line": 4,
                                  "col": 20
                                }
                              }
                            },
                            "ty": {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 6
                              },
                              "end": {
                                "line": 5,
                                "col": 11
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Y",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 4
                        },
                        "end": {
                          "line": 5,
                          "col": 12
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 49
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                },
                {
                  "Fun": {
                    "args": [
                      {
                        "Var": 99
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Var": 99
                    },
                    "fx": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              },
              "fx": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 3
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "bar",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 2
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  }
                }
              },
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "Foo",
                        "args": []
                      }
                    },
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "Foo",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        },
                        "fx": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "fx": []
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 2
                },
                "end": {
                  "line": 8,
                  "col": 5
                }
              }
            }
          },
          "args": [
            {
              "StructCall": {
                "name": "Foo",
                "fields": [
                  {
                    "name": "a",
                    "value": {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 8,
                            "col": 15
                          },
                          "end": {
                            "line": 8,
                            "col": 16
                          }
                        }
                      }
                    }
                  }
                ],
                "rest": null,
                "ty": {
                  "Con": {
                    "name": "Foo",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 6
                  },
                  "end": {
                    "line": 8,
                    "col": 18
                  }
                }
              }
            },
            {
              "Closure": {
                "fun": {
                  "name": "__anonymous",
                  "generics": [],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 21
                            },
                            "end": {
                              "line": 8,
                              "col": 22
                            }
                          }
                        }
                      },
                      "ann": "Unknown",
                      "ty": {
                        "Con": {
                          "name": "Foo",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "ann": "Unknown",
                  "body": {
                    "StructAccess": {
                      "expr": {
                        "Var": {
                          "value": "x",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 8,
                                "col": 21
                              },
                              "end": {
                                "line": 8,
                                "col": 22
                              }
                            }
                          },
                          "ty": {
                            "Con": {
                              "name": "Foo",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 24
                            },
                            "end": {
                              "line": 8,
                              "col": 25
                            }
                          }
                        }
                      },
                      "field": "a",
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 8,
                          "col": 24
                        },
                        "end": {
                          "line": 8,
                          "col": 27
                        }
                      }
                    }
                  }
                },
                "kind": "Lambda",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "Foo",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "fx": []
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 20
                  },
                  "end": {
                    "line": 8,
                    "col": 27
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 28
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 1
      }
    }
  }
}
