Bidirectional inference for closure params

SOURCE:
{
  struct Foo { a: int }

  fn bar<T, Y>(start: T, f: fn (x: T) -> Y) -> Y {
    f(start)
  }

  bar(Foo { a: 1 }, |x| x.a)
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "a",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 23
            },
            "file": 99
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "bar",
            "generics": [
              {
                "name": "T",
                "bounds": [],
                "span": {
                  "start": {
                    "line": 4,
                    "col": 10
                  },
                  "end": {
                    "line": 4,
                    "col": 11
                  },
                  "file": 99
                }
              },
              {
                "name": "Y",
                "bounds": [],
                "span": {
                  "start": {
                    "line": 4,
                    "col": 13
                  },
                  "end": {
                    "line": 4,
                    "col": 14
                  },
                  "file": 99
                }
              }
            ],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "start",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 16
                      },
                      "end": {
                        "line": 4,
                        "col": 21
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "T",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "f",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 26
                      },
                      "end": {
                        "line": 4,
                        "col": 27
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "Y",
                        "args": []
                      }
                    }
                  }
                },
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "T",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "Y",
                        "args": []
                      }
                    }
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "Y",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "Y",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "f",
                          "decl": {
                            "start": {
                              "line": 4,
                              "col": 26
                            },
                            "end": {
                              "line": 4,
                              "col": 27
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "T",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "Y",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 5
                            },
                            "end": {
                              "line": 5,
                              "col": 6
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "start",
                            "decl": {
                              "start": {
                                "line": 4,
                                "col": 16
                              },
                              "end": {
                                "line": 4,
                                "col": 21
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "id": "T",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 7
                              },
                              "end": {
                                "line": 5,
                                "col": 12
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "Y",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 6
                        },
                        "end": {
                          "line": 5,
                          "col": 12
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "Y",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 50
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [
                "T",
                "Y"
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "T",
                        "args": []
                      }
                    },
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "id": "T",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "id": "Y",
                            "args": []
                          }
                        }
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "Y",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                },
                {
                  "Fun": {
                    "args": [
                      {
                        "Var": 99
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Var": 99
                    }
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              }
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 6,
              "col": 3
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "bar",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 3
                },
                "end": {
                  "line": 6,
                  "col": 3
                },
                "file": 99
              },
              "generics_instantiated": [
                {
                  "Con": {
                    "id": "Foo",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Foo",
                        "args": []
                      }
                    },
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "id": "Foo",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 3
                },
                "end": {
                  "line": 8,
                  "col": 6
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "StructCall": {
                "name": "Foo",
                "fields": [
                  {
                    "name": "a",
                    "value": {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 8,
                            "col": 16
                          },
                          "end": {
                            "line": 8,
                            "col": 17
                          },
                          "file": 99
                        }
                      }
                    }
                  }
                ],
                "rest": null,
                "ty": {
                  "Con": {
                    "id": "Foo",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 11
                  },
                  "end": {
                    "line": 8,
                    "col": 18
                  },
                  "file": 99
                }
              }
            },
            {
              "Closure": {
                "fun": {
                  "name": "__anonymous",
                  "generics": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 22
                            },
                            "end": {
                              "line": 8,
                              "col": 23
                            },
                            "file": 99
                          }
                        }
                      },
                      "ann": "Unknown",
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "ann": "Unknown",
                  "body": {
                    "FieldAccess": {
                      "expr": {
                        "Var": {
                          "value": "x",
                          "decl": {
                            "start": {
                              "line": 8,
                              "col": 22
                            },
                            "end": {
                              "line": 8,
                              "col": 23
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Con": {
                              "id": "Foo",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 25
                            },
                            "end": {
                              "line": 8,
                              "col": 26
                            },
                            "file": 99
                          }
                        }
                      },
                      "field": "a",
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 8,
                          "col": 27
                        },
                        "end": {
                          "line": 8,
                          "col": 28
                        },
                        "file": 99
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Var": 99
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Var": 99
                        }
                      }
                    }
                  }
                },
                "kind": "Lambda",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 21
                  },
                  "end": {
                    "line": 8,
                    "col": 28
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 6
            },
            "end": {
              "line": 8,
              "col": 28
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 9,
        "col": 1
      },
      "file": 99
    }
  }
}
