Block ends with list

SOURCE:
{ fn foo() -> List<Int> { [1] } }

OUTPUT:
fn () -> List<Int>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "List",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "List",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Literal": {
                      "lit": {
                        "List": [
                          {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "Int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 27
                                },
                                "end": {
                                  "line": 1,
                                  "col": 28
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "List",
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 26
                        },
                        "end": {
                          "line": 1,
                          "col": 29
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "List",
                    "args": [
                      {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 24
                  },
                  "end": {
                    "line": 1,
                    "col": 31
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "List",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "fx": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 31
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "List",
            "args": [
              {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              }
            ]
          }
        },
        "fx": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 33
      }
    }
  }
}
