Block ends with generic list

SOURCE:
{ fn foo<Y>(foo: Y) -> [Y] { [foo, foo] } }

OUTPUT:
fn <A>(A) -> [A]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [
              "Y"
            ],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "foo",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 12
                      },
                      "end": {
                        "line": 1,
                        "col": 15
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "Y",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "Y",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Literal": {
                      "lit": {
                        "Slice": [
                          {
                            "Var": {
                              "value": "foo",
                              "decl": {
                                "file_id": {
                                  "package": "dummy",
                                  "filename": "dummy"
                                },
                                "span": {
                                  "start": {
                                    "line": 1,
                                    "col": 12
                                  },
                                  "end": {
                                    "line": 1,
                                    "col": 15
                                  }
                                }
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "name": "Y",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 30
                                },
                                "end": {
                                  "line": 1,
                                  "col": 33
                                }
                              }
                            }
                          },
                          {
                            "Var": {
                              "value": "foo",
                              "decl": {
                                "file_id": {
                                  "package": "dummy",
                                  "filename": "dummy"
                                },
                                "span": {
                                  "start": {
                                    "line": 1,
                                    "col": 12
                                  },
                                  "end": {
                                    "line": 1,
                                    "col": 15
                                  }
                                }
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "name": "Y",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 35
                                },
                                "end": {
                                  "line": 1,
                                  "col": 38
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "Slice",
                          "args": [
                            {
                              "Con": {
                                "name": "Y",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 29
                        },
                        "end": {
                          "line": 1,
                          "col": 39
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Slice",
                    "args": [
                      {
                        "Con": {
                          "name": "Y",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 27
                  },
                  "end": {
                    "line": 1,
                    "col": 41
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [
                "Y"
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "Y",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "Y",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Slice",
                  "args": [
                    {
                      "Var": 99
                    }
                  ]
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 41
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Var": 99
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Slice",
            "args": [
              {
                "Var": 99
              }
            ]
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 43
      }
    }
  }
}
