Block ends with function 4

SOURCE:
{ fn foo<T>(foo: T, bar: bool) -> T { foo } }

OUTPUT:
fn <A>(A, bool) -> A
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [
              "T"
            ],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "foo",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 12
                      },
                      "end": {
                        "line": 1,
                        "col": 15
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "bar",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 20
                      },
                      "end": {
                        "line": 1,
                        "col": 23
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "bool",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "bool",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 1,
                            "col": 12
                          },
                          "end": {
                            "line": 1,
                            "col": 15
                          }
                        }
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 38
                        },
                        "end": {
                          "line": 1,
                          "col": 41
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 36
                  },
                  "end": {
                    "line": 1,
                    "col": 43
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [
                "T"
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "bool",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "T",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                },
                {
                  "Con": {
                    "name": "bool",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 43
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Var": 99
          },
          {
            "Con": {
              "name": "bool",
              "args": []
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Var": 99
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 45
      }
    }
  }
}
