Blocks get the type of the last expression.

SOURCE:
{ fn foo() {} }

OUTPUT:
fn () -> ()
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [],
            "ret": {
              "Con": {
                "id": "Unit",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "Unit",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [],
                "ty": {
                  "Con": {
                    "id": "Unit",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 12
                  },
                  "end": {
                    "line": 1,
                    "col": 13
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "Unit",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 13
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 15
      },
      "file": 99
    }
  }
}
