Block ends with function 2

SOURCE:
{ fn foo(foo: int) -> int { foo } }

OUTPUT:
fn (int) -> int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "foo",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 9
                      },
                      "end": {
                        "line": 1,
                        "col": 12
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 1,
                            "col": 9
                          },
                          "end": {
                            "line": 1,
                            "col": 12
                          }
                        }
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 28
                        },
                        "end": {
                          "line": 1,
                          "col": 31
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 26
                  },
                  "end": {
                    "line": 1,
                    "col": 33
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 33
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Con": {
              "name": "int",
              "args": []
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 35
      }
    }
  }
}
