Block ends with function 3

SOURCE:
{ fn foo(bar: int, baz: bool) -> int { bar } }

OUTPUT:
fn (int, bool) -> int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "bar",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 10
                      },
                      "end": {
                        "line": 1,
                        "col": 13
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "baz",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 20
                      },
                      "end": {
                        "line": 1,
                        "col": 23
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "bool",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "bool",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "bar",
                      "decl": {
                        "start": {
                          "line": 1,
                          "col": 10
                        },
                        "end": {
                          "line": 1,
                          "col": 13
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 40
                        },
                        "end": {
                          "line": 1,
                          "col": 43
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 38
                  },
                  "end": {
                    "line": 1,
                    "col": 44
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "bool",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "bool",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 44
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          {
            "Con": {
              "id": "bool",
              "args": []
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 46
      },
      "file": 99
    }
  }
}
