Block ends with function 4

SOURCE:
{ fn foo<T>(bar: T, baz: bool) -> T { bar } }

OUTPUT:
fn <A>(A, bool) -> A
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [
              {
                "name": "T",
                "bounds": [],
                "span": {
                  "start": {
                    "line": 1,
                    "col": 10
                  },
                  "end": {
                    "line": 1,
                    "col": 11
                  },
                  "file": 99
                }
              }
            ],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "bar",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 13
                      },
                      "end": {
                        "line": 1,
                        "col": 16
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "T",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "baz",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 1,
                        "col": 21
                      },
                      "end": {
                        "line": 1,
                        "col": 24
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "bool",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "bool",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "T",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "bar",
                      "decl": {
                        "start": {
                          "line": 1,
                          "col": 13
                        },
                        "end": {
                          "line": 1,
                          "col": 16
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "T",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 39
                        },
                        "end": {
                          "line": 1,
                          "col": 42
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "T",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 37
                  },
                  "end": {
                    "line": 1,
                    "col": 43
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [
                "T"
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "T",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "bool",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "T",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                },
                {
                  "Con": {
                    "id": "bool",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              }
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 43
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Var": 99
          },
          {
            "Con": {
              "id": "bool",
              "args": []
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Var": 99
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 45
      },
      "file": 99
    }
  }
}
