Block ends with list

SOURCE:
{ fn foo() -> [int] { [1] } }

OUTPUT:
fn () -> [int]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Literal": {
                      "lit": {
                        "Slice": [
                          {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 23
                                },
                                "end": {
                                  "line": 1,
                                  "col": 24
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "Slice",
                          "args": [
                            {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 22
                        },
                        "end": {
                          "line": 1,
                          "col": 25
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Slice",
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 20
                  },
                  "end": {
                    "line": 1,
                    "col": 27
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Slice",
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 27
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Slice",
            "args": [
              {
                "Con": {
                  "name": "int",
                  "args": []
                }
              }
            ]
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 29
      }
    }
  }
}
