boolean operators

SOURCE:
{ (1 == 2) && (false || true) }

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Binary": {
          "op": "And",
          "left": {
            "Paren": {
              "expr": {
                "Binary": {
                  "op": "Eq",
                  "left": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 4
                        },
                        "end": {
                          "line": 1,
                          "col": 5
                        },
                        "file": 99
                      }
                    }
                  },
                  "right": {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 9
                        },
                        "end": {
                          "line": 1,
                          "col": 10
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 4
                    },
                    "end": {
                      "line": 1,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              "ty": {
                "Con": {
                  "id": "bool",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 3
                },
                "end": {
                  "line": 1,
                  "col": 10
                },
                "file": 99
              }
            }
          },
          "right": {
            "Paren": {
              "expr": {
                "Binary": {
                  "op": "Or",
                  "left": {
                    "Literal": {
                      "lit": {
                        "Bool": false
                      },
                      "ty": {
                        "Con": {
                          "id": "bool",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 16
                        },
                        "end": {
                          "line": 1,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  },
                  "right": {
                    "Literal": {
                      "lit": {
                        "Bool": true
                      },
                      "ty": {
                        "Con": {
                          "id": "bool",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 25
                        },
                        "end": {
                          "line": 1,
                          "col": 29
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 16
                    },
                    "end": {
                      "line": 1,
                      "col": 29
                    },
                    "file": 99
                  }
                }
              },
              "ty": {
                "Con": {
                  "id": "bool",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 15
                },
                "end": {
                  "line": 1,
                  "col": 29
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 29
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 31
      },
      "file": 99
    }
  }
}
