Can use different generic name than declaration.

SOURCE:
{
  struct Foo<T> {}

  impl<Y> Foo<Y> {
    fn bar<X>(x: X, y: Y) {}
  }

  2
}

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [
              "T"
            ],
            "fields": []
          },
          "is_trait": false,
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 18
            }
          }
        }
      },
      {
        "ImplBlock": {
          "ann": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                }
              ]
            }
          },
          "items": [
            {
              "Closure": {
                "fun": {
                  "name": "Foo::bar",
                  "generics": [
                    "X",
                    "Y"
                  ],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 14
                            },
                            "end": {
                              "line": 5,
                              "col": 15
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "X",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "X",
                          "args": []
                        }
                      }
                    },
                    {
                      "pat": {
                        "Type": {
                          "ident": "y",
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 20
                            },
                            "end": {
                              "line": 5,
                              "col": 21
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "Y",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Y",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [],
                      "ty": {
                        "Con": {
                          "name": "Unit",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 26
                        },
                        "end": {
                          "line": 5,
                          "col": 28
                        }
                      }
                    }
                  }
                },
                "kind": "TopLevel",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Var": 99
                      },
                      {
                        "Var": 99
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "fx": []
                  }
                },
                "span": {
                  "start": {
                    "line": 5,
                    "col": 4
                  },
                  "end": {
                    "line": 5,
                    "col": 28
                  }
                }
              }
            }
          ],
          "generics": [
            "Y"
          ],
          "span": {
            "start": {
              "line": 4,
              "col": 10
            },
            "end": {
              "line": 4,
              "col": 16
            }
          }
        }
      },
      {
        "Literal": {
          "lit": {
            "Int": 2
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 1
      }
    }
  }
}
