Closures can be inferred.

SOURCE:
|n| sum(n, 1)

OUTPUT:
fn (int) -> int
---
No errors.
---
{
  "Closure": {
    "fun": {
      "name": "__anonymous",
      "generics": [],
      "args": [
        {
          "pat": {
            "Type": {
              "ident": "n",
              "is_mut": false,
              "ann": "Unknown",
              "span": {
                "start": {
                  "line": 1,
                  "col": 1
                },
                "end": {
                  "line": 1,
                  "col": 2
                },
                "file": 99
              }
            }
          },
          "ann": "Unknown",
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        }
      ],
      "ret": {
        "Con": {
          "id": "int",
          "args": []
        }
      },
      "ann": "Unknown",
      "body": {
        "Call": {
          "func": {
            "Var": {
              "value": "sum",
              "decl": {
                "start": {
                  "line": 21,
                  "col": 0
                },
                "end": {
                  "line": 23,
                  "col": 1
                },
                "file": -1
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 4
                },
                "end": {
                  "line": 1,
                  "col": 7
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Var": {
                "value": "n",
                "decl": {
                  "start": {
                    "line": 1,
                    "col": 1
                  },
                  "end": {
                    "line": 1,
                    "col": 2
                  },
                  "file": 99
                },
                "generics_instantiated": [],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 8
                  },
                  "end": {
                    "line": 1,
                    "col": 9
                  },
                  "file": 99
                }
              }
            },
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 11
                  },
                  "end": {
                    "line": 1,
                    "col": 12
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 4
            },
            "end": {
              "line": 1,
              "col": 13
            },
            "file": 99
          }
        }
      },
      "bounded_ty": {
        "generics": [],
        "ty": {
          "Fun": {
            "args": [
              {
                "Var": 99
              }
            ],
            "bounds": [],
            "ret": {
              "Var": 99
            }
          }
        }
      }
    },
    "kind": "Lambda",
    "ty": {
      "Fun": {
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 13
      },
      "file": 99
    }
  }
}
