Enums with generics should get instantiated.

SOURCE:
{
  enum Maybe<T> { Just(T), None }
  Maybe::Just(1)
}

OUTPUT:
Maybe<Int>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Maybe",
            "generics": [
              "T"
            ],
            "cons": [
              {
                "name": "Just",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    }
                  }
                ]
              },
              {
                "name": "None",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 33
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "Maybe::Just",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 2
                  },
                  "end": {
                    "line": 2,
                    "col": 33
                  }
                }
              },
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "fx": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 13
                }
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 14
                  },
                  "end": {
                    "line": 3,
                    "col": 15
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 16
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Maybe",
        "args": [
          {
            "Con": {
              "name": "Int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      }
    }
  }
}
