Enums from functions II.

SOURCE:
{
  enum Maybe<T> { Just(T), None }

  fn foo(b: Int) -> Maybe<Int> {
    Maybe::None
  }

  foo(1) as Maybe<Int>;

  fn bar(b: Int) -> Maybe<Int> {
    Maybe::Just(b)
  }

  match foo(2) as Maybe<Int> {
    Maybe::Just(x) => x,
    Maybe::None => 3,
  }
}

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Maybe",
            "generics": [
              "T"
            ],
            "cons": [
              {
                "name": "Just",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    }
                  }
                ]
              },
              {
                "name": "None",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 33
            }
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "b",
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 9
                      },
                      "end": {
                        "line": 4,
                        "col": 10
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Maybe",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Maybe",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "Maybe::None",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 2
                          },
                          "end": {
                            "line": 2,
                            "col": 33
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 4
                        },
                        "end": {
                          "line": 5,
                          "col": 15
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Maybe",
                    "args": [
                      {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 31
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "fx": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 3
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "foo",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 2
                      },
                      "end": {
                        "line": 6,
                        "col": 3
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 8,
                      "col": 2
                    },
                    "end": {
                      "line": 8,
                      "col": 5
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "Int": 1
                    },
                    "ty": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 8,
                        "col": 6
                      },
                      "end": {
                        "line": 8,
                        "col": 7
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 2
                },
                "end": {
                  "line": 8,
                  "col": 8
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 22
            }
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "bar",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "b",
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 10,
                        "col": 9
                      },
                      "end": {
                        "line": 10,
                        "col": 10
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "Maybe",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Maybe",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "Maybe::Just",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 2
                              },
                              "end": {
                                "line": 2,
                                "col": 33
                              }
                            }
                          },
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "Int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "Maybe",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "Int",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "fx": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 11,
                              "col": 4
                            },
                            "end": {
                              "line": 11,
                              "col": 15
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "b",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 10,
                                  "col": 9
                                },
                                "end": {
                                  "line": 10,
                                  "col": 10
                                }
                              }
                            },
                            "ty": {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 11,
                                "col": 16
                              },
                              "end": {
                                "line": 11,
                                "col": 17
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 11,
                          "col": 4
                        },
                        "end": {
                          "line": 11,
                          "col": 18
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Maybe",
                    "args": [
                      {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 10,
                    "col": 31
                  },
                  "end": {
                    "line": 12,
                    "col": 3
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "fx": []
            }
          },
          "span": {
            "start": {
              "line": 10,
              "col": 2
            },
            "end": {
              "line": 12,
              "col": 3
            }
          }
        }
      },
      {
        "Match": {
          "subject": {
            "CheckType": {
              "expr": {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "foo",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 4,
                            "col": 2
                          },
                          "end": {
                            "line": 6,
                            "col": 3
                          }
                        }
                      },
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "Maybe",
                              "args": [
                                {
                                  "Con": {
                                    "name": "Int",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "fx": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 14,
                          "col": 8
                        },
                        "end": {
                          "line": 14,
                          "col": 11
                        }
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 2
                        },
                        "ty": {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 14,
                            "col": 12
                          },
                          "end": {
                            "line": 14,
                            "col": 13
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 14,
                      "col": 8
                    },
                    "end": {
                      "line": 14,
                      "col": 14
                    }
                  }
                }
              },
              "ann": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 14,
                  "col": 8
                },
                "end": {
                  "line": 14,
                  "col": 28
                }
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe::Just",
                  "elems": [
                    {
                      "Type": {
                        "ident": "x",
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 15,
                            "col": 16
                          },
                          "end": {
                            "line": 15,
                            "col": 17
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 15,
                      "col": 4
                    },
                    "end": {
                      "line": 15,
                      "col": 18
                    }
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 15,
                        "col": 16
                      },
                      "end": {
                        "line": 15,
                        "col": 17
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 15,
                      "col": 22
                    },
                    "end": {
                      "line": 15,
                      "col": 23
                    }
                  }
                }
              }
            },
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe::None",
                  "elems": [],
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 16,
                      "col": 4
                    },
                    "end": {
                      "line": 16,
                      "col": 15
                    }
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Int": 3
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 16,
                      "col": 19
                    },
                    "end": {
                      "line": 16,
                      "col": 20
                    }
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 14,
              "col": 2
            },
            "end": {
              "line": 17,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 18,
        "col": 1
      }
    }
  }
}
