Enum variants get instantiated correctly.

SOURCE:
{
  enum Maybe<T> { Just(T), None }

  Maybe::Just(1) as Maybe<Int>;
  Maybe::Just("foo") as Maybe<String>;
  Maybe::None as Maybe<Bool>;
  Maybe::Just(Maybe::Just(1)) as Maybe<Maybe<Int>>;

  Maybe::None
}

OUTPUT:
Maybe<A>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Maybe",
            "generics": [
              "T"
            ],
            "cons": [
              {
                "name": "Just",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    }
                  }
                ]
              },
              {
                "name": "None",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 33
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Maybe::Just",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 2
                      },
                      "end": {
                        "line": 2,
                        "col": 33
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 2
                    },
                    "end": {
                      "line": 4,
                      "col": 13
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "Int": 1
                    },
                    "ty": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 14
                      },
                      "end": {
                        "line": 4,
                        "col": 15
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 2
                },
                "end": {
                  "line": 4,
                  "col": 16
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 30
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Maybe::Just",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 2
                      },
                      "end": {
                        "line": 2,
                        "col": 33
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "String",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 2
                    },
                    "end": {
                      "line": 5,
                      "col": 13
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "String": "foo"
                    },
                    "ty": {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 5,
                        "col": 14
                      },
                      "end": {
                        "line": 5,
                        "col": 19
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 2
                },
                "end": {
                  "line": 5,
                  "col": 20
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 37
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "Maybe::None",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 2
                  },
                  "end": {
                    "line": 2,
                    "col": 33
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Bool",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 2
                },
                "end": {
                  "line": 6,
                  "col": 13
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Bool",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Bool",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 28
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Maybe::Just",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 2
                      },
                      "end": {
                        "line": 2,
                        "col": 33
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Maybe",
                            "args": [
                              {
                                "Con": {
                                  "name": "Int",
                                  "args": []
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Maybe",
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Int",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 2
                    },
                    "end": {
                      "line": 7,
                      "col": 13
                    }
                  }
                }
              },
              "args": [
                {
                  "Call": {
                    "func": {
                      "Var": {
                        "value": "Maybe::Just",
                        "decl": {
                          "file_id": {
                            "package": "dummy",
                            "filename": "dummy"
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 2
                            },
                            "end": {
                              "line": 2,
                              "col": 33
                            }
                          }
                        },
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "name": "Int",
                                  "args": []
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "name": "Maybe",
                                "args": [
                                  {
                                    "Con": {
                                      "name": "Int",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            },
                            "fx": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 7,
                            "col": 14
                          },
                          "end": {
                            "line": 7,
                            "col": 25
                          }
                        }
                      }
                    },
                    "args": [
                      {
                        "Literal": {
                          "lit": {
                            "Int": 1
                          },
                          "ty": {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 7,
                              "col": 26
                            },
                            "end": {
                              "line": 7,
                              "col": 27
                            }
                          }
                        }
                      }
                    ],
                    "ty": {
                      "Con": {
                        "name": "Maybe",
                        "args": [
                          {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    "span": {
                      "start": {
                        "line": 7,
                        "col": 14
                      },
                      "end": {
                        "line": 7,
                        "col": 28
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Maybe",
                        "args": [
                          {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 7,
                  "col": 2
                },
                "end": {
                  "line": 7,
                  "col": 29
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Maybe",
                    "args": [
                      {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Maybe",
                    "args": [
                      {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 7,
              "col": 2
            },
            "end": {
              "line": 7,
              "col": 50
            }
          }
        }
      },
      {
        "Var": {
          "value": "Maybe::None",
          "decl": {
            "file_id": {
              "package": "dummy",
              "filename": "dummy"
            },
            "span": {
              "start": {
                "line": 2,
                "col": 2
              },
              "end": {
                "line": 2,
                "col": 33
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Var": 99
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 9,
              "col": 2
            },
            "end": {
              "line": 9,
              "col": 13
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Maybe",
        "args": [
          {
            "Var": 99
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 10,
        "col": 1
      }
    }
  }
}
