Equality

SOURCE:
{
  let a = 1
  let b = 2
  a == b
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 7
                  },
                  "end": {
                    "line": 2,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 11
                },
                "end": {
                  "line": 2,
                  "col": 12
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 12
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "b",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 3,
                    "col": 7
                  },
                  "end": {
                    "line": 3,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Int": 2
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 11
                },
                "end": {
                  "line": 3,
                  "col": 12
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 3
            },
            "end": {
              "line": 3,
              "col": 12
            },
            "file": 99
          }
        }
      },
      {
        "Binary": {
          "op": "Eq",
          "left": {
            "Var": {
              "value": "a",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 7
                },
                "end": {
                  "line": 2,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 3
                },
                "end": {
                  "line": 4,
                  "col": 4
                },
                "file": 99
              }
            }
          },
          "right": {
            "Var": {
              "value": "b",
              "decl": {
                "start": {
                  "line": 3,
                  "col": 7
                },
                "end": {
                  "line": 3,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 8
                },
                "end": {
                  "line": 4,
                  "col": 9
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 4,
              "col": 9
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 5,
        "col": 1
      },
      "file": 99
    }
  }
}
