Function call with no arguments.

SOURCE:
{ hello() }

OUTPUT:
string
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Call": {
          "func": {
            "Var": {
              "value": "hello",
              "decl": {
                "start": {
                  "line": 19,
                  "col": 0
                },
                "end": {
                  "line": 19,
                  "col": 28
                },
                "file": -1
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 2
                },
                "end": {
                  "line": 1,
                  "col": 7
                },
                "file": 99
              }
            }
          },
          "args": [],
          "ty": {
            "Con": {
              "id": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 9
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 11
      },
      "file": 99
    }
  }
}
