Functions are in scope after declaration.

SOURCE:
{
  fn foo(a: int) -> int { sum(a, 4) }
  foo(1)
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "a",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 10
                      },
                      "end": {
                        "line": 2,
                        "col": 11
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "sum",
                          "decl": {
                            "start": {
                              "line": 21,
                              "col": 1
                            },
                            "end": {
                              "line": 23,
                              "col": 1
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 27
                            },
                            "end": {
                              "line": 2,
                              "col": 30
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "a",
                            "decl": {
                              "start": {
                                "line": 2,
                                "col": 10
                              },
                              "end": {
                                "line": 2,
                                "col": 11
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 31
                              },
                              "end": {
                                "line": 2,
                                "col": 32
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 4
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 34
                              },
                              "end": {
                                "line": 2,
                                "col": 35
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 30
                        },
                        "end": {
                          "line": 2,
                          "col": 35
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 25
                  },
                  "end": {
                    "line": 2,
                    "col": 37
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 37
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 3
                },
                "end": {
                  "line": 2,
                  "col": 37
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 3
                },
                "end": {
                  "line": 3,
                  "col": 6
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 7
                  },
                  "end": {
                    "line": 3,
                    "col": 8
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 6
            },
            "end": {
              "line": 3,
              "col": 8
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 4,
        "col": 1
      },
      "file": 99
    }
  }
}
