Functions can take mutable params

SOURCE:
{
  fn foo (mut a: int) -> int {
    a = a + 1;
    a
  }

  foo(1)
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "a",
                    "is_mut": true,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 10
                      },
                      "end": {
                        "line": 2,
                        "col": 15
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "VarUpdate": {
                      "target": {
                        "Var": {
                          "value": "a",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 10
                              },
                              "end": {
                                "line": 2,
                                "col": 15
                              }
                            }
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 4
                            },
                            "end": {
                              "line": 3,
                              "col": 5
                            }
                          }
                        }
                      },
                      "value": {
                        "Binary": {
                          "op": "Add",
                          "left": {
                            "Var": {
                              "value": "a",
                              "decl": {
                                "file_id": {
                                  "package": "dummy",
                                  "filename": "dummy"
                                },
                                "span": {
                                  "start": {
                                    "line": 2,
                                    "col": 10
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 15
                                  }
                                }
                              },
                              "generics_instantiated": [],
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 8
                                },
                                "end": {
                                  "line": 3,
                                  "col": 9
                                }
                              }
                            }
                          },
                          "right": {
                            "Literal": {
                              "lit": {
                                "Int": 1
                              },
                              "ty": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 12
                                },
                                "end": {
                                  "line": 3,
                                  "col": 13
                                }
                              }
                            }
                          },
                          "ty": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 8
                            },
                            "end": {
                              "line": 3,
                              "col": 13
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 4
                        },
                        "end": {
                          "line": 3,
                          "col": 13
                        }
                      }
                    }
                  },
                  {
                    "Var": {
                      "value": "a",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 10
                          },
                          "end": {
                            "line": 2,
                            "col": 15
                          }
                        }
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 4
                        },
                        "end": {
                          "line": 4,
                          "col": 5
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 29
                  },
                  "end": {
                    "line": 5,
                    "col": 3
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 3
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 2
                  },
                  "end": {
                    "line": 5,
                    "col": 3
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 7,
                  "col": 2
                },
                "end": {
                  "line": 7,
                  "col": 5
                }
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 7,
                    "col": 6
                  },
                  "end": {
                    "line": 7,
                    "col": 7
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 7,
              "col": 2
            },
            "end": {
              "line": 7,
              "col": 8
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 8,
        "col": 1
      }
    }
  }
}
