Functions with no error get inferred ok.

SOURCE:
{
  list_map([1,2,3], |x| sum(x, 1))
}

OUTPUT:
[int]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Call": {
          "func": {
            "Var": {
              "value": "list_map",
              "decl": {
                "file_id": {
                  "package": "std",
                  "filename": "builtin.brg"
                },
                "span": {
                  "start": {
                    "line": 0,
                    "col": 0
                  },
                  "end": {
                    "line": 0,
                    "col": 0
                  }
                }
              },
              "generics_instantiated": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "Slice",
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 2
                },
                "end": {
                  "line": 2,
                  "col": 10
                }
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Slice": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 12
                          },
                          "end": {
                            "line": 2,
                            "col": 13
                          }
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "Int": 2
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 14
                          },
                          "end": {
                            "line": 2,
                            "col": 15
                          }
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "Int": 3
                        },
                        "ty": {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 16
                          },
                          "end": {
                            "line": 2,
                            "col": 17
                          }
                        }
                      }
                    }
                  ]
                },
                "ty": {
                  "Con": {
                    "name": "Slice",
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 11
                  },
                  "end": {
                    "line": 2,
                    "col": 18
                  }
                }
              }
            },
            {
              "Closure": {
                "fun": {
                  "name": "__anonymous",
                  "generics": [],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 21
                            },
                            "end": {
                              "line": 2,
                              "col": 22
                            }
                          }
                        }
                      },
                      "ann": "Unknown",
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "ann": "Unknown",
                  "body": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "sum",
                          "decl": {
                            "file_id": {
                              "package": "std",
                              "filename": "builtin.brg"
                            },
                            "span": {
                              "start": {
                                "line": 0,
                                "col": 0
                              },
                              "end": {
                                "line": 0,
                                "col": 0
                              }
                            }
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 24
                            },
                            "end": {
                              "line": 2,
                              "col": 27
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "x",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 21
                                },
                                "end": {
                                  "line": 2,
                                  "col": 22
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 28
                              },
                              "end": {
                                "line": 2,
                                "col": 29
                              }
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 31
                              },
                              "end": {
                                "line": 2,
                                "col": 32
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 24
                        },
                        "end": {
                          "line": 2,
                          "col": 33
                        }
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Var": 99
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Var": 99
                        },
                        "id": -1
                      }
                    }
                  }
                },
                "kind": "Lambda",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 20
                  },
                  "end": {
                    "line": 2,
                    "col": 33
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Slice",
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 34
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Slice",
        "args": [
          {
            "Con": {
              "name": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 3,
        "col": 1
      }
    }
  }
}
