Functions should get inferred correctly.

SOURCE:
list_map

OUTPUT:
fn <A, B>([A], fn (A) -> B) -> [B]
---
No errors.
---
{
  "Var": {
    "value": "list_map",
    "decl": {
      "file_id": {
        "package": "std",
        "filename": "builtin.brg"
      },
      "span": {
        "start": {
          "line": 0,
          "col": 0
        },
        "end": {
          "line": 0,
          "col": 0
        }
      }
    },
    "generics_instantiated": [
      {
        "Var": 99
      },
      {
        "Var": 99
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Con": {
              "name": "Slice",
              "args": [
                {
                  "Var": 99
                }
              ]
            }
          },
          {
            "Fun": {
              "args": [
                {
                  "Var": 99
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              },
              "id": -1
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Slice",
            "args": [
              {
                "Var": 99
              }
            ]
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 8
      }
    }
  }
}
