Functions should get inferred correctly.

SOURCE:
list_map

OUTPUT:
fn <A, B>([A], fn (A) -> B) -> [B]
---
No errors.
---
{
  "Var": {
    "value": "list_map",
    "decl": {
      "start": {
        "line": 28,
        "col": 1
      },
      "end": {
        "line": 30,
        "col": 1
      },
      "file": 99
    },
    "generics_instantiated": [
      {
        "Var": 99
      },
      {
        "Var": 99
      }
    ],
    "ty": {
      "Fun": {
        "args": [
          {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Var": 99
                }
              ]
            }
          },
          {
            "Fun": {
              "args": [
                {
                  "Var": 99
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              }
            }
          }
        ],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "Slice",
            "args": [
              {
                "Var": 99
              }
            ]
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 9
      },
      "file": 99
    }
  }
}
