Functions with no error get inferred ok.

SOURCE:
{
  list_map([1,2,3], |x| sum(x, 1))
}

OUTPUT:
[int]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Call": {
          "func": {
            "Var": {
              "value": "list_map",
              "decl": {
                "start": {
                  "line": 28,
                  "col": 1
                },
                "end": {
                  "line": 30,
                  "col": 1
                },
                "file": 99
              },
              "generics_instantiated": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Slice",
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "Slice",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 3
                },
                "end": {
                  "line": 2,
                  "col": 11
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Slice": [
                    {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 13
                          },
                          "end": {
                            "line": 2,
                            "col": 14
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "Int": 2
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 15
                          },
                          "end": {
                            "line": 2,
                            "col": 16
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "Int": 3
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 17
                          },
                          "end": {
                            "line": 2,
                            "col": 18
                          },
                          "file": 99
                        }
                      }
                    }
                  ]
                },
                "ty": {
                  "Con": {
                    "id": "Slice",
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 12
                  },
                  "end": {
                    "line": 2,
                    "col": 18
                  },
                  "file": 99
                }
              }
            },
            {
              "Closure": {
                "fun": {
                  "name": "__anonymous",
                  "generics": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 22
                            },
                            "end": {
                              "line": 2,
                              "col": 23
                            },
                            "file": 99
                          }
                        }
                      },
                      "ann": "Unknown",
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "ann": "Unknown",
                  "body": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "sum",
                          "decl": {
                            "start": {
                              "line": 21,
                              "col": 1
                            },
                            "end": {
                              "line": 23,
                              "col": 1
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "id": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "id": "int",
                                  "args": []
                                }
                              }
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 25
                            },
                            "end": {
                              "line": 2,
                              "col": 28
                            },
                            "file": 99
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "x",
                            "decl": {
                              "start": {
                                "line": 2,
                                "col": 22
                              },
                              "end": {
                                "line": 2,
                                "col": 23
                              },
                              "file": 99
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 29
                              },
                              "end": {
                                "line": 2,
                                "col": 30
                              },
                              "file": 99
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 32
                              },
                              "end": {
                                "line": 2,
                                "col": 33
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 28
                        },
                        "end": {
                          "line": 2,
                          "col": 33
                        },
                        "file": 99
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Var": 99
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Var": 99
                        }
                      }
                    }
                  }
                },
                "kind": "Lambda",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 21
                  },
                  "end": {
                    "line": 2,
                    "col": 33
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 11
            },
            "end": {
              "line": 2,
              "col": 34
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "Slice",
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 3,
        "col": 1
      },
      "file": 99
    }
  }
}
