Function call with arguments

SOURCE:
{ sum(1, 4) }

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Call": {
          "func": {
            "Var": {
              "value": "sum",
              "decl": {
                "start": {
                  "line": 21,
                  "col": 0
                },
                "end": {
                  "line": 23,
                  "col": 1
                },
                "file": -1
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 2
                },
                "end": {
                  "line": 1,
                  "col": 5
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 6
                  },
                  "end": {
                    "line": 1,
                    "col": 7
                  },
                  "file": 99
                }
              }
            },
            {
              "Literal": {
                "lit": {
                  "Int": 4
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 9
                  },
                  "end": {
                    "line": 1,
                    "col": 10
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 11
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 13
      },
      "file": 99
    }
  }
}
