Functions are in scope after declaration.

SOURCE:
{
  fn foo(a: int) -> int { sum(a, 4) }
  foo(1)
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "a",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 9
                      },
                      "end": {
                        "line": 2,
                        "col": 10
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "sum",
                          "decl": {
                            "file_id": {
                              "package": "std",
                              "filename": "builtin.brg"
                            },
                            "span": {
                              "start": {
                                "line": 0,
                                "col": 0
                              },
                              "end": {
                                "line": 0,
                                "col": 0
                              }
                            }
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 26
                            },
                            "end": {
                              "line": 2,
                              "col": 29
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "a",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 9
                                },
                                "end": {
                                  "line": 2,
                                  "col": 10
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 30
                              },
                              "end": {
                                "line": 2,
                                "col": 31
                              }
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 4
                            },
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 33
                              },
                              "end": {
                                "line": 2,
                                "col": 34
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 26
                        },
                        "end": {
                          "line": 2,
                          "col": 35
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 24
                  },
                  "end": {
                    "line": 2,
                    "col": 37
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 37
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 2
                  },
                  "end": {
                    "line": 2,
                    "col": 37
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 5
                }
              }
            }
          },
          "args": [
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 8
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      }
    }
  }
}
