Function call with no arguments.

SOURCE:
{ hello() }

OUTPUT:
String
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Call": {
          "func": {
            "Var": {
              "value": "hello",
              "decl": {
                "file_id": {
                  "package": "builtin",
                  "filename": ""
                },
                "span": {
                  "start": {
                    "line": 0,
                    "col": 0
                  },
                  "end": {
                    "line": 0,
                    "col": 0
                  }
                }
              },
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "String",
                      "args": []
                    }
                  },
                  "fx": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 2
                },
                "end": {
                  "line": 1,
                  "col": 7
                }
              }
            }
          },
          "args": [],
          "ty": {
            "Con": {
              "name": "String",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 9
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "String",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 11
      }
    }
  }
}
