Generic functions get instantiated at each use site.

SOURCE:
{
  fn constant<T, Y>(a: T, b: Y) -> T { a }

  let x = constant("hello", 5);
  x as string;
  let y = sum(constant(1, false), 5);
  y as int;
  y
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "constant",
            "generics": [
              "T",
              "Y"
            ],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "a",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 20
                      },
                      "end": {
                        "line": 2,
                        "col": 21
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "b",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 26
                      },
                      "end": {
                        "line": 2,
                        "col": 27
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Y",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "T",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "a",
                      "decl": {
                        "file_id": {
                          "package": "dummy",
                          "filename": "dummy"
                        },
                        "span": {
                          "start": {
                            "line": 2,
                            "col": 20
                          },
                          "end": {
                            "line": 2,
                            "col": 21
                          }
                        }
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 39
                        },
                        "end": {
                          "line": 2,
                          "col": 40
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 37
                  },
                  "end": {
                    "line": 2,
                    "col": 42
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [
                "T",
                "Y"
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "Y",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "T",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Var": 99
                },
                {
                  "Var": 99
                }
              ],
              "bounds": [],
              "ret": {
                "Var": 99
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 42
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 4,
                    "col": 6
                  },
                  "end": {
                    "line": 4,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "string",
                "args": []
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "constant",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 2
                      },
                      "end": {
                        "line": 2,
                        "col": 42
                      }
                    }
                  },
                  "generics_instantiated": [
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "id": -1
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 10
                    },
                    "end": {
                      "line": 4,
                      "col": 18
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "String": [
                        "hello",
                        null
                      ]
                    },
                    "ty": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 19
                      },
                      "end": {
                        "line": 4,
                        "col": 26
                      }
                    }
                  }
                },
                {
                  "Literal": {
                    "lit": {
                      "Int": 5
                    },
                    "ty": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 28
                      },
                      "end": {
                        "line": 4,
                        "col": 29
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "string",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 10
                },
                "end": {
                  "line": 4,
                  "col": 30
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 31
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "x",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 6
                  },
                  "end": {
                    "line": 4,
                    "col": 7
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "name": "string",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 2
                },
                "end": {
                  "line": 5,
                  "col": 3
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "string",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 13
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "y",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 6,
                    "col": 6
                  },
                  "end": {
                    "line": 6,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "int",
                "args": []
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "sum",
                  "decl": {
                    "file_id": {
                      "package": "std",
                      "filename": "builtin.brg"
                    },
                    "span": {
                      "start": {
                        "line": 0,
                        "col": 0
                      },
                      "end": {
                        "line": 0,
                        "col": 0
                      }
                    }
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "id": -1
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 10
                    },
                    "end": {
                      "line": 6,
                      "col": 13
                    }
                  }
                }
              },
              "args": [
                {
                  "Call": {
                    "func": {
                      "Var": {
                        "value": "constant",
                        "decl": {
                          "file_id": {
                            "package": "dummy",
                            "filename": "dummy"
                          },
                          "span": {
                            "start": {
                              "line": 2,
                              "col": 2
                            },
                            "end": {
                              "line": 2,
                              "col": 42
                            }
                          }
                        },
                        "generics_instantiated": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "name": "bool",
                              "args": []
                            }
                          }
                        ],
                        "ty": {
                          "Fun": {
                            "args": [
                              {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              },
                              {
                                "Con": {
                                  "name": "bool",
                                  "args": []
                                }
                              }
                            ],
                            "bounds": [],
                            "ret": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "id": -1
                          }
                        },
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 14
                          },
                          "end": {
                            "line": 6,
                            "col": 22
                          }
                        }
                      }
                    },
                    "args": [
                      {
                        "Literal": {
                          "lit": {
                            "Int": 1
                          },
                          "ty": {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 23
                            },
                            "end": {
                              "line": 6,
                              "col": 24
                            }
                          }
                        }
                      },
                      {
                        "Literal": {
                          "lit": {
                            "Bool": false
                          },
                          "ty": {
                            "Con": {
                              "name": "bool",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 26
                            },
                            "end": {
                              "line": 6,
                              "col": 31
                            }
                          }
                        }
                      }
                    ],
                    "ty": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 6,
                        "col": 14
                      },
                      "end": {
                        "line": 6,
                        "col": 32
                      }
                    }
                  }
                },
                {
                  "Literal": {
                    "lit": {
                      "Int": 5
                    },
                    "ty": {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 6,
                        "col": 34
                      },
                      "end": {
                        "line": 6,
                        "col": 35
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 10
                },
                "end": {
                  "line": 6,
                  "col": 36
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 37
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "y",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 6,
                    "col": 6
                  },
                  "end": {
                    "line": 6,
                    "col": 7
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 7,
                  "col": 2
                },
                "end": {
                  "line": 7,
                  "col": 3
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 7,
              "col": 2
            },
            "end": {
              "line": 7,
              "col": 10
            }
          }
        }
      },
      {
        "Var": {
          "value": "y",
          "decl": {
            "file_id": {
              "package": "dummy",
              "filename": "dummy"
            },
            "span": {
              "start": {
                "line": 6,
                "col": 6
              },
              "end": {
                "line": 6,
                "col": 7
              }
            }
          },
          "generics_instantiated": [],
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 1
      }
    }
  }
}
