Generics in impl method

SOURCE:
{
  struct Foo<T> { bar: T }
  impl<T> Foo<T> {
    fn map(self, f: fn (x: T) -> string) -> string {
      f(self.bar)
    }

    fn other(self) -> string {
      self.map(|x| "asdf")
    }
  }

  let foo = Foo { bar: 12 };
  foo.other()
}

OUTPUT:
string
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [
              "T"
            ],
            "fields": [
              {
                "name": "bar",
                "ann": {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "name": "T",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 26
            }
          }
        }
      },
      {
        "ImplBlock": {
          "ann": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                }
              ]
            }
          },
          "items": [
            {
              "Closure": {
                "fun": {
                  "name": "map",
                  "generics": [
                    "T"
                  ],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "self",
                          "is_mut": false,
                          "ann": {
                            "Con": {
                              "name": "Foo",
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 2
                            },
                            "end": {
                              "line": 11,
                              "col": 3
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    },
                    {
                      "pat": {
                        "Type": {
                          "ident": "f",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 17
                            },
                            "end": {
                              "line": 4,
                              "col": 18
                            }
                          }
                        }
                      },
                      "ann": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ],
                          "ret": {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          }
                        }
                      },
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          "id": -1
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "Call": {
                            "func": {
                              "Var": {
                                "value": "f",
                                "decl": {
                                  "file_id": {
                                    "package": "dummy",
                                    "filename": "dummy"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 4,
                                      "col": 17
                                    },
                                    "end": {
                                      "line": 4,
                                      "col": 18
                                    }
                                  }
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Con": {
                                          "name": "T",
                                          "args": []
                                        }
                                      }
                                    ],
                                    "bounds": [],
                                    "ret": {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    },
                                    "id": -1
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 5,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 5,
                                    "col": 7
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "FieldAccess": {
                                  "expr": {
                                    "Var": {
                                      "value": "self",
                                      "decl": {
                                        "file_id": {
                                          "package": "dummy",
                                          "filename": "dummy"
                                        },
                                        "span": {
                                          "start": {
                                            "line": 3,
                                            "col": 2
                                          },
                                          "end": {
                                            "line": 11,
                                            "col": 3
                                          }
                                        }
                                      },
                                      "generics_instantiated": [],
                                      "ty": {
                                        "Con": {
                                          "name": "Foo",
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "T",
                                                "args": []
                                              }
                                            }
                                          ]
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 5,
                                          "col": 8
                                        },
                                        "end": {
                                          "line": 5,
                                          "col": 12
                                        }
                                      }
                                    }
                                  },
                                  "field": "bar",
                                  "ty": {
                                    "Con": {
                                      "name": "T",
                                      "args": []
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 5,
                                      "col": 8
                                    },
                                    "end": {
                                      "line": 5,
                                      "col": 16
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 5,
                                "col": 6
                              },
                              "end": {
                                "line": 5,
                                "col": 17
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 51
                        },
                        "end": {
                          "line": 6,
                          "col": 5
                        }
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [
                      "T"
                    ],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "Foo",
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    }
                  }
                },
                "kind": "TopLevel",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Var": 99
                            }
                          ]
                        }
                      },
                      {
                        "Fun": {
                          "args": [
                            {
                              "Var": 99
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "name": "string",
                              "args": []
                            }
                          },
                          "id": -1
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 4
                  },
                  "end": {
                    "line": 6,
                    "col": 5
                  }
                }
              }
            },
            {
              "Closure": {
                "fun": {
                  "name": "other",
                  "generics": [
                    "T"
                  ],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "self",
                          "is_mut": false,
                          "ann": {
                            "Con": {
                              "name": "Foo",
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 2
                            },
                            "end": {
                              "line": 11,
                              "col": 3
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Con": {
                                "name": "T",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "Call": {
                            "func": {
                              "FieldAccess": {
                                "expr": {
                                  "Var": {
                                    "value": "self",
                                    "decl": {
                                      "file_id": {
                                        "package": "dummy",
                                        "filename": "dummy"
                                      },
                                      "span": {
                                        "start": {
                                          "line": 3,
                                          "col": 2
                                        },
                                        "end": {
                                          "line": 11,
                                          "col": 3
                                        }
                                      }
                                    },
                                    "generics_instantiated": [],
                                    "ty": {
                                      "Con": {
                                        "name": "Foo",
                                        "args": [
                                          {
                                            "Con": {
                                              "name": "T",
                                              "args": []
                                            }
                                          }
                                        ]
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 9,
                                        "col": 6
                                      },
                                      "end": {
                                        "line": 9,
                                        "col": 10
                                      }
                                    }
                                  }
                                },
                                "field": "map",
                                "ty": {
                                  "Fun": {
                                    "args": [
                                      {
                                        "Fun": {
                                          "args": [
                                            {
                                              "Con": {
                                                "name": "T",
                                                "args": []
                                              }
                                            }
                                          ],
                                          "bounds": [],
                                          "ret": {
                                            "Con": {
                                              "name": "string",
                                              "args": []
                                            }
                                          },
                                          "id": -1
                                        }
                                      }
                                    ],
                                    "bounds": [],
                                    "ret": {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    },
                                    "id": -1
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 9,
                                    "col": 11
                                  },
                                  "end": {
                                    "line": 9,
                                    "col": 14
                                  }
                                }
                              }
                            },
                            "args": [
                              {
                                "Closure": {
                                  "fun": {
                                    "name": "__anonymous",
                                    "generics": [],
                                    "bounds": [],
                                    "args": [
                                      {
                                        "pat": {
                                          "Type": {
                                            "ident": "x",
                                            "is_mut": false,
                                            "ann": "Unknown",
                                            "span": {
                                              "start": {
                                                "line": 9,
                                                "col": 16
                                              },
                                              "end": {
                                                "line": 9,
                                                "col": 17
                                              }
                                            }
                                          }
                                        },
                                        "ann": "Unknown",
                                        "ty": {
                                          "Con": {
                                            "name": "T",
                                            "args": []
                                          }
                                        }
                                      }
                                    ],
                                    "ret": {
                                      "Con": {
                                        "name": "string",
                                        "args": []
                                      }
                                    },
                                    "ann": "Unknown",
                                    "body": {
                                      "Literal": {
                                        "lit": {
                                          "String": [
                                            "asdf",
                                            null
                                          ]
                                        },
                                        "ty": {
                                          "Con": {
                                            "name": "string",
                                            "args": []
                                          }
                                        },
                                        "span": {
                                          "start": {
                                            "line": 9,
                                            "col": 19
                                          },
                                          "end": {
                                            "line": 9,
                                            "col": 25
                                          }
                                        }
                                      }
                                    },
                                    "bounded_ty": {
                                      "generics": [],
                                      "ty": {
                                        "Fun": {
                                          "args": [
                                            {
                                              "Var": 99
                                            }
                                          ],
                                          "bounds": [],
                                          "ret": {
                                            "Var": 99
                                          },
                                          "id": -1
                                        }
                                      }
                                    }
                                  },
                                  "kind": "Lambda",
                                  "ty": {
                                    "Fun": {
                                      "args": [
                                        {
                                          "Con": {
                                            "name": "T",
                                            "args": []
                                          }
                                        }
                                      ],
                                      "bounds": [],
                                      "ret": {
                                        "Con": {
                                          "name": "string",
                                          "args": []
                                        }
                                      },
                                      "id": -1
                                    }
                                  },
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 15
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 25
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 9,
                                "col": 11
                              },
                              "end": {
                                "line": 9,
                                "col": 14
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 8,
                          "col": 29
                        },
                        "end": {
                          "line": 10,
                          "col": 5
                        }
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [
                      "T"
                    ],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "Foo",
                              "args": [
                                {
                                  "Con": {
                                    "name": "T",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    }
                  }
                },
                "kind": "TopLevel",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "Foo",
                          "args": [
                            {
                              "Var": 99
                            }
                          ]
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 4
                  },
                  "end": {
                    "line": 10,
                    "col": 5
                  }
                }
              }
            }
          ],
          "generics": [
            "T"
          ],
          "span": {
            "start": {
              "line": 3,
              "col": 10
            },
            "end": {
              "line": 3,
              "col": 16
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "foo",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 13,
                    "col": 6
                  },
                  "end": {
                    "line": 13,
                    "col": 9
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Foo",
                "args": [
                  {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "bar",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 12
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 13,
                          "col": 23
                        },
                        "end": {
                          "line": 13,
                          "col": 25
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 13,
                  "col": 12
                },
                "end": {
                  "line": 13,
                  "col": 27
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 13,
              "col": 2
            },
            "end": {
              "line": 13,
              "col": 28
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "FieldAccess": {
              "expr": {
                "Var": {
                  "value": "foo",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 13,
                        "col": 6
                      },
                      "end": {
                        "line": 13,
                        "col": 9
                      }
                    }
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "name": "Foo",
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 14,
                      "col": 2
                    },
                    "end": {
                      "line": 14,
                      "col": 5
                    }
                  }
                }
              },
              "field": "other",
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 14,
                  "col": 6
                },
                "end": {
                  "line": 14,
                  "col": 11
                }
              }
            }
          },
          "args": [],
          "ty": {
            "Con": {
              "name": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 14,
              "col": 6
            },
            "end": {
              "line": 14,
              "col": 11
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 15,
        "col": 1
      }
    }
  }
}
