Generic enums can be pattern matched.

SOURCE:
{
  enum Maybe<T> { Just(T), None }

  let x = Maybe.Just(1)
  match x {
    Maybe.Just(v) => v,
    Maybe.None => 2,
  }
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Maybe",
            "generics": [
              {
                "name": "T",
                "bounds": [],
                "span": {
                  "start": {
                    "line": 2,
                    "col": 14
                  },
                  "end": {
                    "line": 2,
                    "col": 15
                  },
                  "file": 99
                }
              }
            ],
            "cons": [
              {
                "name": "Just",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "id": "T",
                        "args": []
                      }
                    }
                  }
                ]
              },
              {
                "name": "None",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 33
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 4,
                    "col": 7
                  },
                  "end": {
                    "line": 4,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Maybe",
                "args": [
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Maybe.Just",
                  "decl": {
                    "start": {
                      "line": 2,
                      "col": 3
                    },
                    "end": {
                      "line": 2,
                      "col": 33
                    },
                    "file": 99
                  },
                  "generics_instantiated": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 17
                    },
                    "end": {
                      "line": 4,
                      "col": 21
                    },
                    "file": 99
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "Int": 1
                    },
                    "ty": {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 22
                      },
                      "end": {
                        "line": 4,
                        "col": 23
                      },
                      "file": 99
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "id": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 21
                },
                "end": {
                  "line": 4,
                  "col": 23
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Maybe",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 4,
              "col": 23
            },
            "file": 99
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "x",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 7
                },
                "end": {
                  "line": 4,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 9
                },
                "end": {
                  "line": 5,
                  "col": 10
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe.Just",
                  "elems": [
                    {
                      "Type": {
                        "ident": "v",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 6,
                            "col": 16
                          },
                          "end": {
                            "line": 6,
                            "col": 17
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 5
                    },
                    "end": {
                      "line": 6,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "v",
                  "decl": {
                    "start": {
                      "line": 6,
                      "col": 16
                    },
                    "end": {
                      "line": 6,
                      "col": 17
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 22
                    },
                    "end": {
                      "line": 6,
                      "col": 23
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe.None",
                  "elems": [],
                  "ty": {
                    "Con": {
                      "id": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 5
                    },
                    "end": {
                      "line": 7,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Int": 2
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 19
                    },
                    "end": {
                      "line": 7,
                      "col": 20
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 3
            },
            "end": {
              "line": 8,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 9,
        "col": 1
      },
      "file": 99
    }
  }
}
