Generic arguments 2

SOURCE:
{ fn foo() -> [[int]] { [[1]]} }

OUTPUT:
fn () -> [[int]]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Slice",
                "args": [
                  {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Literal": {
                      "lit": {
                        "Slice": [
                          {
                            "Literal": {
                              "lit": {
                                "Slice": [
                                  {
                                    "Literal": {
                                      "lit": {
                                        "Int": 1
                                      },
                                      "ty": {
                                        "Con": {
                                          "name": "int",
                                          "args": []
                                        }
                                      },
                                      "span": {
                                        "start": {
                                          "line": 1,
                                          "col": 26
                                        },
                                        "end": {
                                          "line": 1,
                                          "col": 27
                                        }
                                      }
                                    }
                                  }
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "Slice",
                                  "args": [
                                    {
                                      "Con": {
                                        "name": "int",
                                        "args": []
                                      }
                                    }
                                  ]
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 1,
                                  "col": 25
                                },
                                "end": {
                                  "line": 1,
                                  "col": 28
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "Slice",
                          "args": [
                            {
                              "Con": {
                                "name": "Slice",
                                "args": [
                                  {
                                    "Con": {
                                      "name": "int",
                                      "args": []
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 1,
                          "col": 24
                        },
                        "end": {
                          "line": 1,
                          "col": 29
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Slice",
                    "args": [
                      {
                        "Con": {
                          "name": "Slice",
                          "args": [
                            {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 1,
                    "col": 22
                  },
                  "end": {
                    "line": 1,
                    "col": 30
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "Slice",
                            "args": [
                              {
                                "Con": {
                                  "name": "int",
                                  "args": []
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Slice",
                  "args": [
                    {
                      "Con": {
                        "name": "Slice",
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 30
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Slice",
            "args": [
              {
                "Con": {
                  "name": "Slice",
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 32
      }
    }
  }
}
