If expressions.

SOURCE:
if true {
  1
} else {
  2
}

OUTPUT:
int
---
No errors.
---
{
  "If": {
    "cond": {
      "Literal": {
        "lit": {
          "Bool": true
        },
        "ty": {
          "Con": {
            "name": "bool",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 3
          },
          "end": {
            "line": 1,
            "col": 7
          }
        }
      }
    },
    "then": {
      "Block": {
        "stmts": [
          {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 2
                },
                "end": {
                  "line": 2,
                  "col": 3
                }
              }
            }
          }
        ],
        "ty": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 8
          },
          "end": {
            "line": 3,
            "col": 1
          }
        }
      }
    },
    "els": {
      "Block": {
        "stmts": [
          {
            "Literal": {
              "lit": {
                "Int": 2
              },
              "ty": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 2
                },
                "end": {
                  "line": 4,
                  "col": 3
                }
              }
            }
          }
        ],
        "ty": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 3,
            "col": 7
          },
          "end": {
            "line": 5,
            "col": 1
          }
        }
      }
    },
    "ty": {
      "Con": {
        "name": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 5,
        "col": 1
      }
    }
  }
}
