If expressions.

SOURCE:
if true {
  1
} else {
  2
}

OUTPUT:
int
---
No errors.
---
{
  "If": {
    "cond": {
      "Literal": {
        "lit": {
          "Bool": true
        },
        "ty": {
          "Con": {
            "id": "bool",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 4
          },
          "end": {
            "line": 1,
            "col": 8
          },
          "file": 99
        }
      }
    },
    "then": {
      "Block": {
        "stmts": [
          {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 3
                },
                "end": {
                  "line": 2,
                  "col": 4
                },
                "file": 99
              }
            }
          }
        ],
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 9
          },
          "end": {
            "line": 3,
            "col": 1
          },
          "file": 99
        }
      }
    },
    "els": {
      "Block": {
        "stmts": [
          {
            "Literal": {
              "lit": {
                "Int": 2
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 3
                },
                "end": {
                  "line": 4,
                  "col": 4
                },
                "file": 99
              }
            }
          }
        ],
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 3,
            "col": 8
          },
          "end": {
            "line": 5,
            "col": 1
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 5,
        "col": 1
      },
      "file": 99
    }
  }
}
