Impl blocks

SOURCE:
{
    enum Color { Red, Blue }

    impl Color {
        fn is_red(self) -> bool {
            self == Color::Red
        }
    }

    Color::Red.is_red()
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Color",
            "generics": [],
            "cons": [
              {
                "name": "Red",
                "fields": []
              },
              {
                "name": "Blue",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 4
            },
            "end": {
              "line": 2,
              "col": 28
            },
            "file": 99
          }
        }
      },
      {
        "ImplBlock": {
          "ann": {
            "Con": {
              "name": "Color",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "id": "Color",
              "args": []
            }
          },
          "items": [
            {
              "Closure": {
                "fun": {
                  "name": "is_red",
                  "generics": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "self",
                          "is_mut": false,
                          "ann": {
                            "Con": {
                              "name": "Color",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 4
                            },
                            "end": {
                              "line": 8,
                              "col": 5
                            },
                            "file": 99
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "Color",
                          "args": []
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "Color",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "bool",
                      "args": []
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "Binary": {
                            "op": "Eq",
                            "left": {
                              "Var": {
                                "value": "self",
                                "decl": {
                                  "start": {
                                    "line": 4,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 8,
                                    "col": 5
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "Color",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 12
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 16
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "right": {
                              "Var": {
                                "value": "Color::Red",
                                "decl": {
                                  "start": {
                                    "line": 2,
                                    "col": 4
                                  },
                                  "end": {
                                    "line": 2,
                                    "col": 28
                                  },
                                  "file": 99
                                },
                                "generics_instantiated": [],
                                "ty": {
                                  "Con": {
                                    "id": "Color",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 20
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 30
                                  },
                                  "file": 99
                                }
                              }
                            },
                            "ty": {
                              "Con": {
                                "id": "bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 12
                              },
                              "end": {
                                "line": 6,
                                "col": 30
                              },
                              "file": 99
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "id": "bool",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 32
                        },
                        "end": {
                          "line": 7,
                          "col": 9
                        },
                        "file": 99
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "id": "Color",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "id": "bool",
                            "args": []
                          }
                        }
                      }
                    }
                  }
                },
                "kind": "TopLevel",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "id": "Color",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "id": "bool",
                        "args": []
                      }
                    }
                  }
                },
                "span": {
                  "start": {
                    "line": 5,
                    "col": 8
                  },
                  "end": {
                    "line": 7,
                    "col": 9
                  },
                  "file": 99
                }
              }
            }
          ],
          "generics": [],
          "span": {
            "start": {
              "line": 4,
              "col": 9
            },
            "end": {
              "line": 4,
              "col": 14
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "FieldAccess": {
              "expr": {
                "Var": {
                  "value": "Color::Red",
                  "decl": {
                    "start": {
                      "line": 2,
                      "col": 4
                    },
                    "end": {
                      "line": 2,
                      "col": 28
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "id": "Color",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 10,
                      "col": 4
                    },
                    "end": {
                      "line": 10,
                      "col": 14
                    },
                    "file": 99
                  }
                }
              },
              "field": "is_red",
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 10,
                  "col": 15
                },
                "end": {
                  "line": 10,
                  "col": 21
                },
                "file": 99
              }
            }
          },
          "args": [],
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 10,
              "col": 15
            },
            "end": {
              "line": 10,
              "col": 21
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 11,
        "col": 1
      },
      "file": 99
    }
  }
}
