It's possible to sanity-check the type of a value.

SOURCE:
{
  let x = [1,2,3];
  x as [int];
  x
}

OUTPUT:
[int]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 7
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Slice",
                "args": [
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Slice": [
                  {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 11
                        },
                        "end": {
                          "line": 2,
                          "col": 12
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 13
                        },
                        "end": {
                          "line": 2,
                          "col": 14
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 3
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 15
                        },
                        "end": {
                          "line": 2,
                          "col": 16
                        },
                        "file": 99
                      }
                    }
                  }
                ]
              },
              "ty": {
                "Con": {
                  "id": "Slice",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 10
                },
                "end": {
                  "line": 2,
                  "col": 17
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 18
            },
            "file": 99
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "x",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 6
                },
                "end": {
                  "line": 2,
                  "col": 7
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Slice",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 3
                },
                "file": 99
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Slice",
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 12
            },
            "file": 99
          }
        }
      },
      {
        "Var": {
          "value": "x",
          "decl": {
            "start": {
              "line": 2,
              "col": 6
            },
            "end": {
              "line": 2,
              "col": 7
            },
            "file": 99
          },
          "generics_instantiated": [],
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "Slice",
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 5,
        "col": 1
      },
      "file": 99
    }
  }
}
