It's possible to sanity-check the type of a value.

SOURCE:
{
  let x = [1,2,3];
  x as List<Int>
}

OUTPUT:
List<Int>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "List",
                "args": [
                  {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "List": [
                  {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 11
                        },
                        "end": {
                          "line": 2,
                          "col": 12
                        }
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 13
                        },
                        "end": {
                          "line": 2,
                          "col": 14
                        }
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 3
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 15
                        },
                        "end": {
                          "line": 2,
                          "col": 16
                        }
                      }
                    }
                  }
                ]
              },
              "ty": {
                "Con": {
                  "name": "List",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 10
                },
                "end": {
                  "line": 2,
                  "col": 17
                }
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "name": "List",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 18
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "x",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 7
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "List",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 3
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "List",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "ty": {
            "Con": {
              "name": "List",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 16
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "List",
        "args": [
          {
            "Con": {
              "name": "Int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      }
    }
  }
}
