List literals

SOURCE:
{ [1,2,3] }

OUTPUT:
List<Int>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Literal": {
          "lit": {
            "List": [
              {
                "Literal": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 3
                    },
                    "end": {
                      "line": 1,
                      "col": 4
                    }
                  }
                }
              },
              {
                "Literal": {
                  "lit": {
                    "Int": 2
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 5
                    },
                    "end": {
                      "line": 1,
                      "col": 6
                    }
                  }
                }
              },
              {
                "Literal": {
                  "lit": {
                    "Int": 3
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 7
                    },
                    "end": {
                      "line": 1,
                      "col": 8
                    }
                  }
                }
              }
            ]
          },
          "ty": {
            "Con": {
              "name": "List",
              "args": [
                {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 9
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "List",
        "args": [
          {
            "Con": {
              "name": "Int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 11
      }
    }
  }
}
