Match expressions.

SOURCE:
match 1 {
  1 => "foo",
}

OUTPUT:
string
---
No errors.
---
{
  "Match": {
    "subject": {
      "Literal": {
        "lit": {
          "Int": 1
        },
        "ty": {
          "Con": {
            "name": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 6
          },
          "end": {
            "line": 1,
            "col": 7
          }
        }
      }
    },
    "arms": [
      {
        "pat": {
          "Lit": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 2
              },
              "end": {
                "line": 2,
                "col": 3
              }
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "String": [
                "foo",
                null
              ]
            },
            "ty": {
              "Con": {
                "name": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 7
              },
              "end": {
                "line": 2,
                "col": 12
              }
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 3,
        "col": 1
      }
    }
  }
}
