Match weirdness

SOURCE:
{
    match false {
        true => print("asdf"),
    };

    match 1 {
        1 => false,
    }
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Match": {
          "subject": {
            "Literal": {
              "lit": {
                "Bool": false
              },
              "ty": {
                "Con": {
                  "id": "bool",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 10
                },
                "end": {
                  "line": 2,
                  "col": 15
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Lit": {
                  "lit": {
                    "Bool": true
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 8
                    },
                    "end": {
                      "line": 3,
                      "col": 12
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "print",
                      "decl": {
                        "start": {
                          "line": 49,
                          "col": 0
                        },
                        "end": {
                          "line": 51,
                          "col": 1
                        },
                        "file": -1
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "Unit",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 16
                        },
                        "end": {
                          "line": 3,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Literal": {
                        "lit": {
                          "String": [
                            "asdf",
                            null
                          ]
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 3,
                            "col": 22
                          },
                          "end": {
                            "line": 3,
                            "col": 28
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Unit",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 16
                    },
                    "end": {
                      "line": 3,
                      "col": 29
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "Unit",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 4
            },
            "end": {
              "line": 4,
              "col": 5
            },
            "file": 99
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 10
                },
                "end": {
                  "line": 6,
                  "col": 11
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Lit": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 8
                    },
                    "end": {
                      "line": 7,
                      "col": 9
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Bool": false
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 13
                    },
                    "end": {
                      "line": 7,
                      "col": 18
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 4
            },
            "end": {
              "line": 8,
              "col": 5
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 1
      },
      "file": 99
    }
  }
}
