Math operands on ints

SOURCE:
{ 1 + 5 }

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Binary": {
          "op": "Add",
          "left": {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 3
                },
                "end": {
                  "line": 1,
                  "col": 4
                },
                "file": 99
              }
            }
          },
          "right": {
            "Literal": {
              "lit": {
                "Int": 5
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 7
                },
                "end": {
                  "line": 1,
                  "col": 8
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 8
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 9
      },
      "file": 99
    }
  }
}
