Math operands on Ints

SOURCE:
{ 1 + 5 }

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Binary": {
          "op": "Add",
          "left": {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 2
                },
                "end": {
                  "line": 1,
                  "col": 3
                }
              }
            }
          },
          "right": {
            "Literal": {
              "lit": {
                "Int": 5
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 1,
                  "col": 6
                },
                "end": {
                  "line": 1,
                  "col": 7
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 2
            },
            "end": {
              "line": 1,
              "col": 7
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 9
      }
    }
  }
}
