Math ops with floats

SOURCE:
1.3 + 5.2

OUTPUT:
float64
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Literal": {
        "lit": {
          "Float": 1.3
        },
        "ty": {
          "Con": {
            "id": "float64",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 4
          },
          "file": 99
        }
      }
    },
    "right": {
      "Literal": {
        "lit": {
          "Float": 5.2
        },
        "ty": {
          "Con": {
            "id": "float64",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 7
          },
          "end": {
            "line": 1,
            "col": 10
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "float64",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 10
      },
      "file": 99
    }
  }
}
