Methods.

SOURCE:
{
  1.int_to_string() as String;
  let x = 5;
  x.sum(3) as Int;
  hello().str_concat("foo")
}

OUTPUT:
String
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "int_to_string",
                  "decl": {
                    "file_id": {
                      "package": "std",
                      "filename": "builtin.brg"
                    },
                    "span": {
                      "start": {
                        "line": 0,
                        "col": 0
                      },
                      "end": {
                        "line": 0,
                        "col": 0
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "String",
                          "args": []
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 2,
                      "col": 4
                    },
                    "end": {
                      "line": 2,
                      "col": 17
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "Int": 1
                    },
                    "ty": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 4
                      },
                      "end": {
                        "line": 2,
                        "col": 17
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "String",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 4
                },
                "end": {
                  "line": 2,
                  "col": 17
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "String",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "String",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 29
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Int",
                "args": []
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Int": 5
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 10
                },
                "end": {
                  "line": 3,
                  "col": 11
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 12
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Call": {
              "func": {
                "Var": {
                  "value": "sum",
                  "decl": {
                    "file_id": {
                      "package": "std",
                      "filename": "builtin.brg"
                    },
                    "span": {
                      "start": {
                        "line": 0,
                        "col": 0
                      },
                      "end": {
                        "line": 0,
                        "col": 0
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 4
                    },
                    "end": {
                      "line": 4,
                      "col": 7
                    }
                  }
                }
              },
              "args": [
                {
                  "Var": {
                    "value": "x",
                    "decl": {
                      "file_id": {
                        "package": "dummy",
                        "filename": "dummy"
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 6
                        },
                        "end": {
                          "line": 3,
                          "col": 7
                        }
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 4
                      },
                      "end": {
                        "line": 4,
                        "col": 7
                      }
                    }
                  }
                },
                {
                  "Literal": {
                    "lit": {
                      "Int": 3
                    },
                    "ty": {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 8
                      },
                      "end": {
                        "line": 4,
                        "col": 9
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 4
                },
                "end": {
                  "line": 4,
                  "col": 7
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 17
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "str_concat",
              "decl": {
                "file_id": {
                  "package": "std",
                  "filename": "builtin.brg"
                },
                "span": {
                  "start": {
                    "line": 0,
                    "col": 0
                  },
                  "end": {
                    "line": 0,
                    "col": 0
                  }
                }
              },
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "String",
                      "args": []
                    }
                  },
                  "fx": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 10
                },
                "end": {
                  "line": 5,
                  "col": 20
                }
              }
            }
          },
          "args": [
            {
              "Call": {
                "func": {
                  "Var": {
                    "value": "hello",
                    "decl": {
                      "file_id": {
                        "package": "std",
                        "filename": "builtin.brg"
                      },
                      "span": {
                        "start": {
                          "line": 0,
                          "col": 0
                        },
                        "end": {
                          "line": 0,
                          "col": 0
                        }
                      }
                    },
                    "ty": {
                      "Fun": {
                        "args": [],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        },
                        "fx": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 5,
                        "col": 2
                      },
                      "end": {
                        "line": 5,
                        "col": 7
                      }
                    }
                  }
                },
                "args": [],
                "ty": {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 5,
                    "col": 10
                  },
                  "end": {
                    "line": 5,
                    "col": 20
                  }
                }
              }
            },
            {
              "Literal": {
                "lit": {
                  "String": "foo"
                },
                "ty": {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 5,
                    "col": 21
                  },
                  "end": {
                    "line": 5,
                    "col": 26
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "String",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 10
            },
            "end": {
              "line": 5,
              "col": 20
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "String",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 6,
        "col": 1
      }
    }
  }
}
