Mutable variables

SOURCE:
{
  let mut x = 0;
  x = x + 1;
  x
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": true,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 11
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Int": 0
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 14
                },
                "end": {
                  "line": 2,
                  "col": 15
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 16
            },
            "file": 99
          }
        }
      },
      {
        "VarUpdate": {
          "target": {
            "Var": {
              "value": "x",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 6
                },
                "end": {
                  "line": 2,
                  "col": 11
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 3
                },
                "file": 99
              }
            }
          },
          "value": {
            "Binary": {
              "op": "Add",
              "left": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "start": {
                      "line": 2,
                      "col": 6
                    },
                    "end": {
                      "line": 2,
                      "col": 11
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 6
                    },
                    "end": {
                      "line": 3,
                      "col": 7
                    },
                    "file": 99
                  }
                }
              },
              "right": {
                "Literal": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 10
                    },
                    "end": {
                      "line": 3,
                      "col": 11
                    },
                    "file": 99
                  }
                }
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 6
                },
                "end": {
                  "line": 3,
                  "col": 11
                },
                "file": 99
              }
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 11
            },
            "file": 99
          }
        }
      },
      {
        "Var": {
          "value": "x",
          "decl": {
            "start": {
              "line": 2,
              "col": 6
            },
            "end": {
              "line": 2,
              "col": 11
            },
            "file": 99
          },
          "generics_instantiated": [],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 5,
        "col": 1
      },
      "file": 99
    }
  }
}
