Mutable reference as method receiver

SOURCE:
{
  struct Foo { x: int }

  impl Foo {
    fn bar(&mut self) {
      self.x = 5;
    }
  }

  let mut f = Foo { x: 3 };
  f.bar()
}

OUTPUT:
()
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 23
            }
          }
        }
      },
      {
        "ImplBlock": {
          "ann": {
            "Con": {
              "name": "Foo",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": []
            }
          },
          "items": [
            {
              "Closure": {
                "fun": {
                  "name": "bar",
                  "generics": [],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "self",
                          "is_mut": true,
                          "ann": {
                            "Con": {
                              "name": "RefMut",
                              "args": [
                                {
                                  "Con": {
                                    "name": "Foo",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 2
                            },
                            "end": {
                              "line": 8,
                              "col": 3
                            }
                          }
                        }
                      },
                      "ann": {
                        "Con": {
                          "name": "RefMut",
                          "args": [
                            {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "RefMut",
                          "args": [
                            {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "ann": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "body": {
                    "Block": {
                      "stmts": [
                        {
                          "VarUpdate": {
                            "target": {
                              "FieldAccess": {
                                "expr": {
                                  "Var": {
                                    "value": "self",
                                    "decl": {
                                      "file_id": {
                                        "package": "dummy",
                                        "filename": "dummy"
                                      },
                                      "span": {
                                        "start": {
                                          "line": 4,
                                          "col": 2
                                        },
                                        "end": {
                                          "line": 8,
                                          "col": 3
                                        }
                                      }
                                    },
                                    "generics_instantiated": [],
                                    "ty": {
                                      "Con": {
                                        "name": "RefMut",
                                        "args": [
                                          {
                                            "Con": {
                                              "name": "Foo",
                                              "args": []
                                            }
                                          }
                                        ]
                                      }
                                    },
                                    "span": {
                                      "start": {
                                        "line": 6,
                                        "col": 6
                                      },
                                      "end": {
                                        "line": 6,
                                        "col": 10
                                      }
                                    }
                                  }
                                },
                                "field": "x",
                                "ty": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 12
                                  }
                                }
                              }
                            },
                            "value": {
                              "Literal": {
                                "lit": {
                                  "Int": 5
                                },
                                "ty": {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 6,
                                    "col": 15
                                  },
                                  "end": {
                                    "line": 6,
                                    "col": 16
                                  }
                                }
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 6
                              },
                              "end": {
                                "line": 6,
                                "col": 16
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Unit",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 22
                        },
                        "end": {
                          "line": 7,
                          "col": 5
                        }
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "RefMut",
                              "args": [
                                {
                                  "Con": {
                                    "name": "Foo",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "Unit",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    }
                  }
                },
                "kind": "TopLevel",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "RefMut",
                          "args": [
                            {
                              "Con": {
                                "name": "Foo",
                                "args": []
                              }
                            }
                          ]
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "Unit",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 5,
                    "col": 4
                  },
                  "end": {
                    "line": 7,
                    "col": 5
                  }
                }
              }
            }
          ],
          "generics": [],
          "span": {
            "start": {
              "line": 4,
              "col": 7
            },
            "end": {
              "line": 4,
              "col": 10
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "f",
                "is_mut": true,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 10,
                    "col": 6
                  },
                  "end": {
                    "line": 10,
                    "col": 11
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Foo",
                "args": []
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "x",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 3
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 10,
                          "col": 23
                        },
                        "end": {
                          "line": 10,
                          "col": 24
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 10,
                  "col": 14
                },
                "end": {
                  "line": 10,
                  "col": 26
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 10,
              "col": 2
            },
            "end": {
              "line": 10,
              "col": 27
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "FieldAccess": {
              "expr": {
                "Var": {
                  "value": "f",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 10,
                        "col": 6
                      },
                      "end": {
                        "line": 10,
                        "col": 11
                      }
                    }
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "name": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 11,
                      "col": 2
                    },
                    "end": {
                      "line": 11,
                      "col": 3
                    }
                  }
                }
              },
              "field": "bar",
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Unit",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 11,
                  "col": 4
                },
                "end": {
                  "line": 11,
                  "col": 7
                }
              }
            }
          },
          "args": [],
          "ty": {
            "Con": {
              "name": "Unit",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 11,
              "col": 4
            },
            "end": {
              "line": 11,
              "col": 7
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Unit",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 12,
        "col": 1
      }
    }
  }
}
