Mutable variables

SOURCE:
{
  let mut x = 0;
  x = x + 1;
  x
}

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 11
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Int",
                "args": []
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Int": 0
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 14
                },
                "end": {
                  "line": 2,
                  "col": 15
                }
              }
            }
          },
          "mutable": true,
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 16
            }
          }
        }
      },
      {
        "VarUpdate": {
          "target": {
            "Var": {
              "value": "x",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 11
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 3
                }
              }
            }
          },
          "value": {
            "Binary": {
              "op": "Add",
              "left": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 6
                      },
                      "end": {
                        "line": 2,
                        "col": 11
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 6
                    },
                    "end": {
                      "line": 3,
                      "col": 7
                    }
                  }
                }
              },
              "right": {
                "Literal": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "name": "Int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 10
                    },
                    "end": {
                      "line": 3,
                      "col": 11
                    }
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 6
                },
                "end": {
                  "line": 3,
                  "col": 11
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 11
            }
          }
        }
      },
      {
        "Var": {
          "value": "x",
          "decl": {
            "file_id": {
              "package": "dummy",
              "filename": "dummy"
            },
            "span": {
              "start": {
                "line": 2,
                "col": 6
              },
              "end": {
                "line": 2,
                "col": 11
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 5,
        "col": 1
      }
    }
  }
}
