Negate expressions

SOURCE:
!false

OUTPUT:
bool
---
No errors.
---
{
  "Unary": {
    "op": "Not",
    "expr": {
      "Literal": {
        "lit": {
          "Bool": false
        },
        "ty": {
          "Con": {
            "id": "bool",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 2
          },
          "end": {
            "line": 1,
            "col": 7
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 7
      },
      "file": 99
    }
  }
}
