Negative numbers

SOURCE:
5 * -3

OUTPUT:
Int
---
No errors.
---
[]
---
{
  "Binary": {
    "op": "Mul",
    "left": {
      "Literal": {
        "lit": {
          "Int": 5
        },
        "ty": {
          "Con": {
            "name": "Int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 0
          },
          "end": {
            "line": 1,
            "col": 1
          }
        }
      }
    },
    "right": {
      "Unary": {
        "op": "Neg",
        "expr": {
          "Literal": {
            "lit": {
              "Int": 3
            },
            "ty": {
              "Con": {
                "name": "Int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 5
              },
              "end": {
                "line": 1,
                "col": 6
              }
            }
          }
        },
        "ty": {
          "Con": {
            "name": "Int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 4
          },
          "end": {
            "line": 1,
            "col": 6
          }
        }
      }
    },
    "ty": {
      "Con": {
        "name": "Int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 6
      }
    }
  }
}
