Negative numbers

SOURCE:
5 * -3

OUTPUT:
int
---
No errors.
---
{
  "Binary": {
    "op": "Mul",
    "left": {
      "Literal": {
        "lit": {
          "Int": 5
        },
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 2
          },
          "file": 99
        }
      }
    },
    "right": {
      "Unary": {
        "op": "Neg",
        "expr": {
          "Literal": {
            "lit": {
              "Int": 3
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 6
              },
              "end": {
                "line": 1,
                "col": 7
              },
              "file": 99
            }
          }
        },
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 5
          },
          "end": {
            "line": 1,
            "col": 7
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 7
      },
      "file": 99
    }
  }
}
