Nested updates.

SOURCE:
{
  struct Foo { a: int, b: string }
  struct Bar { a: int, b: string, f: Foo }

  let x = Foo { a: 1, b: "foo" }
  let y = Bar { a: 1, b: "bar", f: x }
  Bar { a: 2, b: "baz", f: Foo { a: 4, ..x } }
}

OUTPUT:
Bar
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "a",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "b",
                "ann": {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 34
            },
            "file": 99
          }
        }
      },
      {
        "StructDef": {
          "def": {
            "name": "Bar",
            "generics": [],
            "fields": [
              {
                "name": "a",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "b",
                "ann": {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "f",
                "ann": {
                  "Con": {
                    "name": "Foo",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 3,
              "col": 3
            },
            "end": {
              "line": 3,
              "col": 42
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 5,
                    "col": 7
                  },
                  "end": {
                    "line": 5,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Foo",
                "args": []
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "a",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 20
                        },
                        "end": {
                          "line": 5,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "b",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": {
                          "Single": "foo"
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 26
                        },
                        "end": {
                          "line": 5,
                          "col": 31
                        },
                        "file": 99
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 15
                },
                "end": {
                  "line": 5,
                  "col": 32
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Foo",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 3
            },
            "end": {
              "line": 5,
              "col": 32
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "y",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 6,
                    "col": 7
                  },
                  "end": {
                    "line": 6,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Bar",
                "args": []
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Bar",
              "fields": [
                {
                  "name": "a",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 20
                        },
                        "end": {
                          "line": 6,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "b",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": {
                          "Single": "bar"
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 26
                        },
                        "end": {
                          "line": 6,
                          "col": 31
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "f",
                  "value": {
                    "Var": {
                      "value": "x",
                      "decl": {
                        "start": {
                          "line": 5,
                          "col": 7
                        },
                        "end": {
                          "line": 5,
                          "col": 8
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 36
                        },
                        "end": {
                          "line": 6,
                          "col": 37
                        },
                        "file": 99
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "id": "Bar",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 15
                },
                "end": {
                  "line": 6,
                  "col": 38
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Bar",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 3
            },
            "end": {
              "line": 6,
              "col": 38
            },
            "file": 99
          }
        }
      },
      {
        "StructCall": {
          "name": "Bar",
          "fields": [
            {
              "name": "a",
              "value": {
                "Literal": {
                  "lit": {
                    "Int": 2
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 12
                    },
                    "end": {
                      "line": 7,
                      "col": 13
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "name": "b",
              "value": {
                "Literal": {
                  "lit": {
                    "String": {
                      "Single": "baz"
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 18
                    },
                    "end": {
                      "line": 7,
                      "col": 23
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "name": "f",
              "value": {
                "StructCall": {
                  "name": "Foo",
                  "fields": [
                    {
                      "name": "a",
                      "value": {
                        "Literal": {
                          "lit": {
                            "Int": 4
                          },
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 7,
                              "col": 37
                            },
                            "end": {
                              "line": 7,
                              "col": 38
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "rest": {
                    "Var": {
                      "value": "x",
                      "decl": {
                        "start": {
                          "line": 5,
                          "col": 7
                        },
                        "end": {
                          "line": 5,
                          "col": 8
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "Foo",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 7,
                          "col": 42
                        },
                        "end": {
                          "line": 7,
                          "col": 43
                        },
                        "file": 99
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 32
                    },
                    "end": {
                      "line": 7,
                      "col": 44
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "rest": null,
          "ty": {
            "Con": {
              "id": "Bar",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 7,
              "col": 7
            },
            "end": {
              "line": 7,
              "col": 46
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "Bar",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 8,
        "col": 1
      },
      "file": 99
    }
  }
}
