Nested pattern matching is supported.

SOURCE:
{
  enum Maybe<T> { Just(T), None }
  enum Color { Red, Blue(String, Bool) }

  let c = Color::Blue("foo", false);
  let x = Maybe::Just(c);

  let n = match x {
    Maybe::Just(Color::Blue(s, b)) => {
      s as String;
      b as Bool;
      1
    },
    Maybe::None => 2,
  };

  n as Int;

  match x {
    Maybe::Just(x) => x,
    Maybe::None => Color::Red,
  }
}

OUTPUT:
Color
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Maybe",
            "generics": [
              "T"
            ],
            "cons": [
              {
                "name": "Just",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "T",
                        "args": []
                      }
                    }
                  }
                ]
              },
              {
                "name": "None",
                "fields": []
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 33
            }
          }
        }
      },
      {
        "EnumDef": {
          "def": {
            "name": "Color",
            "generics": [],
            "cons": [
              {
                "name": "Red",
                "fields": []
              },
              {
                "name": "Blue",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  },
                  {
                    "name": "field1",
                    "ann": {
                      "Con": {
                        "name": "Bool",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "Bool",
                        "args": []
                      }
                    }
                  }
                ]
              }
            ]
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 40
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "c",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 5,
                    "col": 6
                  },
                  "end": {
                    "line": 5,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Color",
                "args": []
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Color::Blue",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 3,
                        "col": 2
                      },
                      "end": {
                        "line": 3,
                        "col": 40
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "Bool",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Color",
                          "args": []
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 10
                    },
                    "end": {
                      "line": 5,
                      "col": 21
                    }
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "String": "foo"
                    },
                    "ty": {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 5,
                        "col": 22
                      },
                      "end": {
                        "line": 5,
                        "col": 27
                      }
                    }
                  }
                },
                {
                  "Literal": {
                    "lit": {
                      "Bool": false
                    },
                    "ty": {
                      "Con": {
                        "name": "Bool",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 5,
                        "col": 29
                      },
                      "end": {
                        "line": 5,
                        "col": 34
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Color",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 10
                },
                "end": {
                  "line": 5,
                  "col": 35
                }
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "name": "Color",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 36
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 6,
                    "col": 6
                  },
                  "end": {
                    "line": 6,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Maybe",
                "args": [
                  {
                    "Con": {
                      "name": "Color",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Maybe::Just",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 2
                      },
                      "end": {
                        "line": 2,
                        "col": 33
                      }
                    }
                  },
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "name": "Color",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Color",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "fx": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 10
                    },
                    "end": {
                      "line": 6,
                      "col": 21
                    }
                  }
                }
              },
              "args": [
                {
                  "Var": {
                    "value": "c",
                    "decl": {
                      "file_id": {
                        "package": "dummy",
                        "filename": "dummy"
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 6
                        },
                        "end": {
                          "line": 5,
                          "col": 7
                        }
                      }
                    },
                    "ty": {
                      "Con": {
                        "name": "Color",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 6,
                        "col": 22
                      },
                      "end": {
                        "line": 6,
                        "col": 23
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Color",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 10
                },
                "end": {
                  "line": 6,
                  "col": 24
                }
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "name": "Maybe",
              "args": [
                {
                  "Con": {
                    "name": "Color",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 25
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "n",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 8,
                    "col": 6
                  },
                  "end": {
                    "line": 8,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Int",
                "args": []
              }
            }
          },
          "value": {
            "Match": {
              "subject": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 6,
                        "col": 6
                      },
                      "end": {
                        "line": 6,
                        "col": 7
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Color",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 8,
                      "col": 16
                    },
                    "end": {
                      "line": 8,
                      "col": 17
                    }
                  }
                }
              },
              "arms": [
                {
                  "pat": {
                    "Pat": {
                      "ident": "Maybe::Just",
                      "elems": [
                        {
                          "Pat": {
                            "ident": "Color::Blue",
                            "elems": [
                              {
                                "Type": {
                                  "ident": "s",
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 28
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 29
                                    }
                                  }
                                }
                              },
                              {
                                "Type": {
                                  "ident": "b",
                                  "ann": "Unknown",
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 31
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 32
                                    }
                                  }
                                }
                              }
                            ],
                            "ty": {
                              "Con": {
                                "name": "Color",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 9,
                                "col": 16
                              },
                              "end": {
                                "line": 9,
                                "col": 33
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Color",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 9,
                          "col": 4
                        },
                        "end": {
                          "line": 9,
                          "col": 34
                        }
                      }
                    }
                  },
                  "expr": {
                    "Block": {
                      "stmts": [
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "s",
                                "decl": {
                                  "file_id": {
                                    "package": "dummy",
                                    "filename": "dummy"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 28
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 29
                                    }
                                  }
                                },
                                "ty": {
                                  "Con": {
                                    "name": "String",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 10,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 10,
                                    "col": 7
                                  }
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "String",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "name": "String",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 10,
                                "col": 6
                              },
                              "end": {
                                "line": 10,
                                "col": 17
                              }
                            }
                          }
                        },
                        {
                          "CheckType": {
                            "expr": {
                              "Var": {
                                "value": "b",
                                "decl": {
                                  "file_id": {
                                    "package": "dummy",
                                    "filename": "dummy"
                                  },
                                  "span": {
                                    "start": {
                                      "line": 9,
                                      "col": 31
                                    },
                                    "end": {
                                      "line": 9,
                                      "col": 32
                                    }
                                  }
                                },
                                "ty": {
                                  "Con": {
                                    "name": "Bool",
                                    "args": []
                                  }
                                },
                                "span": {
                                  "start": {
                                    "line": 11,
                                    "col": 6
                                  },
                                  "end": {
                                    "line": 11,
                                    "col": 7
                                  }
                                }
                              }
                            },
                            "ann": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "ty": {
                              "Con": {
                                "name": "Bool",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 11,
                                "col": 6
                              },
                              "end": {
                                "line": 11,
                                "col": 15
                              }
                            }
                          }
                        },
                        {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "name": "Int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 12,
                                "col": 6
                              },
                              "end": {
                                "line": 12,
                                "col": 7
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 9,
                          "col": 38
                        },
                        "end": {
                          "line": 13,
                          "col": 5
                        }
                      }
                    }
                  }
                },
                {
                  "pat": {
                    "Pat": {
                      "ident": "Maybe::None",
                      "elems": [],
                      "ty": {
                        "Con": {
                          "name": "Maybe",
                          "args": [
                            {
                              "Con": {
                                "name": "Color",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 14,
                          "col": 4
                        },
                        "end": {
                          "line": 14,
                          "col": 15
                        }
                      }
                    }
                  },
                  "expr": {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 14,
                          "col": 19
                        },
                        "end": {
                          "line": 14,
                          "col": 20
                        }
                      }
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 10
                },
                "end": {
                  "line": 15,
                  "col": 3
                }
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 2
            },
            "end": {
              "line": 15,
              "col": 4
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "Var": {
              "value": "n",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 6
                  },
                  "end": {
                    "line": 8,
                    "col": 7
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 17,
                  "col": 2
                },
                "end": {
                  "line": 17,
                  "col": 3
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "Int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 17,
              "col": 2
            },
            "end": {
              "line": 17,
              "col": 10
            }
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "x",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 6,
                    "col": 6
                  },
                  "end": {
                    "line": 6,
                    "col": 7
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Maybe",
                  "args": [
                    {
                      "Con": {
                        "name": "Color",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 19,
                  "col": 8
                },
                "end": {
                  "line": 19,
                  "col": 9
                }
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe::Just",
                  "elems": [
                    {
                      "Type": {
                        "ident": "x",
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 20,
                            "col": 16
                          },
                          "end": {
                            "line": 20,
                            "col": 17
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Color",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 20,
                      "col": 4
                    },
                    "end": {
                      "line": 20,
                      "col": 18
                    }
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 20,
                        "col": 16
                      },
                      "end": {
                        "line": 20,
                        "col": 17
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Color",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 20,
                      "col": 22
                    },
                    "end": {
                      "line": 20,
                      "col": 23
                    }
                  }
                }
              }
            },
            {
              "pat": {
                "Pat": {
                  "ident": "Maybe::None",
                  "elems": [],
                  "ty": {
                    "Con": {
                      "name": "Maybe",
                      "args": [
                        {
                          "Con": {
                            "name": "Color",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 21,
                      "col": 4
                    },
                    "end": {
                      "line": 21,
                      "col": 15
                    }
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "Color::Red",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 3,
                        "col": 2
                      },
                      "end": {
                        "line": 3,
                        "col": 40
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "Color",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 21,
                      "col": 19
                    },
                    "end": {
                      "line": 21,
                      "col": 29
                    }
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "Color",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 19,
              "col": 2
            },
            "end": {
              "line": 22,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Color",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 23,
        "col": 1
      }
    }
  }
}
