Not equal operator

SOURCE:
{
  1 != 2
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Binary": {
          "op": "Ne",
          "left": {
            "Literal": {
              "lit": {
                "Int": 1
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 3
                },
                "end": {
                  "line": 2,
                  "col": 4
                },
                "file": 99
              }
            }
          },
          "right": {
            "Literal": {
              "lit": {
                "Int": 2
              },
              "ty": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 8
                },
                "end": {
                  "line": 2,
                  "col": 9
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 9
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 3,
        "col": 1
      },
      "file": 99
    }
  }
}
