Pattern matching on structs

SOURCE:
{
  struct Foo { x: int, y: string }

  let f = Foo{ x: 34, y: "yo" }
  match f {
    Foo { x, y: "bar" } => false,
    Foo { x: 34, y: "bar" } => false,
    Foo { x, y } => true,
  }
}

OUTPUT:
bool
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "y",
                "ann": {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 34
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "f",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 4,
                    "col": 7
                  },
                  "end": {
                    "line": 4,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Foo",
                "args": []
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "x",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 34
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 19
                        },
                        "end": {
                          "line": 4,
                          "col": 21
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "y",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": {
                          "Single": "yo"
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 26
                        },
                        "end": {
                          "line": 4,
                          "col": 30
                        },
                        "file": 99
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 14
                },
                "end": {
                  "line": 4,
                  "col": 31
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Foo",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 4,
              "col": 31
            },
            "file": 99
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "f",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 7
                },
                "end": {
                  "line": 4,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 9
                },
                "end": {
                  "line": 5,
                  "col": 10
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Struct": {
                  "ident": "Foo",
                  "fields": [
                    {
                      "name": "x",
                      "value": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 9
                            },
                            "end": {
                              "line": 6,
                              "col": 12
                            },
                            "file": 99
                          }
                        }
                      }
                    },
                    {
                      "name": "y",
                      "value": {
                        "Lit": {
                          "lit": {
                            "String": {
                              "Single": "bar"
                            }
                          },
                          "ty": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 17
                            },
                            "end": {
                              "line": 6,
                              "col": 22
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 9
                    },
                    "end": {
                      "line": 6,
                      "col": 23
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Bool": false
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 28
                    },
                    "end": {
                      "line": 6,
                      "col": 33
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "pat": {
                "Struct": {
                  "ident": "Foo",
                  "fields": [
                    {
                      "name": "x",
                      "value": {
                        "Lit": {
                          "lit": {
                            "Int": 34
                          },
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 7,
                              "col": 14
                            },
                            "end": {
                              "line": 7,
                              "col": 16
                            },
                            "file": 99
                          }
                        }
                      }
                    },
                    {
                      "name": "y",
                      "value": {
                        "Lit": {
                          "lit": {
                            "String": {
                              "Single": "bar"
                            }
                          },
                          "ty": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 7,
                              "col": 21
                            },
                            "end": {
                              "line": 7,
                              "col": 26
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 9
                    },
                    "end": {
                      "line": 7,
                      "col": 27
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Bool": false
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 32
                    },
                    "end": {
                      "line": 7,
                      "col": 37
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "pat": {
                "Struct": {
                  "ident": "Foo",
                  "fields": [
                    {
                      "name": "x",
                      "value": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 9
                            },
                            "end": {
                              "line": 8,
                              "col": 12
                            },
                            "file": 99
                          }
                        }
                      }
                    },
                    {
                      "name": "y",
                      "value": {
                        "Type": {
                          "ident": "y",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 8,
                              "col": 9
                            },
                            "end": {
                              "line": 8,
                              "col": 15
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 8,
                      "col": 9
                    },
                    "end": {
                      "line": 8,
                      "col": 16
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "Bool": true
                  },
                  "ty": {
                    "Con": {
                      "id": "bool",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 8,
                      "col": 21
                    },
                    "end": {
                      "line": 8,
                      "col": 25
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "bool",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 3
            },
            "end": {
              "line": 9,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "bool",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 10,
        "col": 1
      },
      "file": 99
    }
  }
}
