Pattern matching works on enums.

SOURCE:
{
  enum Color { Red, Blue(string) }

  let x = Color.Blue("foo")
  match x {
    Color.Red => "bar",
    Color.Blue(c) => str_concat(c, "!"),
  }
}

OUTPUT:
string
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "EnumDef": {
          "def": {
            "name": "Color",
            "generics": [],
            "cons": [
              {
                "name": "Red",
                "fields": []
              },
              {
                "name": "Blue",
                "fields": [
                  {
                    "name": "field0",
                    "ann": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "ty": {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    }
                  }
                ]
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 34
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 4,
                    "col": 7
                  },
                  "end": {
                    "line": 4,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Color",
                "args": []
              }
            }
          },
          "value": {
            "Call": {
              "func": {
                "Var": {
                  "value": "Color.Blue",
                  "decl": {
                    "start": {
                      "line": 2,
                      "col": 3
                    },
                    "end": {
                      "line": 2,
                      "col": 34
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Fun": {
                      "args": [
                        {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        }
                      ],
                      "bounds": [],
                      "ret": {
                        "Con": {
                          "id": "Color",
                          "args": []
                        }
                      }
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 17
                    },
                    "end": {
                      "line": 4,
                      "col": 21
                    },
                    "file": 99
                  }
                }
              },
              "args": [
                {
                  "Literal": {
                    "lit": {
                      "String": {
                        "Single": "foo"
                      }
                    },
                    "ty": {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 22
                      },
                      "end": {
                        "line": 4,
                        "col": 27
                      },
                      "file": 99
                    }
                  }
                }
              ],
              "ty": {
                "Con": {
                  "id": "Color",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 21
                },
                "end": {
                  "line": 4,
                  "col": 27
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Color",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 4,
              "col": 27
            },
            "file": 99
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "x",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 7
                },
                "end": {
                  "line": 4,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Color",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 9
                },
                "end": {
                  "line": 5,
                  "col": 10
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Pat": {
                  "ident": "Color.Red",
                  "elems": [],
                  "ty": {
                    "Con": {
                      "id": "Color",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 5
                    },
                    "end": {
                      "line": 6,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "String": {
                      "Single": "bar"
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 18
                    },
                    "end": {
                      "line": 6,
                      "col": 23
                    },
                    "file": 99
                  }
                }
              }
            },
            {
              "pat": {
                "Pat": {
                  "ident": "Color.Blue",
                  "elems": [
                    {
                      "Type": {
                        "ident": "c",
                        "is_mut": false,
                        "ann": "Unknown",
                        "span": {
                          "start": {
                            "line": 7,
                            "col": 16
                          },
                          "end": {
                            "line": 7,
                            "col": 17
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Color",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 5
                    },
                    "end": {
                      "line": 7,
                      "col": 10
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Call": {
                  "func": {
                    "Var": {
                      "value": "str_concat",
                      "decl": {
                        "start": {
                          "line": 46,
                          "col": 1
                        },
                        "end": {
                          "line": 48,
                          "col": 1
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Fun": {
                          "args": [
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "id": "string",
                                "args": []
                              }
                            }
                          ],
                          "bounds": [],
                          "ret": {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        }
                      },
                      "span": {
                        "start": {
                          "line": 7,
                          "col": 22
                        },
                        "end": {
                          "line": 7,
                          "col": 32
                        },
                        "file": 99
                      }
                    }
                  },
                  "args": [
                    {
                      "Var": {
                        "value": "c",
                        "decl": {
                          "start": {
                            "line": 7,
                            "col": 16
                          },
                          "end": {
                            "line": 7,
                            "col": 17
                          },
                          "file": 99
                        },
                        "generics_instantiated": [],
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 7,
                            "col": 33
                          },
                          "end": {
                            "line": 7,
                            "col": 34
                          },
                          "file": 99
                        }
                      }
                    },
                    {
                      "Literal": {
                        "lit": {
                          "String": {
                            "Single": "!"
                          }
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 7,
                            "col": 36
                          },
                          "end": {
                            "line": 7,
                            "col": 39
                          },
                          "file": 99
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 32
                    },
                    "end": {
                      "line": 7,
                      "col": 39
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 3
            },
            "end": {
              "line": 8,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 9,
        "col": 1
      },
      "file": 99
    }
  }
}
