Plus operator works with strings

SOURCE:
"a" + "b"

OUTPUT:
string
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Literal": {
        "lit": {
          "String": {
            "Single": "a"
          }
        },
        "ty": {
          "Con": {
            "id": "string",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 4
          },
          "file": 99
        }
      }
    },
    "right": {
      "Literal": {
        "lit": {
          "String": {
            "Single": "b"
          }
        },
        "ty": {
          "Con": {
            "id": "string",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 7
          },
          "end": {
            "line": 1,
            "col": 10
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 10
      },
      "file": 99
    }
  }
}
