Plus operator works with strings

SOURCE:
"a" + "b"

OUTPUT:
string
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Literal": {
        "lit": {
          "String": [
            "a",
            null
          ]
        },
        "ty": {
          "Con": {
            "id": "string",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 0
          },
          "end": {
            "line": 1,
            "col": 3
          },
          "file": 99
        }
      }
    },
    "right": {
      "Literal": {
        "lit": {
          "String": [
            "b",
            null
          ]
        },
        "ty": {
          "Con": {
            "id": "string",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 6
          },
          "end": {
            "line": 1,
            "col": 9
          },
          "file": 99
        }
      }
    },
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 9
      },
      "file": 99
    }
  }
}
