Reference types

SOURCE:
{
  struct Bar { x: int }

  fn foo(a: *Bar) -> int {
    a.x
  }

  foo(&Bar{ x: 1 })
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Bar",
            "generics": [],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 23
            },
            "file": 99
          }
        }
      },
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "a",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 4,
                        "col": 10
                      },
                      "end": {
                        "line": 4,
                        "col": 11
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Ref",
                    "args": [
                      {
                        "Con": {
                          "name": "Bar",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "ty": {
                  "Con": {
                    "id": "Ref",
                    "args": [
                      {
                        "Con": {
                          "id": "Bar",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "FieldAccess": {
                      "expr": {
                        "Var": {
                          "value": "a",
                          "decl": {
                            "start": {
                              "line": 4,
                              "col": 10
                            },
                            "end": {
                              "line": 4,
                              "col": 11
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Con": {
                              "id": "Ref",
                              "args": [
                                {
                                  "Con": {
                                    "id": "Bar",
                                    "args": []
                                  }
                                }
                              ]
                            }
                          },
                          "span": {
                            "start": {
                              "line": 5,
                              "col": 5
                            },
                            "end": {
                              "line": 5,
                              "col": 6
                            },
                            "file": 99
                          }
                        }
                      },
                      "field": "x",
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 5,
                          "col": 7
                        },
                        "end": {
                          "line": 5,
                          "col": 8
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 4,
                    "col": 26
                  },
                  "end": {
                    "line": 6,
                    "col": 3
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Ref",
                        "args": [
                          {
                            "Con": {
                              "id": "Bar",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "Ref",
                    "args": [
                      {
                        "Con": {
                          "id": "Bar",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 6,
              "col": 3
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 3
                },
                "end": {
                  "line": 6,
                  "col": 3
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Ref",
                        "args": [
                          {
                            "Con": {
                              "id": "Bar",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 8,
                  "col": 3
                },
                "end": {
                  "line": 8,
                  "col": 6
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Reference": {
                "expr": {
                  "StructCall": {
                    "name": "Bar",
                    "fields": [
                      {
                        "name": "x",
                        "value": {
                          "Literal": {
                            "lit": {
                              "Int": 1
                            },
                            "ty": {
                              "Con": {
                                "id": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 8,
                                "col": 16
                              },
                              "end": {
                                "line": 8,
                                "col": 17
                              },
                              "file": 99
                            }
                          }
                        }
                      }
                    ],
                    "rest": null,
                    "ty": {
                      "Con": {
                        "id": "Bar",
                        "args": []
                      }
                    },
                    "span": {
                      "start": {
                        "line": 8,
                        "col": 11
                      },
                      "end": {
                        "line": 8,
                        "col": 18
                      },
                      "file": 99
                    }
                  }
                },
                "mutable": true,
                "ty": {
                  "Con": {
                    "id": "Ref",
                    "args": [
                      {
                        "Con": {
                          "id": "Bar",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 8,
                    "col": 7
                  },
                  "end": {
                    "line": 8,
                    "col": 18
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 8,
              "col": 6
            },
            "end": {
              "line": 8,
              "col": 19
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 9,
        "col": 1
      },
      "file": 99
    }
  }
}
