Return statements should unify.

SOURCE:
{
  fn foo() -> int {
    let x = 5
    return x
  }
}

OUTPUT:
fn () -> int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Let": {
                      "binding": {
                        "pat": {
                          "Type": {
                            "ident": "x",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 9
                              },
                              "end": {
                                "line": 3,
                                "col": 10
                              },
                              "file": 99
                            }
                          }
                        },
                        "ann": "Unknown",
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      },
                      "value": {
                        "Literal": {
                          "lit": {
                            "Int": 5
                          },
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 13
                            },
                            "end": {
                              "line": 3,
                              "col": 14
                            },
                            "file": 99
                          }
                        }
                      },
                      "mutable": false,
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 5
                        },
                        "end": {
                          "line": 3,
                          "col": 14
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Return": {
                      "expr": {
                        "Var": {
                          "value": "x",
                          "decl": {
                            "start": {
                              "line": 3,
                              "col": 9
                            },
                            "end": {
                              "line": 3,
                              "col": 10
                            },
                            "file": 99
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 12
                            },
                            "end": {
                              "line": 4,
                              "col": 13
                            },
                            "file": 99
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 5
                        },
                        "end": {
                          "line": 4,
                          "col": 13
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 19
                  },
                  "end": {
                    "line": 5,
                    "col": 3
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 5,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "id": "int",
            "args": []
          }
        }
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 6,
        "col": 1
      },
      "file": 99
    }
  }
}
