Return statements should unify.

SOURCE:
{
  fn foo() -> Int {
    let x = 5;
    return x
  }
}

OUTPUT:
fn () -> Int
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "Int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "Int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Let": {
                      "binding": {
                        "pat": {
                          "Type": {
                            "ident": "x",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 8
                              },
                              "end": {
                                "line": 3,
                                "col": 9
                              }
                            }
                          }
                        },
                        "ann": "Unknown",
                        "ty": {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        }
                      },
                      "value": {
                        "Literal": {
                          "lit": {
                            "Int": 5
                          },
                          "ty": {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 12
                            },
                            "end": {
                              "line": 3,
                              "col": 13
                            }
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 4
                        },
                        "end": {
                          "line": 3,
                          "col": 14
                        }
                      }
                    }
                  },
                  {
                    "Return": {
                      "expr": {
                        "Var": {
                          "value": "x",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 8
                              },
                              "end": {
                                "line": 3,
                                "col": 9
                              }
                            }
                          },
                          "ty": {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 4,
                              "col": 11
                            },
                            "end": {
                              "line": 4,
                              "col": 12
                            }
                          }
                        }
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 4
                        },
                        "end": {
                          "line": 4,
                          "col": 12
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 18
                  },
                  "end": {
                    "line": 5,
                    "col": 3
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Int",
                  "args": []
                }
              },
              "fx": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Int",
            "args": []
          }
        },
        "fx": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 6,
        "col": 1
      }
    }
  }
}
