Slice literals

SOURCE:
{ [1,2,3] }

OUTPUT:
[int]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Literal": {
          "lit": {
            "Slice": [
              {
                "Literal": {
                  "lit": {
                    "Int": 1
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 4
                    },
                    "end": {
                      "line": 1,
                      "col": 5
                    },
                    "file": 99
                  }
                }
              },
              {
                "Literal": {
                  "lit": {
                    "Int": 2
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 6
                    },
                    "end": {
                      "line": 1,
                      "col": 7
                    },
                    "file": 99
                  }
                }
              },
              {
                "Literal": {
                  "lit": {
                    "Int": 3
                  },
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 1,
                      "col": 8
                    },
                    "end": {
                      "line": 1,
                      "col": 9
                    },
                    "file": 99
                  }
                }
              }
            ]
          },
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 1,
              "col": 3
            },
            "end": {
              "line": 1,
              "col": 9
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "Slice",
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 11
      },
      "file": 99
    }
  }
}
