Slices are polymorphic

SOURCE:
{
  let x = [1,2,3]
  list_push(x, 4)
  ["hello"]
}

OUTPUT:
[string]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "x",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 7
                  },
                  "end": {
                    "line": 2,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Slice",
                "args": [
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "Literal": {
              "lit": {
                "Slice": [
                  {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 12
                        },
                        "end": {
                          "line": 2,
                          "col": 13
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 14
                        },
                        "end": {
                          "line": 2,
                          "col": 15
                        },
                        "file": 99
                      }
                    }
                  },
                  {
                    "Literal": {
                      "lit": {
                        "Int": 3
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 16
                        },
                        "end": {
                          "line": 2,
                          "col": 17
                        },
                        "file": 99
                      }
                    }
                  }
                ]
              },
              "ty": {
                "Con": {
                  "id": "Slice",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 11
                },
                "end": {
                  "line": 2,
                  "col": 17
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 17
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "list_push",
              "decl": {
                "start": {
                  "line": 24,
                  "col": 1
                },
                "end": {
                  "line": 26,
                  "col": 1
                },
                "file": 99
              },
              "generics_instantiated": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Slice",
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "Slice",
                      "args": [
                        {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        }
                      ]
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 3
                },
                "end": {
                  "line": 3,
                  "col": 12
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "Var": {
                "value": "x",
                "decl": {
                  "start": {
                    "line": 2,
                    "col": 7
                  },
                  "end": {
                    "line": 2,
                    "col": 8
                  },
                  "file": 99
                },
                "generics_instantiated": [],
                "ty": {
                  "Con": {
                    "id": "Slice",
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 13
                  },
                  "end": {
                    "line": 3,
                    "col": 14
                  },
                  "file": 99
                }
              }
            },
            {
              "Literal": {
                "lit": {
                  "Int": 4
                },
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 16
                  },
                  "end": {
                    "line": 3,
                    "col": 17
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 12
            },
            "end": {
              "line": 3,
              "col": 17
            },
            "file": 99
          }
        }
      },
      {
        "Literal": {
          "lit": {
            "Slice": [
              {
                "Literal": {
                  "lit": {
                    "String": {
                      "Single": "hello"
                    }
                  },
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 4
                    },
                    "end": {
                      "line": 4,
                      "col": 11
                    },
                    "file": 99
                  }
                }
              }
            ]
          },
          "ty": {
            "Con": {
              "id": "Slice",
              "args": [
                {
                  "Con": {
                    "id": "string",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 3
            },
            "end": {
              "line": 4,
              "col": 11
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "Slice",
        "args": [
          {
            "Con": {
              "id": "string",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 5,
        "col": 1
      },
      "file": 99
    }
  }
}
