Struct patterns

SOURCE:
{
  struct Foo { x: int, y: string }

  let f = Foo { x: 1, y: "a" };
  match f {
    Foo { x, y } => x
  }
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "y",
                "ann": {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 34
            },
            "file": 99
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "f",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 4,
                    "col": 6
                  },
                  "end": {
                    "line": 4,
                    "col": 7
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Foo",
                "args": []
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "x",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 19
                        },
                        "end": {
                          "line": 4,
                          "col": 20
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "y",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": [
                          "a",
                          null
                        ]
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 4,
                          "col": 25
                        },
                        "end": {
                          "line": 4,
                          "col": 28
                        },
                        "file": 99
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 4,
                  "col": 10
                },
                "end": {
                  "line": 4,
                  "col": 30
                },
                "file": 99
              }
            }
          },
          "ty": {
            "Con": {
              "id": "Foo",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 4,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 31
            },
            "file": 99
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "f",
              "decl": {
                "start": {
                  "line": 4,
                  "col": 6
                },
                "end": {
                  "line": 4,
                  "col": 7
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Foo",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 8
                },
                "end": {
                  "line": 5,
                  "col": 9
                },
                "file": 99
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Struct": {
                  "ident": "Foo",
                  "fields": [
                    {
                      "name": "x",
                      "value": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 10
                            },
                            "end": {
                              "line": 6,
                              "col": 11
                            },
                            "file": 99
                          }
                        }
                      }
                    },
                    {
                      "name": "y",
                      "value": {
                        "Type": {
                          "ident": "y",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 13
                            },
                            "end": {
                              "line": 6,
                              "col": 14
                            },
                            "file": 99
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "id": "Foo",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 4
                    },
                    "end": {
                      "line": 6,
                      "col": 16
                    },
                    "file": 99
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "x",
                  "decl": {
                    "start": {
                      "line": 6,
                      "col": 10
                    },
                    "end": {
                      "line": 6,
                      "col": 11
                    },
                    "file": 99
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 20
                    },
                    "end": {
                      "line": 6,
                      "col": 21
                    },
                    "file": 99
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 7,
              "col": 3
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 8,
        "col": 1
      },
      "file": 99
    }
  }
}
