Struct patterns on generic structs

SOURCE:
{
  struct Foo<T> { x: Int, y: List<T> }
  let a = Foo { x: 1, y: ["yo"] };

  match a {
    Foo { x: 1, y } => y,
    _ => ["asdf"],
  }
}

OUTPUT:
List<String>
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [
              "T"
            ],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "Int",
                    "args": []
                  }
                }
              },
              {
                "name": "y",
                "ann": {
                  "Con": {
                    "name": "List",
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "ty": {
                  "Con": {
                    "name": "List",
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              }
            ]
          },
          "is_trait": false,
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 38
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Foo",
                "args": [
                  {
                    "Con": {
                      "name": "String",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "x",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 19
                        },
                        "end": {
                          "line": 3,
                          "col": 20
                        }
                      }
                    }
                  }
                },
                {
                  "name": "y",
                  "value": {
                    "Literal": {
                      "lit": {
                        "List": [
                          {
                            "Literal": {
                              "lit": {
                                "String": "yo"
                              },
                              "ty": {
                                "Con": {
                                  "name": "String",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 26
                                },
                                "end": {
                                  "line": 3,
                                  "col": 30
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "List",
                          "args": [
                            {
                              "Con": {
                                "name": "String",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 25
                        },
                        "end": {
                          "line": 3,
                          "col": 31
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": [
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 10
                },
                "end": {
                  "line": 3,
                  "col": 33
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 34
            }
          }
        }
      },
      {
        "Match": {
          "subject": {
            "Var": {
              "value": "a",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              },
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": [
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 8
                },
                "end": {
                  "line": 5,
                  "col": 9
                }
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Struct": {
                  "ident": "Foo",
                  "fields": [
                    {
                      "name": "x",
                      "value": {
                        "Lit": {
                          "lit": {
                            "Int": 1
                          },
                          "ty": {
                            "Con": {
                              "name": "Int",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 13
                            },
                            "end": {
                              "line": 6,
                              "col": 14
                            }
                          }
                        }
                      }
                    },
                    {
                      "name": "y",
                      "value": {
                        "Type": {
                          "ident": "y",
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 16
                            },
                            "end": {
                              "line": 6,
                              "col": 17
                            }
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Foo",
                      "args": [
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 4
                    },
                    "end": {
                      "line": 6,
                      "col": 19
                    }
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "y",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 6,
                        "col": 16
                      },
                      "end": {
                        "line": 6,
                        "col": 17
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "List",
                      "args": [
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 6,
                      "col": 23
                    },
                    "end": {
                      "line": 6,
                      "col": 24
                    }
                  }
                }
              }
            },
            {
              "pat": {
                "Wild": {
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 4
                    },
                    "end": {
                      "line": 7,
                      "col": 5
                    }
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "List": [
                      {
                        "Literal": {
                          "lit": {
                            "String": "asdf"
                          },
                          "ty": {
                            "Con": {
                              "name": "String",
                              "args": []
                            }
                          },
                          "span": {
                            "start": {
                              "line": 7,
                              "col": 10
                            },
                            "end": {
                              "line": 7,
                              "col": 16
                            }
                          }
                        }
                      }
                    ]
                  },
                  "ty": {
                    "Con": {
                      "name": "List",
                      "args": [
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 7,
                      "col": 9
                    },
                    "end": {
                      "line": 7,
                      "col": 17
                    }
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "List",
              "args": [
                {
                  "Con": {
                    "name": "String",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 8,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "List",
        "args": [
          {
            "Con": {
              "name": "String",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 1
      }
    }
  }
}
