Tuples as return type.

SOURCE:
{
  fn foo() -> (string, bool) {
    ("foo", true)
  }
}

OUTPUT:
fn () -> (string, bool)
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [],
            "ret": {
              "Con": {
                "name": "Tuple2",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "name": "bool",
                      "args": []
                    }
                  }
                ]
              }
            },
            "ann": {
              "Con": {
                "name": "Tuple2",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "name": "bool",
                      "args": []
                    }
                  }
                ]
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "StructCall": {
                      "name": "Tuple2",
                      "fields": [
                        {
                          "name": "first",
                          "value": {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "foo",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 5
                                },
                                "end": {
                                  "line": 3,
                                  "col": 10
                                }
                              }
                            }
                          }
                        },
                        {
                          "name": "second",
                          "value": {
                            "Literal": {
                              "lit": {
                                "Bool": true
                              },
                              "ty": {
                                "Con": {
                                  "name": "bool",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 12
                                },
                                "end": {
                                  "line": 3,
                                  "col": 16
                                }
                              }
                            }
                          }
                        }
                      ],
                      "rest": null,
                      "ty": {
                        "Con": {
                          "name": "Tuple2",
                          "args": [
                            {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            },
                            {
                              "Con": {
                                "name": "bool",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 4
                        },
                        "end": {
                          "line": 3,
                          "col": 17
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "Tuple2",
                    "args": [
                      {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "name": "bool",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 29
                  },
                  "end": {
                    "line": 4,
                    "col": 3
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "Tuple2",
                      "args": [
                        {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "bool",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "bool",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Fun": {
        "args": [],
        "bounds": [],
        "ret": {
          "Con": {
            "name": "Tuple2",
            "args": [
              {
                "Con": {
                  "name": "string",
                  "args": []
                }
              },
              {
                "Con": {
                  "name": "bool",
                  "args": []
                }
              }
            ]
          }
        },
        "id": -1
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 5,
        "col": 1
      }
    }
  }
}
