Tuple patterns

SOURCE:
{
  fn foo((x, y): (int, string)) -> int { x }
  foo((1, "a"))
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "args": [
              {
                "pat": {
                  "Struct": {
                    "ident": "Tuple2",
                    "fields": [
                      {
                        "name": "first",
                        "value": {
                          "Type": {
                            "ident": "x",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 10
                              },
                              "end": {
                                "line": 2,
                                "col": 11
                              },
                              "file": 99
                            }
                          }
                        }
                      },
                      {
                        "name": "second",
                        "value": {
                          "Type": {
                            "ident": "y",
                            "is_mut": false,
                            "ann": "Unknown",
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 13
                              },
                              "end": {
                                "line": 2,
                                "col": 14
                              },
                              "file": 99
                            }
                          }
                        }
                      }
                    ],
                    "ty": {
                      "Con": {
                        "id": "Tuple2",
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        ]
                      }
                    },
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 9
                      },
                      "end": {
                        "line": 2,
                        "col": 15
                      },
                      "file": 99
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "Tuple2",
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "ty": {
                  "Con": {
                    "id": "Tuple2",
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Var": {
                      "value": "x",
                      "decl": {
                        "start": {
                          "line": 2,
                          "col": 10
                        },
                        "end": {
                          "line": 2,
                          "col": 11
                        },
                        "file": 99
                      },
                      "generics_instantiated": [],
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 41
                        },
                        "end": {
                          "line": 2,
                          "col": 42
                        },
                        "file": 99
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 39
                  },
                  "end": {
                    "line": 2,
                    "col": 44
                  },
                  "file": 99
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Tuple2",
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Con": {
                    "id": "Tuple2",
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      }
                    ]
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "id": "int",
                  "args": []
                }
              }
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 44
            },
            "file": 99
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 2
                },
                "end": {
                  "line": 2,
                  "col": 44
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Con": {
                        "id": "Tuple2",
                        "args": [
                          {
                            "Con": {
                              "id": "int",
                              "args": []
                            }
                          },
                          {
                            "Con": {
                              "id": "string",
                              "args": []
                            }
                          }
                        ]
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  }
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 5
                },
                "file": 99
              }
            }
          },
          "args": [
            {
              "StructCall": {
                "name": "Tuple2",
                "fields": [
                  {
                    "name": "first",
                    "value": {
                      "Literal": {
                        "lit": {
                          "Int": 1
                        },
                        "ty": {
                          "Con": {
                            "id": "int",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 3,
                            "col": 7
                          },
                          "end": {
                            "line": 3,
                            "col": 8
                          },
                          "file": 99
                        }
                      }
                    }
                  },
                  {
                    "name": "second",
                    "value": {
                      "Literal": {
                        "lit": {
                          "String": [
                            "a",
                            null
                          ]
                        },
                        "ty": {
                          "Con": {
                            "id": "string",
                            "args": []
                          }
                        },
                        "span": {
                          "start": {
                            "line": 3,
                            "col": 10
                          },
                          "end": {
                            "line": 3,
                            "col": 13
                          },
                          "file": 99
                        }
                      }
                    }
                  }
                ],
                "rest": null,
                "ty": {
                  "Con": {
                    "id": "Tuple2",
                    "args": [
                      {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 14
                  },
                  "file": 99
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 15
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      },
      "file": 99
    }
  }
}
