Tuples.

SOURCE:
(1, 2)

OUTPUT:
(int, int)
---
No errors.
---
{
  "StructCall": {
    "name": "Tuple2",
    "fields": [
      {
        "name": "first",
        "value": {
          "Literal": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 1
              },
              "end": {
                "line": 1,
                "col": 2
              }
            }
          }
        }
      },
      {
        "name": "second",
        "value": {
          "Literal": {
            "lit": {
              "Int": 2
            },
            "ty": {
              "Con": {
                "name": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 4
              },
              "end": {
                "line": 1,
                "col": 5
              }
            }
          }
        }
      }
    ],
    "rest": null,
    "ty": {
      "Con": {
        "name": "Tuple2",
        "args": [
          {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          {
            "Con": {
              "name": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 1,
        "col": 6
      }
    }
  }
}
