Tuples.

SOURCE:
(1, 2)

OUTPUT:
(int, int)
---
No errors.
---
{
  "StructCall": {
    "name": "Tuple2",
    "fields": [
      {
        "name": "first",
        "value": {
          "Literal": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 2
              },
              "end": {
                "line": 1,
                "col": 3
              },
              "file": 99
            }
          }
        }
      },
      {
        "name": "second",
        "value": {
          "Literal": {
            "lit": {
              "Int": 2
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 1,
                "col": 5
              },
              "end": {
                "line": 1,
                "col": 6
              },
              "file": 99
            }
          }
        }
      }
    ],
    "rest": null,
    "ty": {
      "Con": {
        "id": "Tuple2",
        "args": [
          {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          {
            "Con": {
              "id": "int",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 1,
        "col": 6
      },
      "file": 99
    }
  }
}
