Tuple fields

SOURCE:
{
  let a = (1, "a");
  a.0
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Tuple2",
                "args": [
                  {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Tuple2",
              "fields": [
                {
                  "name": "first",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 11
                        },
                        "end": {
                          "line": 2,
                          "col": 12
                        }
                      }
                    }
                  }
                },
                {
                  "name": "second",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": [
                          "a",
                          null
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 14
                        },
                        "end": {
                          "line": 2,
                          "col": 17
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 10
                },
                "end": {
                  "line": 2,
                  "col": 18
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Tuple2",
              "args": [
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 19
            }
          }
        }
      },
      {
        "FieldAccess": {
          "expr": {
            "Var": {
              "value": "a",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 6
                  },
                  "end": {
                    "line": 2,
                    "col": 7
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "name": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 2
                },
                "end": {
                  "line": 3,
                  "col": 3
                }
              }
            }
          },
          "field": "first",
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 5
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 4,
        "col": 1
      }
    }
  }
}
