Tuple fields II

SOURCE:
{
  struct Foo<T> { x: int, y: [T] }
  let a = Foo { x: 1, y: ["yo"] };

  a.x as int;
  a.y
}

OUTPUT:
[string]
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "StructDef": {
          "def": {
            "name": "Foo",
            "generics": [
              "T"
            ],
            "fields": [
              {
                "name": "x",
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "name": "int",
                      "args": []
                    }
                  }
                }
              },
              {
                "name": "y",
                "ann": {
                  "Con": {
                    "name": "Slice",
                    "args": [
                      {
                        "Con": {
                          "name": "T",
                          "args": []
                        }
                      }
                    ]
                  }
                },
                "ty": {
                  "generics": [],
                  "ty": {
                    "Con": {
                      "name": "Slice",
                      "args": [
                        {
                          "Con": {
                            "name": "T",
                            "args": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            ]
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 2,
              "col": 34
            }
          }
        }
      },
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "name": "Foo",
                "args": [
                  {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Foo",
              "fields": [
                {
                  "name": "x",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 19
                        },
                        "end": {
                          "line": 3,
                          "col": 20
                        }
                      }
                    }
                  }
                },
                {
                  "name": "y",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Slice": [
                          {
                            "Literal": {
                              "lit": {
                                "String": [
                                  "yo",
                                  null
                                ]
                              },
                              "ty": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "span": {
                                "start": {
                                  "line": 3,
                                  "col": 26
                                },
                                "end": {
                                  "line": 3,
                                  "col": 30
                                }
                              }
                            }
                          }
                        ]
                      },
                      "ty": {
                        "Con": {
                          "name": "Slice",
                          "args": [
                            {
                              "Con": {
                                "name": "string",
                                "args": []
                              }
                            }
                          ]
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 25
                        },
                        "end": {
                          "line": 3,
                          "col": 31
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": [
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 10
                },
                "end": {
                  "line": 3,
                  "col": 33
                }
              }
            }
          },
          "ty": {
            "Con": {
              "name": "Foo",
              "args": [
                {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 2
            },
            "end": {
              "line": 3,
              "col": 34
            }
          }
        }
      },
      {
        "CheckType": {
          "expr": {
            "FieldAccess": {
              "expr": {
                "Var": {
                  "value": "a",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 3,
                        "col": 6
                      },
                      "end": {
                        "line": 3,
                        "col": 7
                      }
                    }
                  },
                  "generics_instantiated": [],
                  "ty": {
                    "Con": {
                      "name": "Foo",
                      "args": [
                        {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 5,
                      "col": 2
                    },
                    "end": {
                      "line": 5,
                      "col": 3
                    }
                  }
                }
              },
              "field": "x",
              "ty": {
                "Con": {
                  "name": "int",
                  "args": []
                }
              },
              "span": {
                "start": {
                  "line": 5,
                  "col": 2
                },
                "end": {
                  "line": 5,
                  "col": 5
                }
              }
            }
          },
          "ann": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "ty": {
            "Con": {
              "name": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 5,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 12
            }
          }
        }
      },
      {
        "FieldAccess": {
          "expr": {
            "Var": {
              "value": "a",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 3,
                    "col": 6
                  },
                  "end": {
                    "line": 3,
                    "col": 7
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "name": "Foo",
                  "args": [
                    {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 2
                },
                "end": {
                  "line": 6,
                  "col": 3
                }
              }
            }
          },
          "field": "y",
          "ty": {
            "Con": {
              "name": "Slice",
              "args": [
                {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 5
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "Slice",
        "args": [
          {
            "Con": {
              "name": "string",
              "args": []
            }
          }
        ]
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 7,
        "col": 1
      }
    }
  }
}
