Tuple patterns in match arms

SOURCE:
{
  match (2, "b") {
    (_, y) => y,
    _ => "c",
  }
}

OUTPUT:
String
---
No errors.
---
[]
---
{
  "Block": {
    "stmts": [
      {
        "Match": {
          "subject": {
            "StructCall": {
              "name": "Tuple2",
              "fields": [
                {
                  "name": "first",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 2
                      },
                      "ty": {
                        "Con": {
                          "name": "Int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 9
                        },
                        "end": {
                          "line": 2,
                          "col": 10
                        }
                      }
                    }
                  }
                },
                {
                  "name": "second",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": "b"
                      },
                      "ty": {
                        "Con": {
                          "name": "String",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 12
                        },
                        "end": {
                          "line": 2,
                          "col": 15
                        }
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "name": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "name": "Int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "name": "String",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 8
                },
                "end": {
                  "line": 2,
                  "col": 16
                }
              }
            }
          },
          "arms": [
            {
              "pat": {
                "Struct": {
                  "ident": "Tuple2",
                  "fields": [
                    {
                      "name": "first",
                      "value": {
                        "Wild": {
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 5
                            },
                            "end": {
                              "line": 3,
                              "col": 6
                            }
                          }
                        }
                      }
                    },
                    {
                      "name": "second",
                      "value": {
                        "Type": {
                          "ident": "y",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 8
                            },
                            "end": {
                              "line": 3,
                              "col": 9
                            }
                          }
                        }
                      }
                    }
                  ],
                  "ty": {
                    "Con": {
                      "name": "Tuple2",
                      "args": [
                        {
                          "Con": {
                            "name": "Int",
                            "args": []
                          }
                        },
                        {
                          "Con": {
                            "name": "String",
                            "args": []
                          }
                        }
                      ]
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 4
                    },
                    "end": {
                      "line": 3,
                      "col": 10
                    }
                  }
                }
              },
              "expr": {
                "Var": {
                  "value": "y",
                  "decl": {
                    "file_id": {
                      "package": "dummy",
                      "filename": "dummy"
                    },
                    "span": {
                      "start": {
                        "line": 3,
                        "col": 8
                      },
                      "end": {
                        "line": 3,
                        "col": 9
                      }
                    }
                  },
                  "ty": {
                    "Con": {
                      "name": "String",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 3,
                      "col": 14
                    },
                    "end": {
                      "line": 3,
                      "col": 15
                    }
                  }
                }
              }
            },
            {
              "pat": {
                "Wild": {
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 4
                    },
                    "end": {
                      "line": 4,
                      "col": 5
                    }
                  }
                }
              },
              "expr": {
                "Literal": {
                  "lit": {
                    "String": "c"
                  },
                  "ty": {
                    "Con": {
                      "name": "String",
                      "args": []
                    }
                  },
                  "span": {
                    "start": {
                      "line": 4,
                      "col": 9
                    },
                    "end": {
                      "line": 4,
                      "col": 12
                    }
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "String",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 5,
              "col": 3
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "String",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 6,
        "col": 1
      }
    }
  }
}
