Tuple fields

SOURCE:
{
  let a = (1, "a")
  a.0
}

OUTPUT:
int
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "is_mut": false,
                "ann": "Unknown",
                "span": {
                  "start": {
                    "line": 2,
                    "col": 7
                  },
                  "end": {
                    "line": 2,
                    "col": 8
                  },
                  "file": 99
                }
              }
            },
            "ann": "Unknown",
            "ty": {
              "Con": {
                "id": "Tuple2",
                "args": [
                  {
                    "Con": {
                      "id": "int",
                      "args": []
                    }
                  },
                  {
                    "Con": {
                      "id": "string",
                      "args": []
                    }
                  }
                ]
              }
            }
          },
          "value": {
            "StructCall": {
              "name": "Tuple2",
              "fields": [
                {
                  "name": "first",
                  "value": {
                    "Literal": {
                      "lit": {
                        "Int": 1
                      },
                      "ty": {
                        "Con": {
                          "id": "int",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 12
                        },
                        "end": {
                          "line": 2,
                          "col": 13
                        },
                        "file": 99
                      }
                    }
                  }
                },
                {
                  "name": "second",
                  "value": {
                    "Literal": {
                      "lit": {
                        "String": {
                          "Single": "a"
                        }
                      },
                      "ty": {
                        "Con": {
                          "id": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 2,
                          "col": 15
                        },
                        "end": {
                          "line": 2,
                          "col": 18
                        },
                        "file": 99
                      }
                    }
                  }
                }
              ],
              "rest": null,
              "ty": {
                "Con": {
                  "id": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 2,
                  "col": 11
                },
                "end": {
                  "line": 2,
                  "col": 18
                },
                "file": 99
              }
            }
          },
          "mutable": false,
          "ty": {
            "Con": {
              "id": "Tuple2",
              "args": [
                {
                  "Con": {
                    "id": "int",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "id": "string",
                    "args": []
                  }
                }
              ]
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 3
            },
            "end": {
              "line": 2,
              "col": 18
            },
            "file": 99
          }
        }
      },
      {
        "FieldAccess": {
          "expr": {
            "Var": {
              "value": "a",
              "decl": {
                "start": {
                  "line": 2,
                  "col": 7
                },
                "end": {
                  "line": 2,
                  "col": 8
                },
                "file": 99
              },
              "generics_instantiated": [],
              "ty": {
                "Con": {
                  "id": "Tuple2",
                  "args": [
                    {
                      "Con": {
                        "id": "int",
                        "args": []
                      }
                    },
                    {
                      "Con": {
                        "id": "string",
                        "args": []
                      }
                    }
                  ]
                }
              },
              "span": {
                "start": {
                  "line": 3,
                  "col": 3
                },
                "end": {
                  "line": 3,
                  "col": 4
                },
                "file": 99
              }
            }
          },
          "field": "first",
          "ty": {
            "Con": {
              "id": "int",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 3,
              "col": 5
            },
            "end": {
              "line": 3,
              "col": 6
            },
            "file": 99
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 4,
        "col": 1
      },
      "file": 99
    }
  }
}
