Typing callbacks.

SOURCE:
{
  fn foo( f: fn (i: int) -> string, x: int ) -> string {
    f(x)
  }

  foo(|x| int_to_string(x), 1)
}

OUTPUT:
string
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Closure": {
          "fun": {
            "name": "foo",
            "generics": [],
            "bounds": [],
            "args": [
              {
                "pat": {
                  "Type": {
                    "ident": "f",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 10
                      },
                      "end": {
                        "line": 2,
                        "col": 11
                      }
                    }
                  }
                },
                "ann": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    }
                  }
                },
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                }
              },
              {
                "pat": {
                  "Type": {
                    "ident": "x",
                    "is_mut": false,
                    "ann": "Unknown",
                    "span": {
                      "start": {
                        "line": 2,
                        "col": 36
                      },
                      "end": {
                        "line": 2,
                        "col": 37
                      }
                    }
                  }
                },
                "ann": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              }
            ],
            "ret": {
              "Con": {
                "name": "string",
                "args": []
              }
            },
            "ann": {
              "Con": {
                "name": "string",
                "args": []
              }
            },
            "body": {
              "Block": {
                "stmts": [
                  {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "f",
                          "decl": {
                            "file_id": {
                              "package": "dummy",
                              "filename": "dummy"
                            },
                            "span": {
                              "start": {
                                "line": 2,
                                "col": 10
                              },
                              "end": {
                                "line": 2,
                                "col": 11
                              }
                            }
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          },
                          "span": {
                            "start": {
                              "line": 3,
                              "col": 4
                            },
                            "end": {
                              "line": 3,
                              "col": 5
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "x",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 2,
                                  "col": 36
                                },
                                "end": {
                                  "line": 2,
                                  "col": 37
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 3,
                                "col": 6
                              },
                              "end": {
                                "line": 3,
                                "col": 7
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 3,
                          "col": 4
                        },
                        "end": {
                          "line": 3,
                          "col": 8
                        }
                      }
                    }
                  }
                ],
                "ty": {
                  "Con": {
                    "name": "string",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 55
                  },
                  "end": {
                    "line": 4,
                    "col": 3
                  }
                }
              }
            },
            "bounded_ty": {
              "generics": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    },
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "id": -1
                }
              }
            }
          },
          "kind": "Inline",
          "ty": {
            "Fun": {
              "args": [
                {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ],
              "bounds": [],
              "ret": {
                "Con": {
                  "name": "string",
                  "args": []
                }
              },
              "id": -1
            }
          },
          "span": {
            "start": {
              "line": 2,
              "col": 2
            },
            "end": {
              "line": 4,
              "col": 3
            }
          }
        }
      },
      {
        "Call": {
          "func": {
            "Var": {
              "value": "foo",
              "decl": {
                "file_id": {
                  "package": "dummy",
                  "filename": "dummy"
                },
                "span": {
                  "start": {
                    "line": 2,
                    "col": 2
                  },
                  "end": {
                    "line": 4,
                    "col": 3
                  }
                }
              },
              "generics_instantiated": [],
              "ty": {
                "Fun": {
                  "args": [
                    {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Con": {
                            "name": "string",
                            "args": []
                          }
                        },
                        "id": -1
                      }
                    },
                    {
                      "Con": {
                        "name": "int",
                        "args": []
                      }
                    }
                  ],
                  "bounds": [],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "id": -1
                }
              },
              "span": {
                "start": {
                  "line": 6,
                  "col": 2
                },
                "end": {
                  "line": 6,
                  "col": 5
                }
              }
            }
          },
          "args": [
            {
              "Closure": {
                "fun": {
                  "name": "__anonymous",
                  "generics": [],
                  "bounds": [],
                  "args": [
                    {
                      "pat": {
                        "Type": {
                          "ident": "x",
                          "is_mut": false,
                          "ann": "Unknown",
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 7
                            },
                            "end": {
                              "line": 6,
                              "col": 8
                            }
                          }
                        }
                      },
                      "ann": "Unknown",
                      "ty": {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    }
                  ],
                  "ret": {
                    "Con": {
                      "name": "string",
                      "args": []
                    }
                  },
                  "ann": "Unknown",
                  "body": {
                    "Call": {
                      "func": {
                        "Var": {
                          "value": "int_to_string",
                          "decl": {
                            "file_id": {
                              "package": "std",
                              "filename": "builtin.brg"
                            },
                            "span": {
                              "start": {
                                "line": 0,
                                "col": 0
                              },
                              "end": {
                                "line": 0,
                                "col": 0
                              }
                            }
                          },
                          "generics_instantiated": [],
                          "ty": {
                            "Fun": {
                              "args": [
                                {
                                  "Con": {
                                    "name": "int",
                                    "args": []
                                  }
                                }
                              ],
                              "bounds": [],
                              "ret": {
                                "Con": {
                                  "name": "string",
                                  "args": []
                                }
                              },
                              "id": -1
                            }
                          },
                          "span": {
                            "start": {
                              "line": 6,
                              "col": 10
                            },
                            "end": {
                              "line": 6,
                              "col": 23
                            }
                          }
                        }
                      },
                      "args": [
                        {
                          "Var": {
                            "value": "x",
                            "decl": {
                              "file_id": {
                                "package": "dummy",
                                "filename": "dummy"
                              },
                              "span": {
                                "start": {
                                  "line": 6,
                                  "col": 7
                                },
                                "end": {
                                  "line": 6,
                                  "col": 8
                                }
                              }
                            },
                            "generics_instantiated": [],
                            "ty": {
                              "Con": {
                                "name": "int",
                                "args": []
                              }
                            },
                            "span": {
                              "start": {
                                "line": 6,
                                "col": 24
                              },
                              "end": {
                                "line": 6,
                                "col": 25
                              }
                            }
                          }
                        }
                      ],
                      "ty": {
                        "Con": {
                          "name": "string",
                          "args": []
                        }
                      },
                      "span": {
                        "start": {
                          "line": 6,
                          "col": 10
                        },
                        "end": {
                          "line": 6,
                          "col": 26
                        }
                      }
                    }
                  },
                  "bounded_ty": {
                    "generics": [],
                    "ty": {
                      "Fun": {
                        "args": [
                          {
                            "Con": {
                              "name": "int",
                              "args": []
                            }
                          }
                        ],
                        "bounds": [],
                        "ret": {
                          "Var": 99
                        },
                        "id": -1
                      }
                    }
                  }
                },
                "kind": "Lambda",
                "ty": {
                  "Fun": {
                    "args": [
                      {
                        "Con": {
                          "name": "int",
                          "args": []
                        }
                      }
                    ],
                    "bounds": [],
                    "ret": {
                      "Con": {
                        "name": "string",
                        "args": []
                      }
                    },
                    "id": -1
                  }
                },
                "span": {
                  "start": {
                    "line": 6,
                    "col": 6
                  },
                  "end": {
                    "line": 6,
                    "col": 26
                  }
                }
              }
            },
            {
              "Literal": {
                "lit": {
                  "Int": 1
                },
                "ty": {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                },
                "span": {
                  "start": {
                    "line": 6,
                    "col": 28
                  },
                  "end": {
                    "line": 6,
                    "col": 29
                  }
                }
              }
            }
          ],
          "ty": {
            "Con": {
              "name": "string",
              "args": []
            }
          },
          "span": {
            "start": {
              "line": 6,
              "col": 2
            },
            "end": {
              "line": 6,
              "col": 30
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "name": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 7,
        "col": 1
      }
    }
  }
}
