Unit pattern match arm

SOURCE:
match () {
  () => 1,
}

OUTPUT:
int
---
No errors.
---
{
  "Match": {
    "subject": {
      "Unit": {
        "ty": {
          "Con": {
            "id": "Unit",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 7
          },
          "end": {
            "line": 1,
            "col": 8
          },
          "file": 99
        }
      }
    },
    "arms": [
      {
        "pat": {
          "Unit": {
            "ty": {
              "Con": {
                "id": "Unit",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 3
              },
              "end": {
                "line": 2,
                "col": 4
              },
              "file": 99
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 9
              },
              "end": {
                "line": 2,
                "col": 10
              },
              "file": 99
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "int",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 3,
        "col": 1
      },
      "file": 99
    }
  }
}
