Wildcard matches.

SOURCE:
match 1 {
  1 => "foo",
  _ => "foo",
}

OUTPUT:
string
---
No errors.
---
{
  "Match": {
    "subject": {
      "Literal": {
        "lit": {
          "Int": 1
        },
        "ty": {
          "Con": {
            "id": "int",
            "args": []
          }
        },
        "span": {
          "start": {
            "line": 1,
            "col": 7
          },
          "end": {
            "line": 1,
            "col": 8
          },
          "file": 99
        }
      }
    },
    "arms": [
      {
        "pat": {
          "Lit": {
            "lit": {
              "Int": 1
            },
            "ty": {
              "Con": {
                "id": "int",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 3
              },
              "end": {
                "line": 2,
                "col": 4
              },
              "file": 99
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "String": {
                "Single": "foo"
              }
            },
            "ty": {
              "Con": {
                "id": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 2,
                "col": 8
              },
              "end": {
                "line": 2,
                "col": 13
              },
              "file": 99
            }
          }
        }
      },
      {
        "pat": {
          "Wild": {
            "span": {
              "start": {
                "line": 3,
                "col": 3
              },
              "end": {
                "line": 3,
                "col": 4
              },
              "file": 99
            }
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "String": {
                "Single": "foo"
              }
            },
            "ty": {
              "Con": {
                "id": "string",
                "args": []
              }
            },
            "span": {
              "start": {
                "line": 3,
                "col": 8
              },
              "end": {
                "line": 3,
                "col": 13
              },
              "file": 99
            }
          }
        }
      }
    ],
    "ty": {
      "Con": {
        "id": "string",
        "args": []
      }
    },
    "span": {
      "start": {
        "line": 1,
        "col": 1
      },
      "end": {
        "line": 4,
        "col": 1
      },
      "file": 99
    }
  }
}
