Early returns in blocks.

SOURCE:
fn foo() -> Int {
  {
    return 5;
  }

  999
}

fn borgo_main() {
  foo().assert_eq(5);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func foo() any {

	{

		return 5

		return 999
	}
}
func borgo_main() any {

	{

		return Debug_assert_eq(foo(), 5)
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("foo", foo)
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
