Exhaustiveness checking on bools

SOURCE:
fn borgo_main() {
  let x = match false {
    true => unreachable!(),
    false => 2,
  };
  x.assert_eq(2);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	var var1_block any
	{
		var2 := false
		var var3_result any
		var4_subject := var2
		var5_matches := 0

		if var5_matches != 2 {
			var5_matches = 0

			var6 := true

			if var5_matches != 1 && borgo.Ops.Eq(var6, var4_subject).(bool) {
				var5_matches = 2
			} else {
				var5_matches = 1
			}
			_ = var4_subject

			if var5_matches == 2 {
				var7 := Debug_unreachable()
				var3_result = var7
			}
		}

		if var5_matches != 2 {
			var5_matches = 0

			var8 := false

			if var5_matches != 1 && borgo.Ops.Eq(var8, var4_subject).(bool) {
				var5_matches = 2
			} else {
				var5_matches = 1
			}
			_ = var4_subject

			if var5_matches == 2 {
				var9 := 2
				var3_result = var9
			}
		}

		var10 := var3_result
		var11 := borgo.Unit
		_ = var11
		var12 := var10
		var13 := 2
		var14 := Debug_assert_eq
		var15 := var14(var12, var13)
		var1_block = var15
	}
	return var1_block
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
