Hashing with Hash trait

SOURCE:
fn borgo_main() {
  let a = "yo";
  let b = "y".append("o");

  a.to_hash().assert_eq(b.to_hash());
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	{

		var a any = "yo"

		var b any = String_append("y", "o")

		return Debug_assert_eq(String_to_hash(a), String_to_hash(b))
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
