If statements

SOURCE:
fn borgo_main() {
  let x = if true { 6 } else { 0 };
  x.assert_eq(6);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	{
		var var1 any
		_ = var1

		if borgo.Ops.Eq(true, true).(bool) {

			var1 = 6
		} else {

			var1 = 0
		}
		var x any = var1

		return Debug_assert_eq(x, 6)
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
