Lists

SOURCE:
fn main() {
  let mut x = [1, 2, 5 + 5];

  inspect(x);
  assert_eq(x.len(), 3);
  assert_eq(x[1], 2);

  x[1] = 8;
  assert_eq(x[1], 8);

  x = x.append(9);
  assert_eq(x[3], 9);
}

OUTPUT:
[1 2 10]

---
package main

func main() {
	x := []int{1, 2, 5 + 5}

	inspect[[]int](x)

	assert_eq[int](Slice_len[int](x), 3)

	assert_eq[int](x[1], 2)

	x[1] = 8

	assert_eq[int](x[1], 8)

	x = Slice_append[int](x, 9)

	assert_eq[int](x[3], 9)
}
