Mutating vars

SOURCE:
fn foo(a: int) -> int {
  loop {
    if a > 5 { break }
    a = a + 1
  }

  a
}

fn main() {
  let mut x = 1
  x = x + 3
  assert_eq(x, 4)

  {
    let x = 5
    assert_eq(x, 5)
  }

  assert_eq(foo(0), 6)

  // TODO this doesn't type check :/
  // x = x + 6
  // x.assert_eq(10)
}

OUTPUT:

---
package main

func foo(a int) int {
	for {

		if a > 5 {
			break
		}

		a = a + 1
	}

	return a
}

func main() {
	x := 1

	x = x + 3

	assert_eq[int](x, 4)
	{

		x := 5

		assert_eq[int](x, 5)
	}

	assert_eq[int](foo(0), 6)
}
