Newlines in strings

SOURCE:
fn borgo_main() {
  let s = "a
b
c";

  let s = s.split("\n");
  s.to_list().assert_eq(["a", "b", "c"]);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	{

		var s any = "a\nb\nc"

		s = String_split(s, "\n")

		return Debug_assert_eq(Seq_to_list(s), borgo.List("a", "b", "c"))
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
