Rebind variables

SOURCE:
fn borgo_main() {
  let x = 1;
  x.assert_eq(1);

  let x = 1 + 1;
  x.assert_eq(2);

  {
    let x = x + 5;
    x.assert_eq(7);
  }

  x.assert_eq(2);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	{

		var x any = 1

		Debug_assert_eq(x, 1)

		x = borgo.Ops.IAdd(1, 1)

		Debug_assert_eq(x, 2)
		{

			var x any = borgo.Ops.IAdd(x, 5)

			Debug_assert_eq(x, 7)
		}

		return Debug_assert_eq(x, 2)
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
