Rebind variables

SOURCE:
fn borgo_main() {
  let x = 1;
  x.assert_eq(1);

  let x = 1 + 1;
  x.assert_eq(2);

  {
    let x = x + 5;
    x.assert_eq(7);
  }

  x.assert_eq(2);
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	var var1_block any
	{
		var2 := 1
		var3 := var2
		var4 := borgo.Unit
		_ = var4
		var5 := var3
		var6 := 1
		var7 := Debug_assert_eq
		var8 := var7(var5, var6)
		_ = var8
		var9 := 1
		var10 := 1
		var11 := borgo.Ops.IAdd
		var12 := var11(var9, var10)
		var13 := var12
		var14 := borgo.Unit
		_ = var14
		var15 := var13
		var16 := 2
		var17 := Debug_assert_eq
		var18 := var17(var15, var16)
		_ = var18
		var var19_block any
		{
			var20 := var13
			var21 := 5
			var22 := borgo.Ops.IAdd
			var23 := var22(var20, var21)
			var24 := var23
			var25 := borgo.Unit
			_ = var25
			var26 := var24
			var27 := 7
			var28 := Debug_assert_eq
			var29 := var28(var26, var27)
			var19_block = var29
		}
		_ = var19_block
		var30 := var13
		var31 := 2
		var32 := Debug_assert_eq
		var33 := var32(var30, var31)
		var1_block = var33
	}
	return var1_block
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
