Records have stable field order.

SOURCE:
struct Foo { x: int, y: string }

fn main() {
    inspect((1, "a", true))
    inspect(Foo { x: 1, y: "b" })
}

OUTPUT:
{first:1 second:a third:true}
{x:1 y:b}

---
package main

type Foo struct {
	x int
	y string
}

func main() {
	inspect[Tuple3[int, string, bool]](Tuple3[int, string, bool]{
		first:  1,
		second: "a",
		third:  true,
	})

	inspect[Foo](Foo{
		x: 1,
		y: "b",
	})
}
