Recursion across files

SOURCE:
file: a.brg
fn a(n: int) -> int {
  if n == 100 {
    return n
  }

  b(n + 10)
}

file: b.brg
fn b(n: int) -> int {
  if n == 200 {
    return n
  }

  a(n + 20)
}

file: main.brg
fn main() { assert_eq(a(40), 100) }

OUTPUT:

---
package main

func b(n int) int {
	if n == 200 {
		return n
	}

	return a(n + 20)
}

func a(n int) int {
	if n == 100 {
		return n
	}

	return b(n + 10)
}

func main() {
	assert_eq[int](a(40), 100)
}
