Recursive functions are supported in files.

SOURCE:
file: main.brg

fn foo(n: Int) -> Int {
  if n != 5 {
    return foo(n + 1)
  }

  n
}

fn borgo_main() {
  foo(1).assert_eq(5)
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func foo(n any) any {

	{

		if borgo.Ops.Eq(borgo.Ops.Ne(n, 5), true).(bool) {

			return foo(borgo.Ops.IAdd(n, 1))

		}

		return n
	}
}
func borgo_main() any {

	{

		return Debug_assert_eq(foo(1), 5)
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("foo", foo)
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
