String parsing

SOURCE:
fn borgo_main() {
  "2".parse_int().assert_eq(Some(2));
  "abc".parse_int().assert_eq(None);
  "3.4".parse_float().assert_eq(Some(3.4));
}

OUTPUT:

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	{

		Debug_assert_eq(String_parse_int("2"), make_Option_Some(2))

		Debug_assert_eq(String_parse_int("abc"), make_Option_None)

		return Debug_assert_eq(String_parse_float("3.4"), make_Option_Some(3.4))
	}
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
