Struct access

SOURCE:
struct Foo {
    a: int,
    b: string,
    c: bool,
}

fn main() {
    let x = Foo { a: 1, b: "hi", c: true }
    assert_eq(x.a, 1)
    let y = Foo { a: 5, c: false, ..x }
    assert_eq(y.a, 5)
    assert_eq(x.a, 1)
}

OUTPUT:

---
package main

type Foo struct {
	a int
	b string
	c bool
}

func main() {
	x := Foo{
		a: 1,
		b: "hi",
		c: true,
	}

	assert_eq[int](x.a, 1)

	y := func(data Foo) Foo {
		data.a = 5
		data.c = false
		return data
	}(x)

	assert_eq[int](y.a, 5)

	assert_eq[int](x.a, 1)
}
