Using for loops.

SOURCE:
fn borgo_main() {
  for x in [1, 2, 3].seq() {
    x.inspect();
  }
}

OUTPUT:
1
2
3

---
package main

import borgo "borgo/runtime"

var _ = borgo.Unit

func borgo_main() any {

	var var1_block any
	{
		var2 := 1
		var3 := 2
		var4 := 3
		var5 := borgo.List(var2, var3, var4)
		var6 := List_seq
		var7 := var6(var5)
		for !borgo.ValuesIsOfType(var7, "Seq::Nil") {
			var8 := borgo.GetArg(var7, 0)
			var9 := var8
			var var10_block any
			{
				var11 := var9
				var12 := Debug_inspect(var11)
				var10_block = var12
			}
			_ = var10_block

			var7 = borgo.GetArg(var7, 1).(func() any)()
		}
		var13 := borgo.Unit
		var1_block = var13
	}
	return var1_block
}

func pkg_user_init() {
	borgo.RegisterGlobalFunction("borgo_main", borgo_main)
}
