#!/usr/bin/env bash

set -euo pipefail

if [ $# -gt 1 ];
then
    echo "USAGE: $0 [--skip-rust]"
    exit 1
fi

mkdir -p static

# Building wasm bindings is very slow
SKIP_RUST=0

if [ ${1:-""} = "--skip-rust" ];
then
  SKIP_RUST=true
fi

cd ../runtime

GOOS=js GOARCH=wasm go build -o ../playground/static/main.wasm interpreter/wasm.go

cd -

if [ $SKIP_RUST = true ];
then
  echo "SKIP BUILDING RUST WASM BINDINGS"
else
  cd ../wasm
  wasm-pack build --target web # --debug
  cp -R pkg ../playground/static
  cd -
fi

cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" "./static/go-wasm-exec.js"

cp -R ../runtime/std ./static

deno run -A build-examples.ts 

npx esbuild --bundle wasm-index.js --outfile=static/bundle.js
