Index expression

SOURCE:
a.b[34]

OUTPUT:
Ident("a", 1)#1,1, Dot#1,2, Ident("b", 1)#1,3, LBrack#1,4, Int("34", 2)#1,5, RBrack#1,7, EOF#1,8
---
No errors.
---
{
  "Index": {
    "expr": {
      "FieldAccess": {
        "expr": {
          "Var": {
            "value": "a",
            "generics_instantiated": []
          }
        },
        "field": "b"
      }
    },
    "index": {
      "Literal": {
        "lit": {
          "Int": 34
        }
      }
    }
  }
}