Match on tuples

SOURCE:
match x {
    (a, 34) => 2
}

OUTPUT:
Match#1,1, Ident("x", 1)#1,7, LCurly#1,9, LParen#2,5, Ident("a", 1)#2,6, Comma#2,7, Int("34", 2)#2,9, RParen#2,11, FatArrow#2,13, Int("2", 1)#2,16, Semicolon#2,17, RCurly#3,1, EOF#3,2
---
No errors.
---
{
  "Match": {
    "subject": {
      "Var": {
        "value": "x",
        "generics_instantiated": []
      }
    },
    "arms": [
      {
        "pat": {
          "Struct": {
            "ident": "Tuple2",
            "fields": [
              {
                "name": "first",
                "value": {
                  "Type": {
                    "ident": "a",
                    "is_mut": false,
                    "ann": "Unknown"
                  }
                }
              },
              {
                "name": "second",
                "value": {
                  "Lit": {
                    "lit": {
                      "Int": 34
                    }
                  }
                }
              }
            ]
          }
        },
        "expr": {
          "Literal": {
            "lit": {
              "Int": 2
            }
          }
        }
      }
    ]
  }
}