Parens

SOURCE:
1 * (2 + 3)

OUTPUT:
Int("1", 1)#1,1, Star#1,3, LParen#1,5, Int("2", 1)#1,6, Plus#1,8, Int("3", 1)#1,10, RParen#1,11, EOF#1,12
---
No errors.
---
{
  "Binary": {
    "op": "Mul",
    "left": {
      "Literal": {
        "lit": {
          "Int": 1
        }
      }
    },
    "right": {
      "Paren": {
        "expr": {
          "Binary": {
            "op": "Add",
            "left": {
              "Literal": {
                "lit": {
                  "Int": 2
                }
              }
            },
            "right": {
              "Literal": {
                "lit": {
                  "Int": 3
                }
              }
            }
          }
        }
      }
    }
  }
}