Precedence I

SOURCE:
3 * 1 + 2

OUTPUT:
Int("3", 1)#1,1, Star#1,3, Int("1", 1)#1,5, Plus#1,7, Int("2", 1)#1,9, EOF#1,10
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Binary": {
        "op": "Mul",
        "left": {
          "Literal": {
            "lit": {
              "Int": 3
            }
          }
        },
        "right": {
          "Literal": {
            "lit": {
              "Int": 1
            }
          }
        }
      }
    },
    "right": {
      "Literal": {
        "lit": {
          "Int": 2
        }
      }
    }
  }
}