Precedence II

SOURCE:
5 + 4 * 7

OUTPUT:
Int("5", 1)#1,1, Plus#1,3, Int("4", 1)#1,5, Star#1,7, Int("7", 1)#1,9, EOF#1,10
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Literal": {
        "lit": {
          "Int": 5
        }
      }
    },
    "right": {
      "Binary": {
        "op": "Mul",
        "left": {
          "Literal": {
            "lit": {
              "Int": 4
            }
          }
        },
        "right": {
          "Literal": {
            "lit": {
              "Int": 7
            }
          }
        }
      }
    }
  }
}