Select statements

SOURCE:
{
    select {
        let x = foo.Recv() => {
        }

        bar.Send() => {
        }

        _ => {
        }
    }
}

OUTPUT:
LCurly#1,1, Select#2,5, LCurly#2,12, Let#3,9, Ident("x", 1)#3,13, Eq#3,15, Ident("foo", 3)#3,17, Dot#3,20, Ident("Recv", 4)#3,21, LParen#3,25, RParen#3,26, FatArrow#3,28, LCurly#3,31, RCurly#4,9, Semicolon#4,10, Ident("bar", 3)#6,9, Dot#6,12, Ident("Send", 4)#6,13, LParen#6,17, RParen#6,18, FatArrow#6,20, LCurly#6,23, RCurly#7,9, Semicolon#7,10, Ident("_", 1)#9,9, FatArrow#9,11, LCurly#9,14, RCurly#10,9, Semicolon#10,10, RCurly#11,5, Semicolon#11,6, RCurly#12,1, EOF#12,2
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Select": {
          "arms": [
            {
              "pat": {
                "Recv": [
                  {
                    "pat": {
                      "Type": {
                        "ident": "x",
                        "is_mut": false,
                        "ann": "Unknown"
                      }
                    },
                    "ann": "Unknown"
                  },
                  {
                    "Call": {
                      "func": {
                        "FieldAccess": {
                          "expr": {
                            "Var": {
                              "value": "foo",
                              "generics_instantiated": []
                            }
                          },
                          "field": "Recv"
                        }
                      },
                      "args": []
                    }
                  }
                ]
              },
              "expr": {
                "Block": {
                  "stmts": []
                }
              }
            },
            {
              "pat": {
                "Send": {
                  "Call": {
                    "func": {
                      "FieldAccess": {
                        "expr": {
                          "Var": {
                            "value": "bar",
                            "generics_instantiated": []
                          }
                        },
                        "field": "Send"
                      }
                    },
                    "args": []
                  }
                }
              },
              "expr": {
                "Block": {
                  "stmts": []
                }
              }
            },
            {
              "pat": "Wildcard",
              "expr": {
                "Block": {
                  "stmts": []
                }
              }
            }
          ]
        }
      }
    ]
  }
}