Slices

SOURCE:
[1, 2, 3]

OUTPUT:
LBrack#1,1, Int("1", 1)#1,2, Comma#1,3, Int("2", 1)#1,5, Comma#1,6, Int("3", 1)#1,8, RBrack#1,9, EOF#1,10
---
No errors.
---
{
  "Literal": {
    "lit": {
      "Slice": [
        {
          "Literal": {
            "lit": {
              "Int": 1
            }
          }
        },
        {
          "Literal": {
            "lit": {
              "Int": 2
            }
          }
        },
        {
          "Literal": {
            "lit": {
              "Int": 3
            }
          }
        }
      ]
    }
  }
}