Struct definition

SOURCE:
struct Foo<T> {
    bar: Bar,
    baz: Baz<T, int>
}

OUTPUT:
Struct#1,1, Ident("Foo", 3)#1,8, LAngle#1,11, Ident("T", 1)#1,12, RAngle#1,13, LCurly#1,15, Ident("bar", 3)#2,5, Colon#2,8, Ident("Bar", 3)#2,10, Comma#2,13, Ident("baz", 3)#3,5, Colon#3,8, Ident("Baz", 3)#3,10, LAngle#3,13, Ident("T", 1)#3,14, Comma#3,15, Ident("int", 3)#3,17, RAngle#3,20, Semicolon#3,21, RCurly#4,1, EOF#4,2
---
No errors.
---
{
  "StructDef": {
    "def": {
      "name": "Foo",
      "generics": [
        {
          "name": "T",
          "bounds": []
        }
      ],
      "fields": [
        {
          "name": "bar",
          "ann": {
            "Con": {
              "name": "Bar",
              "args": []
            }
          }
        },
        {
          "name": "baz",
          "ann": {
            "Con": {
              "name": "Baz",
              "args": [
                {
                  "Con": {
                    "name": "T",
                    "args": []
                  }
                },
                {
                  "Con": {
                    "name": "int",
                    "args": []
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}