Tuple fields

SOURCE:
{
    let a = (true, 1)
    a.0
}

OUTPUT:
LCurly#1,1, Let#2,5, Ident("a", 1)#2,9, Eq#2,11, LParen#2,13, Bool#2,14, Comma#2,18, Int("1", 1)#2,20, RParen#2,21, Semicolon#2,22, Ident("a", 1)#3,5, Dot#3,6, Int("0", 1)#3,7, Semicolon#3,8, RCurly#4,1, EOF#4,2
---
No errors.
---
{
  "Block": {
    "stmts": [
      {
        "Let": {
          "binding": {
            "pat": {
              "Type": {
                "ident": "a",
                "is_mut": false,
                "ann": "Unknown"
              }
            },
            "ann": "Unknown"
          },
          "value": {
            "Tuple": {
              "elems": [
                {
                  "Literal": {
                    "lit": {
                      "Bool": true
                    }
                  }
                },
                {
                  "Literal": {
                    "lit": {
                      "Int": 1
                    }
                  }
                }
              ]
            }
          },
          "mutable": false
        }
      },
      {
        "FieldAccess": {
          "expr": {
            "Var": {
              "value": "a",
              "generics_instantiated": []
            }
          },
          "field": "first"
        }
      }
    ]
  }
}