Tuples

SOURCE:
(a, b, 3 + 5)

OUTPUT:
LParen#1,1, Ident("a", 1)#1,2, Comma#1,3, Ident("b", 1)#1,5, Comma#1,6, Int("3", 1)#1,8, Plus#1,10, Int("5", 1)#1,12, RParen#1,13, EOF#1,14
---
No errors.
---
{
  "Tuple": {
    "elems": [
      {
        "Var": {
          "value": "a",
          "generics_instantiated": []
        }
      },
      {
        "Var": {
          "value": "b",
          "generics_instantiated": []
        }
      },
      {
        "Binary": {
          "op": "Add",
          "left": {
            "Literal": {
              "lit": {
                "Int": 3
              }
            }
          },
          "right": {
            "Literal": {
              "lit": {
                "Int": 5
              }
            }
          }
        }
      }
    ]
  }
}