Unary II

SOURCE:
1 + -5

OUTPUT:
Int("1", 1)#1,1, Plus#1,3, Minus#1,5, Int("5", 1)#1,6, EOF#1,7
---
No errors.
---
{
  "Binary": {
    "op": "Add",
    "left": {
      "Literal": {
        "lit": {
          "Int": 1
        }
      }
    },
    "right": {
      "Unary": {
        "op": "Neg",
        "expr": {
          "Literal": {
            "lit": {
              "Int": 5
            }
          }
        }
      }
    }
  }
}